#!/usr/bin/env python3
"""
Docs index — one source of truth (frontmatter in each feature's primary doc),
two views: a generated Feature Registry block in docs/README.md for humans, and
compact / searchable / graph views for LLM agents.

Usage:
    python3 .cinna-core-kit/scripts/docs_index.py <command> [options]

Commands:
    registry [--check]        Regenerate the Feature Registry block in docs/README.md
                              (--check: exit 1 if the block is stale, write nothing)
    summary [--domain D]      Compact feature list: name — one_liner (per domain)
    search TERM [--limit N] [--feature F] [--domain D] [--include-plans]
                              Case-insensitive text search across docs; hits are
                              grouped by file with feature + nearest heading
    impact [--files F...] [--base REF] [--include-plans]
                              Docs that cover the changed files (default: working
                              tree vs HEAD, plus untracked), expanded one hop along
                              `affects` edges
    path FROM TO              Shortest chain between two features over the doc graph
    graph [--feature F]       Dump feature edges (derived links + authored affects)
    stale [--feature F]       Docs whose referenced code has commits newer than the
                              doc's own last commit (advisory)
    check [--verbose]         Registry block up to date, frontmatter valid, one_liner
                              cap, orphan code modules, route citations vs OpenAPI,
                              tech-doc anchoring. Exit 1 on failures.
    seed                      ONE-TIME migration: derive frontmatter skeletons from
                              the hand-written registry rows and wrap the block in
                              markers. Skips docs that already carry frontmatter.

Frontmatter (first thing in the feature's primary doc):

    ---
    feature: server_channels
    domain: application              # or a list: [application, knowledge]
    one_liner: "Admin-configured server-wide inbound channels routing outside senders to agents."
    docs:                            # other docs of the feature, label -> path
      tech: server_channels_tech.md  # relative to this doc's dir, or docs/-rooted
      debug monitor tech: channel_debug_monitor_tech.md
    primary_label: business logic    # optional; label of THIS doc in the registry
    affects: [routing_tuning]        # optional, directional: change here => review there
    covers: [backend/app/services/server_channels/**]   # optional override globs
    ---

`related` is never authored — it is derived from the links the docs already carry.
"""

import fnmatch
import importlib.util
import json
import os
import re
import subprocess
import sys
from collections import defaultdict, deque

ONE_LINER_MAX = 200
RELATED_MAX = 6  # related features shown per registry row; the rest is "+N more" (full list: `graph`)
MIN_DIR_REF_DEPTH = 4  # directory refs shallower than this are too generic to imply coverage
REGISTRY_START = "<!-- registry:start -->"
REGISTRY_END = "<!-- registry:end -->"
GENERATED_NOTE = (
    "<!-- Generated by .cinna-core-kit/scripts/docs_index.py registry — do not edit by hand.\n"
    "     Edit the frontmatter of each feature's primary doc instead. -->"
)
ROUTE_RE = re.compile(r"\b(GET|POST|PUT|PATCH|DELETE)\s+`?(/api/v1/[^\s`)|,\]>]+)")
CELL_SPLIT_RE = re.compile(r"(?<!\\)\|")
LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")


# --------------------------------------------------------------------------- paths


def project_root():
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.abspath(os.path.join(here, "..", ".."))


ROOT = project_root()
DOCS = os.path.join(ROOT, "docs")
README = os.path.join(DOCS, "README.md")
OPENAPI = os.path.join(ROOT, "frontend", "openapi.json")
ALLOWLIST = os.path.join(ROOT, ".cinna-core-kit", "docs_index_allowlist.txt")


def rel(path):
    return os.path.relpath(path, ROOT).replace(os.sep, "/")


def _load_checker():
    spec = importlib.util.spec_from_file_location(
        "check_docs_references",
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "check_docs_references.py"),
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


CHECKER = _load_checker()


def indexed_docs(include_plans=False):
    """All docs under docs/ that the index reasons about (plans excluded by default)."""
    out = []
    for dirpath, dirnames, files in os.walk(DOCS):
        r = rel(dirpath)
        if not include_plans and r.startswith("docs/plans"):
            dirnames[:] = []
            continue
        for f in files:
            if f.endswith(".md"):
                out.append(rel(os.path.join(dirpath, f)))
    return sorted(out)


def read(path):
    with open(os.path.join(ROOT, path), "r", encoding="utf-8", errors="ignore") as fh:
        return fh.read()


# --------------------------------------------------------------------- frontmatter


def _scalar(v):
    v = v.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
        return v[1:-1].replace('\\"', '"')
    return v


def _flow_list(v):
    inner = v.strip()[1:-1].strip()
    if not inner:
        return []
    return [_scalar(x) for x in inner.split(",")]


def parse_frontmatter(text):
    """
    Minimal YAML-subset parser (stdlib only): top-level `key: scalar`,
    `key: [a, b]`, and block mappings / lists nested one level. Returns
    (dict or None, body_text).
    """
    if not text.startswith("---\n"):
        return None, text
    end = text.find("\n---\n", 4)
    if end < 0:
        return None, text
    block = text[4:end]
    body = text[end + 5 :]
    data = {}
    key = None
    for raw in block.split("\n"):
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        if not raw.startswith(" "):
            k, _, v = raw.partition(":")
            key = k.strip()
            v = v.strip()
            if v.startswith("["):
                data[key] = _flow_list(v)
            elif v == "":
                data[key] = None  # filled by nested lines
            else:
                data[key] = _scalar(v)
            continue
        line = raw.strip()
        if key is None:
            continue
        if line.startswith("- "):
            if not isinstance(data.get(key), list):
                data[key] = []
            data[key].append(_scalar(line[2:]))
        else:
            k, _, v = line.partition(":")
            if not isinstance(data.get(key), dict):
                data[key] = {}
            data[key][k.strip()] = _scalar(v)
    return data, body


def strip_frontmatter(text):
    return parse_frontmatter(text)[1]


def dump_frontmatter(fm):
    """Emit the frontmatter block in the canonical key order."""
    lines = ["---"]
    lines.append("feature: %s" % fm["feature"])
    dom = fm["domain"]
    lines.append("domain: %s" % (("[%s]" % ", ".join(dom)) if isinstance(dom, list) else dom))
    lines.append('one_liner: "%s"' % fm["one_liner"].replace('"', '\\"'))
    if fm.get("docs"):
        lines.append("docs:")
        for label, path in fm["docs"].items():
            lines.append("  %s: %s" % (label, path))
    if fm.get("primary_label") and fm["primary_label"] != "business logic":
        lines.append("primary_label: %s" % fm["primary_label"])
    if fm.get("affects"):
        lines.append("affects: [%s]" % ", ".join(fm["affects"]))
    if fm.get("covers"):
        lines.append("covers: [%s]" % ", ".join(fm["covers"]))
    lines.append("---")
    return "\n".join(lines) + "\n"


# -------------------------------------------------------------------- the index


class Feature:
    def __init__(self, name, primary, fm):
        self.name = name
        self.primary = primary  # docs/-rooted path of the doc carrying the frontmatter
        self.fm = fm
        dom = fm.get("domain") or "unknown"
        self.domains = dom if isinstance(dom, list) else [dom]
        self.one_liner = (fm.get("one_liner") or "").strip()
        self.primary_label = fm.get("primary_label") or "business logic"
        self.affects = fm.get("affects") or []
        self.covers = fm.get("covers") or []
        self.docs = []  # [(label, docs/-rooted path)]
        self.docs.append((self.primary_label, primary))
        base = os.path.dirname(primary)
        for label, p in (fm.get("docs") or {}).items():
            if p.startswith("docs/"):
                resolved = p
            else:
                resolved = os.path.normpath(os.path.join(base, p)).replace(os.sep, "/")
            self.docs.append((label, resolved))

    @property
    def doc_paths(self):
        return [p for _, p in self.docs]


class Index:
    def __init__(self, include_plans=False):
        self.docs = indexed_docs(include_plans)
        self.text = {p: read(p) for p in self.docs}
        self.features = {}  # name -> Feature
        self.owner = {}  # doc path -> feature name
        self.errors = []
        for p in self.docs:
            fm, _ = parse_frontmatter(self.text[p])
            if fm is None:
                continue
            name = fm.get("feature")
            if not name:
                self.errors.append("%s: frontmatter without `feature:`" % p)
                continue
            if name in self.features:
                self.errors.append(
                    "%s: duplicate feature `%s` (also in %s)" % (p, name, self.features[name].primary)
                )
                continue
            self.features[name] = Feature(name, p, fm)
        for f in self.features.values():
            for _, d in f.docs:
                if d in self.owner and self.owner[d] != f.name:
                    self.errors.append(
                        "%s claimed by both `%s` and `%s`" % (d, self.owner[d], f.name)
                    )
                self.owner.setdefault(d, f.name)
        self._refs = None
        self._related = None

    # ---- references: doc -> set(root-relative paths it names)
    @property
    def refs(self):
        if self._refs is None:
            self._refs = {}
            for p in self.docs:
                s = set()
                for line in strip_frontmatter(self.text[p]).split("\n"):
                    if "<!-- nocheck -->" in line:
                        continue
                    s.update(CHECKER.extract_references(line, os.path.join(ROOT, p), ROOT))
                self._refs[p] = s
        return self._refs

    # ---- derived related edges (undirected), from doc->doc links
    @property
    def related(self):
        if self._related is None:
            rel_map = defaultdict(set)
            for f in self.features.values():
                for d in f.doc_paths:
                    for r in self.refs.get(d, ()):
                        g = self.owner.get(r)
                        if g and g != f.name:
                            rel_map[f.name].add(g)
                            rel_map[g].add(f.name)
            self._related = rel_map
        return self._related

    def neighbours(self, name):
        out = set(self.related.get(name, ()))
        out.update(self.features[name].affects if name in self.features else ())
        for g in self.features.values():
            if name in g.affects:
                out.add(g.name)
        return out

    def domain_order(self):
        """Domain order is hand-authored in the README's Domain Map table."""
        order = []
        text = self.text.get("docs/README.md", "")
        in_map = False
        for line in text.split("\n"):
            if line.startswith("## Domain Map"):
                in_map = True
                continue
            if in_map and line.startswith("## "):
                break
            if in_map:
                m = re.match(r"\|\s*\[([a-z_]+)\]\(#", line)
                if m:
                    order.append(m.group(1))
        return order


# ---------------------------------------------------------------- registry view


def render_registry(idx):
    order = idx.domain_order()
    by_domain = defaultdict(list)
    for f in idx.features.values():
        for d in f.domains:
            by_domain[d].append(f)
    unknown = [d for d in by_domain if d not in order]
    lines = [REGISTRY_START, GENERATED_NOTE, ""]
    for d in order + sorted(unknown):
        feats = sorted(by_domain.get(d, []), key=lambda f: f.name)
        if not feats:
            continue
        lines.append("### %s" % d)
        lines.append("")
        lines.append("| Feature | Description | Docs | Related |")
        lines.append("|---------|-------------|------|---------|")
        for f in feats:
            docs = " \\| ".join("[%s](%s)" % (label, p[len("docs/"):]) for label, p in f.docs)
            rel_names = [n for n in sorted(idx.related.get(f.name, ())) if n in idx.features]
            aff = [a for a in f.affects if a not in rel_names and a in idx.features]
            shown = rel_names[:RELATED_MAX]
            parts = ["[%s](%s)" % (n, idx.features[n].primary[len("docs/"):]) for n in shown]
            if len(rel_names) > RELATED_MAX:
                parts.append("+%d more" % (len(rel_names) - RELATED_MAX))
            parts += ["[%s](%s) (affects)" % (n, idx.features[n].primary[len("docs/"):]) for n in aff]
            related = ", ".join(parts)
            desc = f.one_liner.replace("|", "\\|")
            lines.append("| %s | %s | %s | %s |" % (f.name, desc, docs, related))
        lines.append("")
    lines.append(REGISTRY_END)
    return "\n".join(lines)


def cmd_registry(args):
    check = "--check" in args
    idx = Index()
    if idx.errors:
        for e in idx.errors:
            print("ERROR:", e)
        return 1
    text = idx.text["docs/README.md"]
    s, e = text.find(REGISTRY_START), text.find(REGISTRY_END)
    if s < 0 or e < 0:
        print("ERROR: docs/README.md has no registry markers; run `seed` first")
        return 1
    new_block = render_registry(idx)
    new_text = text[:s] + new_block + text[e + len(REGISTRY_END):]
    if new_text == text:
        print("Registry block is up to date (%d features)." % len(idx.features))
        return 0
    if check:
        print("STALE: docs/README.md registry block differs from frontmatter; run "
              "`python3 .cinna-core-kit/scripts/docs_index.py registry`")
        return 1
    with open(README, "w", encoding="utf-8") as fh:
        fh.write(new_text)
    print("Regenerated registry block: %d features." % len(idx.features))
    return 0


# ----------------------------------------------------------------- summary view


def cmd_summary(args):
    only = _opt(args, "--domain")
    idx = Index()
    by_domain = defaultdict(list)
    for f in idx.features.values():
        for d in f.domains:
            by_domain[d].append(f)
    for d in idx.domain_order() + sorted(set(by_domain) - set(idx.domain_order())):
        if only and d != only:
            continue
        feats = sorted(by_domain.get(d, []), key=lambda f: f.name)
        if not feats:
            continue
        print("## %s" % d)
        for f in feats:
            extra = ", ".join("%s: %s" % (l, p) for l, p in f.docs[1:])
            print("- %s — %s  <%s>%s" % (f.name, f.one_liner, f.primary, ("  [%s]" % extra) if extra else ""))
        print()
    return 0


# ------------------------------------------------------------------- search


def cmd_search(args):
    terms = [a for a in args if not a.startswith("--") and a not in _opt_values(args)]
    if not terms:
        print("usage: search TERM [TERM...] [--limit N] [--feature F] [--domain D] [--include-plans]")
        return 2
    limit = int(_opt(args, "--limit") or 50)
    feature = _opt(args, "--feature")
    domain = _opt(args, "--domain")
    idx = Index(include_plans="--include-plans" in args)
    pats = [re.compile(re.escape(t), re.IGNORECASE) for t in terms]
    hits = 0
    for p in idx.docs:
        owner = idx.owner.get(p)
        if feature and owner != feature:
            continue
        if domain and (owner is None or domain not in idx.features[owner].domains):
            continue
        heading = ""
        file_hits = []
        for n, line in enumerate(idx.text[p].split("\n"), 1):
            if line.startswith("#"):
                heading = line.lstrip("#").strip()
            if all(pt.search(line) for pt in pats):
                file_hits.append((n, heading, line.strip()))
        if not file_hits:
            continue
        print("%s  [%s]" % (p, owner or "-"))
        for n, h, l in file_hits:
            print("  %5d  %s%s" % (n, ("(%s) " % h) if h else "", l[:160]))
            hits += 1
            if hits >= limit:
                print("... limit %d reached; narrow with --feature/--domain or raise --limit" % limit)
                return 0
    if hits == 0:
        print("no hits")
    return 0


# ------------------------------------------------------------------- impact


def _glob_re(g):
    out = ""
    i = 0
    while i < len(g):
        if g.startswith("**/", i):
            out += "(?:.*/)?"
            i += 3
        elif g.startswith("**", i):
            out += ".*"
            i += 2
        elif g[i] == "*":
            out += "[^/]*"
            i += 1
        elif g[i] == "?":
            out += "."
            i += 1
        else:
            out += re.escape(g[i])
            i += 1
    return re.compile("^" + out + "$")


def changed_files(args):
    files = _opt_list(args, "--files")
    if files:
        return sorted(set(f.replace(os.sep, "/") for f in files))
    base = _opt(args, "--base")
    if base:
        out = _git(["diff", "--name-only", base])
    else:
        out = _git(["diff", "--name-only", "HEAD"]) + "\n" + _git(
            ["ls-files", "--others", "--exclude-standard"]
        )
    return sorted(set(l.strip() for l in out.split("\n") if l.strip()))


def covering_docs(idx, files):
    """{doc: [(file, how)]} for docs whose references or covers globs match the files."""
    result = defaultdict(list)
    cover_res = {}
    for f in idx.features.values():
        if f.covers:
            cover_res[f.name] = [_glob_re(g) for g in f.covers]
    for doc in idx.docs:
        refs = idx.refs.get(doc, set())
        owner = idx.owner.get(doc)
        for ch in files:
            if ch.startswith("docs/"):
                continue
            hit = None
            for r in refs:
                if r == ch:
                    hit = r
                    break
                # A directory reference counts only when it is specific enough:
                # `backend/app/services/server_channels/` yes, `backend/app/` no.
                if ch.startswith(r.rstrip("/") + "/") and len(r.rstrip("/").split("/")) >= MIN_DIR_REF_DEPTH:
                    hit = r
                    break
            if hit is None and owner in cover_res:
                for cre in cover_res[owner]:
                    if cre.match(ch):
                        hit = "covers:" + cre.pattern
                        break
            if hit is not None:
                result[doc].append((ch, hit))
    return result


def cmd_impact(args):
    idx = Index(include_plans="--include-plans" in args)
    files = changed_files(args)
    code = [f for f in files if not f.startswith("docs/")]
    if not code:
        print("no changed code files (docs-only change or clean tree)")
        return 0
    direct = covering_docs(idx, code)
    print("Changed code files: %d" % len(code))
    if not direct:
        print("No doc names any of the changed files. Consider: is a new feature undocumented?")
        for f in code:
            print("  ", f)
        return 0
    print("\nDocs that name changed files:")
    touched_features = set()
    for doc in sorted(direct):
        owner = idx.owner.get(doc)
        if owner:
            touched_features.add(owner)
        print("  %s  [%s]" % (doc, owner or "-"))
        for ch, how in direct[doc][:6]:
            print("      %s" % ch + ("" if how == ch else "   (via %s)" % how))
        if len(direct[doc]) > 6:
            print("      ... +%d more" % (len(direct[doc]) - 6))
    hop = []
    for name in sorted(touched_features):
        for a in idx.features[name].affects:
            if a in idx.features and a not in touched_features:
                hop.append((a, name))
    if hop:
        print("\nOne hop along `affects` (review these too):")
        for a, src in hop:
            print("  %s  <%s>   because %s affects it" % (a, idx.features[a].primary, src))
    changed_docs = [f for f in files if f.startswith("docs/")]
    if changed_docs:
        print("\nDocs already changed in this diff: %d" % len(changed_docs))
    return 0


# ---------------------------------------------------------------- graph / path


def cmd_graph(args):
    only = _opt(args, "--feature")
    idx = Index()
    names = [only] if only else sorted(idx.features)
    for n in names:
        if n not in idx.features:
            print("unknown feature:", n)
            return 1
        f = idx.features[n]
        print("%s  <%s>" % (n, f.primary))
        for g in sorted(idx.related.get(n, ())):
            print("   related  %s" % g)
        for g in f.affects:
            print("   affects  %s" % g)
        for g in sorted(idx.features):
            if n in idx.features[g].affects:
                print("   affected-by  %s" % g)
    return 0


def cmd_path(args):
    pos = [a for a in args if not a.startswith("--")]
    if len(pos) != 2:
        print("usage: path FROM TO")
        return 2
    src, dst = pos
    idx = Index()
    for n in (src, dst):
        if n not in idx.features:
            print("unknown feature:", n)
            return 1
    prev = {src: None}
    q = deque([src])
    while q:
        cur = q.popleft()
        if cur == dst:
            break
        for nb in sorted(idx.neighbours(cur)):
            if nb not in prev:
                prev[nb] = cur
                q.append(nb)
    if dst not in prev:
        print("no path between %s and %s" % (src, dst))
        return 1
    chain = []
    cur = dst
    while cur is not None:
        chain.append(cur)
        cur = prev[cur]
    chain.reverse()
    for i, n in enumerate(chain):
        print(("  " if i else "") + ("-> " if i else "") + "%s  <%s>" % (n, idx.features[n].primary))
    return 0


# -------------------------------------------------------------------- stale


def _last_commit_times(paths):
    """{path: unix time of last commit touching it}; one git call per path batch."""
    times = {}
    for i in range(0, len(paths), 200):
        batch = paths[i : i + 200]
        out = _git(["log", "--format=%ct", "--name-only", "--", *batch])
        ts = None
        for line in out.split("\n"):
            line = line.strip()
            if not line:
                continue
            if line.isdigit():
                ts = int(line)
                continue
            if line in batch and line not in times:
                times[line] = ts
    return times


def cmd_stale(args):
    only = _opt(args, "--feature")
    idx = Index()
    docs = [d for d in idx.docs if (not only or idx.owner.get(d) == only)]
    code_refs = set()
    for d in docs:
        code_refs.update(r for r in idx.refs.get(d, ()) if not r.startswith("docs/") and os.path.exists(os.path.join(ROOT, r)))
    times = _last_commit_times(docs + sorted(code_refs))
    rows = []
    for d in docs:
        dt = times.get(d)
        if dt is None:
            continue
        newer = [
            (times.get(r, 0), r)
            for r in idx.refs.get(d, ())
            if not r.startswith("docs/") and times.get(r, 0) > dt
        ]
        if newer:
            newer.sort(reverse=True)
            rows.append((len(newer), d, newer[0][1]))
    rows.sort(reverse=True)
    if not rows:
        print("no docs older than the code they reference")
        return 0
    print("Docs whose referenced code changed after the doc's last commit (advisory):")
    for n, d, newest in rows:
        print("  %3d newer  %s  [%s]  e.g. %s" % (n, d, idx.owner.get(d, "-"), newest))
    return 0


# -------------------------------------------------------------------- check


def _allowlist():
    pats = []
    if os.path.exists(ALLOWLIST):
        for line in open(ALLOWLIST, encoding="utf-8"):
            line = line.split("#", 1)[0].strip()
            if line:
                pats.append(line)
    return pats


def orphan_modules(idx):
    mods = []
    for base in ("backend/app/services", "backend/app/api/routes"):
        for dirpath, _, files in os.walk(os.path.join(ROOT, base)):
            for f in files:
                if f.endswith(".py") and f != "__init__.py":
                    mods.append(rel(os.path.join(dirpath, f)))
    corpus = "\n".join(idx.text[p] for p in idx.docs)
    allow = _allowlist()
    out = []
    for m in sorted(mods):
        if os.path.basename(m) in corpus:
            continue
        if any(fnmatch.fnmatch(m, a) for a in allow):
            continue
        out.append(m)
    return out


def stale_routes(idx):
    if not os.path.exists(OPENAPI):
        return None
    spec = json.load(open(OPENAPI, encoding="utf-8"))
    norm = lambda p: re.sub(r"\{[^}]+\}", "{}", p.split("?")[0].rstrip("/").rstrip("]."))
    known = {norm(p) for p in spec.get("paths", {})}
    out = []
    for p in idx.docs:
        for n, line in enumerate(strip_frontmatter(idx.text[p]).split("\n"), 1):
            if "<!-- nocheck -->" in line:
                continue
            for m in ROUTE_RE.finditer(line):
                if norm(m.group(2)) not in known:
                    out.append((p, n, m.group(1) + " " + m.group(2)))
    return out


def cmd_check(args):
    verbose = "--verbose" in args
    idx = Index()
    failures = 0

    def section(title, items, failing=True, fmt=lambda x: x):
        nonlocal failures
        if not items:
            print("OK   %s" % title)
            return
        print("%s %s (%d)" % ("FAIL" if failing else "WARN", title, len(items)))
        for it in items if (verbose or len(items) <= 25) else items[:25]:
            print("     " + fmt(it))
        if not verbose and len(items) > 25:
            print("     ... +%d more (--verbose)" % (len(items) - 25))
        if failing:
            failures += 1

    section("frontmatter parses without conflicts", idx.errors)

    fm_errors = []
    order = set(idx.domain_order())
    for f in idx.features.values():
        if not f.one_liner or f.one_liner.startswith("TODO"):
            fm_errors.append("%s: one_liner missing or TODO" % f.primary)
        elif len(f.one_liner) > ONE_LINER_MAX:
            fm_errors.append("%s: one_liner is %d chars (max %d)" % (f.primary, len(f.one_liner), ONE_LINER_MAX))
        for d in f.domains:
            if d not in order:
                fm_errors.append("%s: domain `%s` is not in the README Domain Map" % (f.primary, d))
        for label, p in f.docs:
            if not os.path.exists(os.path.join(ROOT, p)):
                fm_errors.append("%s: docs.%s -> %s does not exist" % (f.primary, label, p))
        for a in f.affects:
            if a not in idx.features:
                fm_errors.append("%s: affects unknown feature `%s`" % (f.primary, a))
    section("frontmatter fields valid (one_liner <= %d chars, docs exist, affects resolve)" % ONE_LINER_MAX, fm_errors)

    text = idx.text.get("docs/README.md", "")
    if REGISTRY_START in text and REGISTRY_END in text:
        s, e = text.find(REGISTRY_START), text.find(REGISTRY_END)
        current = text[s : e + len(REGISTRY_END)]
        stale = [] if current == render_registry(idx) else ["docs/README.md registry block differs from frontmatter — run `registry`"]
    else:
        stale = ["docs/README.md has no registry markers"]
    section("README registry block is generated from frontmatter", stale)

    section(
        "every service/route module is named by at least one doc",
        orphan_modules(idx),
        fmt=lambda m: m + "   (document it, or allowlist in .cinna-core-kit/docs_index_allowlist.txt)",
    )

    routes = stale_routes(idx)
    if routes is None:
        print("SKIP route citations (frontend/openapi.json not found)")
    else:
        section("route citations exist in frontend/openapi.json", routes, fmt=lambda r: "%s:%d  %s" % r)

    anchoring = []
    for f in idx.features.values():
        for label, p in f.docs:
            if label == "tech" or p.endswith("_tech.md"):
                refs = idx.refs.get(p, set())
                if not any(r.startswith(("backend/", "frontend/")) for r in refs):
                    anchoring.append("%s: tech doc names no backend/ or frontend/ path" % p)
    section("tech docs are anchored to code paths", anchoring)

    # Kit guide 13 is copied into the cloud building prompts by
    # sync_platform_knowledge.py; the copy carries a generated header, so the
    # source must appear in it verbatim.
    design_source = "docs/local_agent_kit/guides/13-design-patterns.md"
    design_prompt = "backend/app/env-templates/app_core_base/core/prompts/AGENT_DESIGN_PATTERNS.md"
    design_drift = []
    if os.path.isfile(os.path.join(ROOT, design_source)):
        with open(os.path.join(ROOT, design_source), encoding="utf-8") as fh:
            source_text = fh.read()
        prompt_path = os.path.join(ROOT, design_prompt)
        prompt_text = ""
        if os.path.isfile(prompt_path):
            with open(prompt_path, encoding="utf-8") as fh:
                prompt_text = fh.read()
        if source_text not in prompt_text:
            design_drift.append(
                "%s is not a copy of %s — run `make sync-platform-knowledge`" % (design_prompt, design_source)
            )
    section("cloud design-patterns prompt is synced from kit guide 13", design_drift)

    unregistered = [
        d for d in idx.docs
        if d not in idx.owner and d != "docs/README.md"
        and not d.startswith(("docs/wiki/", "docs/local_agent_kit/"))
    ]
    section("docs belong to a registered feature", unregistered, failing=False)

    print("\n%s" % ("all checks passed" if failures == 0 else "%d check(s) failed" % failures))
    return 1 if failures else 0


# --------------------------------------------------------------------- seed


def cmd_seed(args):
    """Derive frontmatter skeletons from the hand-written registry, once."""
    text = read("docs/README.md")
    if REGISTRY_START in text:
        print("README already carries registry markers; seed is a one-time migration.")
        return 1
    start = text.find("## Feature Registry")
    end = text.find("## Architecture Overview")
    if start < 0 or end < 0:
        print("could not locate the Feature Registry section")
        return 1
    section = text[start:end]
    domain = None
    seeded, merged, skipped = [], [], []
    for line in section.split("\n"):
        if line.startswith("### "):
            domain = line[4:].strip()
            continue
        if not re.match(r"^\| [a-z_]+ \|", line):
            continue
        cells = [c.strip() for c in CELL_SPLIT_RE.split(line.strip().strip("|"))]
        if len(cells) < 3:
            continue
        name, desc = cells[0], cells[1]
        docs_cell = next((c for c in reversed(cells) if LINK_RE.search(c)), "")
        links = [(l.strip(), p.strip()) for l, p in LINK_RE.findall(docs_cell)]
        if not links:
            skipped.append((name, "no doc links"))
            continue
        primary_label, primary_rel = links[0]
        primary = "docs/" + primary_rel
        if not os.path.exists(os.path.join(ROOT, primary)):
            skipped.append((name, "primary doc missing: " + primary))
            continue
        existing = read(primary)
        fm, body = parse_frontmatter(existing)
        if fm is not None:
            # Cross-listed row (e.g. `workspaces` under sharing pointing at user_workspaces docs):
            # add the domain to the existing feature instead of creating a duplicate.
            doms = fm["domain"] if isinstance(fm["domain"], list) else [fm["domain"]]
            if domain not in doms:
                doms.append(domain)
            fm["domain"] = doms
            with open(os.path.join(ROOT, primary), "w", encoding="utf-8") as fh:
                fh.write(dump_frontmatter(fm) + body)
            merged.append((name, fm["feature"], domain))
            continue
        base = os.path.dirname(primary)
        docs = {}
        for label, p in links[1:]:
            docs[label] = os.path.relpath("docs/" + p, base).replace(os.sep, "/")
        plain = re.sub(r"[*`_]", "", desc)
        first = re.split(r"(?<=[.;])\s", plain, 1)[0]
        one_liner = "TODO " + first[:ONE_LINER_MAX - 5].rstrip()
        fm = {
            "feature": name,
            "domain": domain,
            "one_liner": one_liner,
            "docs": docs,
            "primary_label": primary_label,
        }
        with open(os.path.join(ROOT, primary), "w", encoding="utf-8") as fh:
            fh.write(dump_frontmatter(fm) + existing)
        seeded.append((name, primary))
    # Wrap the registry section in markers; the old rows stay until `registry` regenerates.
    new_section = "## Feature Registry\n\n" + REGISTRY_START + "\n" + section[len("## Feature Registry"):].strip("\n") + "\n" + REGISTRY_END + "\n\n"
    with open(README, "w", encoding="utf-8") as fh:
        fh.write(text[:start] + new_section + text[end:])
    print("seeded %d features, merged %d cross-listed rows, skipped %d" % (len(seeded), len(merged), len(skipped)))
    for m in merged:
        print("  merged row `%s` into feature `%s` (domain %s)" % m)
    for s in skipped:
        print("  skipped `%s`: %s" % s)
    print("Next: replace every `TODO` one_liner, then run `registry` and `check`.")
    return 0


# ------------------------------------------------------------------- helpers


def _git(argv):
    return subprocess.run(["git", *argv], cwd=ROOT, capture_output=True, text=True).stdout


def _opt(args, flag):
    if flag in args:
        i = args.index(flag)
        if i + 1 < len(args):
            return args[i + 1]
    return None


def _opt_values(args):
    vals = set()
    for flag in ("--limit", "--feature", "--domain", "--base"):
        v = _opt(args, flag)
        if v:
            vals.add(v)
    return vals


def _opt_list(args, flag):
    if flag not in args:
        return []
    out = []
    for a in args[args.index(flag) + 1 :]:
        if a.startswith("--"):
            break
        out.append(a)
    return out


COMMANDS = {
    "registry": cmd_registry,
    "summary": cmd_summary,
    "search": cmd_search,
    "impact": cmd_impact,
    "path": cmd_path,
    "graph": cmd_graph,
    "stale": cmd_stale,
    "check": cmd_check,
    "seed": cmd_seed,
}


def main():
    if len(sys.argv) < 2 or sys.argv[1] in ("-h", "--help") or sys.argv[1] not in COMMANDS:
        print(__doc__)
        return 2
    return COMMANDS[sys.argv[1]](sys.argv[2:])


if __name__ == "__main__":
    sys.exit(main())
