"""
OpenCode SDK Adapter

Orchestrates the opencode serve subprocess lifecycle — server management,
session creation, SSE streaming, and interrupt handling.
Event translation is delegated to OpenCodeEventTransformer.

This adapter handles all opencode/* variants by running `opencode serve` as a
background subprocess and communicating with it over HTTP + SSE.

Supported providers (determined at runtime from the linked credential):
- opencode/anthropic: Anthropic Claude via OpenCode
- opencode/openai: OpenAI GPT models via OpenCode
- opencode/openai_compatible: Any OpenAI-compatible endpoint via OpenCode
- opencode/google: Google Gemini via OpenCode
- opencode (default): Falls back to Anthropic

Unlike Claude Code (which embeds the provider in the SDK ID), the OpenCode
adapter determines its provider from the credential type at environment creation
time. The credential's API key and endpoint are baked into the per-mode config
files at /app/core/.opencode/{mode}/.

Architecture:
    Each mode (building / conversation) runs its own `opencode serve` instance
    on a dedicated port with its own config directory:

    building:     port 4096, config /app/core/.opencode/building/opencode.json
    conversation: port 4097, config /app/core/.opencode/conversation/opencode.json

    This allows different models, permissions, and MCP servers per mode without
    any shared state or race conditions between concurrent sessions.

    opencode serve (subprocess, per-mode port)
        <- POST /session              create session
        <- POST /session/:id/message  send message (session resumption)
        <- GET /global/event          SSE event stream
        <- DELETE /session/:id        interrupt session

Config files (generated by backend at environment creation / rebuild):
    /app/core/.opencode/building/opencode.json
    /app/core/.opencode/conversation/opencode.json
    Runtime AGENTS.md written per request from system prompt.

Session context (written before each message for MCP bridge servers):
    /tmp/.opencode_{mode}/session_context.json
"""

import asyncio
import json
import logging
import os
from pathlib import Path
from typing import AsyncIterator, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Lazy import guard for aiohttp — avoids import errors when the adapter is
# imported but OpenCode is not in use.
# ---------------------------------------------------------------------------

def _import_aiohttp():
    try:
        import aiohttp
        return aiohttp
    except ImportError:
        return None


from .base import (
    BaseSDKAdapter,
    SDKEvent,
    SDKEventType,
    SDKConfig,
    AdapterRegistry,
)
from .opencode_event_transformer import OpenCodeEventTransformer
from .tool_name_registry import normalize_tool_name
from ..prompt_generator import PromptGenerator
from ..active_session_manager import active_session_manager
from ..agent_env_service import AgentEnvService


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

OPENCODE_CONFIG_DIR = Path("/app/core/.opencode")

# Per-mode ports — each mode runs its own opencode serve instance
OPENCODE_MODE_PORTS = {
    "building": 4096,
    "conversation": 4097,
}

# How long to wait for opencode serve to become healthy on first start (seconds)
OPENCODE_STARTUP_TIMEOUT = 30

# How long to wait without meaningful SSE events (text, tool, done) before
# timing out.  Heartbeats keep the socket alive but don't count as progress.
OPENCODE_PROGRESS_TIMEOUT = 120  # seconds

# OpenCode built-in tools exposed to users
OPENCODE_BUILTIN_TOOLS = [
    "bash", "read", "write", "edit", "glob", "grep",
    "list", "patch", "webfetch", "websearch",
]


# ---------------------------------------------------------------------------
# Adapter
# ---------------------------------------------------------------------------

@AdapterRegistry.register
class OpenCodeAdapter(BaseSDKAdapter):
    """
    OpenCode adapter — wraps an `opencode serve` HTTP server.

    Each mode (building / conversation) gets its own adapter instance with
    its own opencode serve process on a dedicated port, so there is no
    shared state between concurrent building and conversation sessions.

    Supports all opencode/* variants. Provider is determined from the
    config files generated at environment creation time.
    """

    ADAPTER_TYPE = "opencode"
    SUPPORTED_PROVIDERS = [
        "anthropic", "openai", "openai_compatible",
        "google", "default",
    ]

    def __init__(self, config: SDKConfig):
        super().__init__(config)

        self.prompt_generator = PromptGenerator(self.workspace_dir)

        # Agent env service for plugin management (mirrors ClaudeCodeAdapter)
        self.agent_env_service = AgentEnvService(self.workspace_dir)

        # Server process — started lazily on first send_message_stream call
        self._server_process: Optional[asyncio.subprocess.Process] = None

        # Lock to prevent concurrent server starts
        self._start_lock = asyncio.Lock()

        # Current session ID — tracked across calls
        self._current_session_id: Optional[str] = None

        # Per-mode port and runtime dir are resolved on first use
        # (when mode is known from send_message_stream)
        self._mode: Optional[str] = None
        self._port: Optional[int] = None
        self._base_url: Optional[str] = None
        self._runtime_dir: Optional[Path] = None

        # Event transformer — translates raw OpenCode SSE events to SDKEvents
        self._event_transformer = OpenCodeEventTransformer(self.workspace_dir)

    def _resolve_mode(self, mode: str) -> None:
        """
        Resolve per-mode paths and port on first use.

        Called once per adapter instance — subsequent calls with the same
        mode are no-ops.  Different modes get different adapter instances
        via SDKManager caching.
        """
        if self._mode == mode:
            return
        self._mode = mode
        self._port = OPENCODE_MODE_PORTS.get(mode, 4096)
        self._base_url = f"http://127.0.0.1:{self._port}"
        self._runtime_dir = Path(f"/tmp/.opencode_{mode}")

    # ------------------------------------------------------------------
    # Process management
    # ------------------------------------------------------------------

    async def _start_opencode_server(self) -> None:
        """
        Launch `opencode serve` as an asyncio subprocess.

        Each mode gets its own server process on a dedicated port with its
        own runtime directory.  Config files are symlinked from the read-only
        per-mode config dir (/app/core/.opencode/{mode}/) into the writable
        runtime dir (/tmp/.opencode_{mode}/).
        """
        logger.info(
            "Starting opencode serve for mode=%s on port %d...",
            self._mode, self._port,
        )

        env = {**os.environ, "OPENCODE_SKIP_UPDATE": "1"}

        # Ensure the runtime directory exists (writable, unlike OPENCODE_CONFIG_DIR
        # which is mounted read-only via the /app/core:ro volume).
        self._runtime_dir.mkdir(parents=True, exist_ok=True)

        # Symlink static config files from the read-only per-mode config dir
        # into the writable runtime dir so opencode finds everything in one place.
        mode_config_dir = OPENCODE_CONFIG_DIR / self._mode
        if mode_config_dir.is_dir():
            for config_file in mode_config_dir.iterdir():
                if config_file.is_file():
                    link = self._runtime_dir / config_file.name
                    if not link.exists():
                        link.symlink_to(config_file)

        # opencode reads config from the current directory or XDG dirs.
        # We point it at our runtime dir as cwd so it finds opencode.json,
        # AGENTS.md, and session_context.json there.
        self._server_process = await asyncio.create_subprocess_exec(
            "opencode", "serve",
            "--port", str(self._port),
            "--hostname", "127.0.0.1",
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
            env=env,
            cwd=str(self._runtime_dir),
        )

        logger.info(
            "opencode serve started for mode=%s (pid=%d, port=%d)",
            self._mode, self._server_process.pid, self._port,
        )

        # Wait for the server to become healthy
        await self._wait_for_server_health()

    async def _wait_for_server_health(self) -> None:
        """Poll the server until it responds or the timeout is reached."""
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            # Can't check health without aiohttp — give a fixed delay
            await asyncio.sleep(3)
            return

        deadline = asyncio.get_running_loop().time() + OPENCODE_STARTUP_TIMEOUT
        last_error: Optional[Exception] = None

        while asyncio.get_running_loop().time() < deadline:
            # Check if process died already
            if self._server_process and self._server_process.returncode is not None:
                raise RuntimeError(
                    f"opencode serve exited prematurely with code "
                    f"{self._server_process.returncode}"
                )

            try:
                async with aiohttp.ClientSession() as session:
                    # Try /health first; fall back to /doc (always exists)
                    for path in ("/health", "/doc"):
                        try:
                            async with session.get(
                                f"{self._base_url}{path}",
                                timeout=aiohttp.ClientTimeout(total=2),
                            ) as resp:
                                if resp.status < 500:
                                    logger.info(
                                        "opencode serve is healthy (status=%d on %s)",
                                        resp.status, path,
                                    )
                                    return
                        except Exception:
                            pass
            except Exception as exc:
                last_error = exc

            await asyncio.sleep(1)

        raise RuntimeError(
            f"opencode serve did not become healthy within "
            f"{OPENCODE_STARTUP_TIMEOUT}s. Last error: {last_error}"
        )

    async def _ensure_server_running(self) -> None:
        """
        Ensure the opencode server is running. Starts it if not running.

        Uses a lock to prevent multiple concurrent starts.
        """
        async with self._start_lock:
            # Check if process exists and is still alive
            process_alive = (
                self._server_process is not None
                and self._server_process.returncode is None
            )

            if not process_alive:
                if self._server_process is not None:
                    logger.warning(
                        "opencode serve process exited (code=%d), restarting...",
                        self._server_process.returncode,
                    )
                # Clear stale session ID so the next request creates a fresh session
                self._current_session_id = None
                await self._start_opencode_server()

    # ------------------------------------------------------------------
    # HTTP helpers
    # ------------------------------------------------------------------

    async def _create_session(self) -> str:
        """
        POST /session — create a new OpenCode session.

        Returns the session ID string.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            raise RuntimeError("aiohttp is required for OpenCodeAdapter but is not installed")

        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"{self._base_url}/session",
                json={},
                timeout=aiohttp.ClientTimeout(total=30),
            ) as resp:
                resp.raise_for_status()
                data = await resp.json()
                session_id = data.get("id") or data.get("sessionId") or data.get("session_id")
                if not session_id:
                    raise RuntimeError(f"POST /session returned no session id: {data}")
                logger.info("Created OpenCode session: %s", session_id)
                self._event_transformer.event_logger.log_send(
                    "create_session", {"session_id": session_id}
                )
                return session_id

    async def _post_message(self, session_id: str, message: str) -> None:
        """
        POST /session/:id/message — send a user message to the session.

        This triggers OpenCode to start processing; actual response comes
        through the SSE stream on GET /global/event.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            raise RuntimeError("aiohttp is required for OpenCodeAdapter but is not installed")

        body = {
            "role": "user",
            "parts": [{"type": "text", "text": message}],
        }

        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"{self._base_url}/session/{session_id}/message",
                json=body,
                timeout=aiohttp.ClientTimeout(total=60),
            ) as resp:
                if resp.status >= 400:
                    text = await resp.text()
                    raise RuntimeError(
                        f"POST /session/{session_id}/message failed "
                        f"({resp.status}): {text}"
                    )
                logger.info("Message sent to OpenCode session %s", session_id)
                self._event_transformer.event_logger.log_send(
                    "post_message",
                    {"session_id": session_id, "message": message},
                )

    # ------------------------------------------------------------------
    # System prompt
    # ------------------------------------------------------------------

    async def _write_agents_md(self, system_prompt: str) -> None:
        """Write the system prompt to AGENTS.md in the runtime directory."""
        agents_md_path = self._runtime_dir / "AGENTS.md"
        self._runtime_dir.mkdir(parents=True, exist_ok=True)
        agents_md_path.write_text(system_prompt, encoding="utf-8")
        logger.info("Wrote AGENTS.md (%d chars)", len(system_prompt))
        self._event_transformer.event_logger.log_send(
            "write_agents_md", {"chars": len(system_prompt)}
        )

    async def _write_session_context(
        self,
        opencode_session_id: str,
        backend_session_id: Optional[str],
    ) -> None:
        """
        Write session context for MCP bridge servers.

        The MCP bridge servers (knowledge_server.py, task_server.py)
        read this file at tool-call time to obtain the
        current backend_session_id without needing to be passed it at startup.
        """
        context = {
            "opencode_session_id": opencode_session_id,
            "backend_session_id": backend_session_id or "",
        }
        context_path = self._runtime_dir / "session_context.json"
        self._runtime_dir.mkdir(parents=True, exist_ok=True)
        context_path.write_text(json.dumps(context, indent=2), encoding="utf-8")
        logger.debug(
            "Wrote session_context.json (opencode=%s, backend=%s)",
            opencode_session_id,
            backend_session_id,
        )

    def _build_plugin_mcp_config(self, mode: str) -> dict:
        """
        Build MCP config entries for active agent plugins.

        Mirrors the plugin loading in ClaudeCodeAdapter but produces the dict
        format used by OpenCode's mcp config section.

        Returns:
            Dict mapping plugin MCP server names to their config entries.
        """
        plugin_mcp: dict = {}
        try:
            active_plugins = self.agent_env_service.get_active_plugins_for_mode(mode)
            for plugin in active_plugins:
                path = plugin.get("path", "")
                if not path:
                    continue
                plugin_name = plugin.get("name", Path(path).parent.name)
                # Use a namespaced key to avoid collisions with bridge servers
                key = f"plugin_{plugin_name}"
                plugin_mcp[key] = {
                    "type": "local",
                    "command": ["python3", path],
                    "enabled": True,
                }
            if plugin_mcp:
                logger.info(
                    "Built plugin MCP config for %s mode: %d plugin(s)",
                    mode,
                    len(plugin_mcp),
                )
        except Exception as exc:  # noqa: BLE001
            logger.warning("Could not build plugin MCP config: %s", exc)
        return plugin_mcp

    # ------------------------------------------------------------------
    # SSE event parsing
    # ------------------------------------------------------------------

    @staticmethod
    def _parse_sse_event(raw_data: str) -> Optional[dict]:
        """
        Parse a single SSE data payload into a dict.

        OpenCode wraps events in a ``{"payload": {...}}`` envelope.
        This method unwraps it so callers always see the inner event dict
        with ``type`` and ``properties`` at the top level.

        Returns None if parsing fails or the payload is not meaningful.
        """
        stripped = raw_data.strip()
        if not stripped or stripped == ":":
            return None
        try:
            parsed = json.loads(stripped)
            # Unwrap the payload envelope if present
            if "payload" in parsed and isinstance(parsed["payload"], dict):
                parsed = parsed["payload"]
            return parsed
        except json.JSONDecodeError:
            logger.debug("Skipping non-JSON SSE data: %s", stripped[:100])
            return None

    # ------------------------------------------------------------------
    # Main send/stream
    # ------------------------------------------------------------------

    async def send_message_stream(
        self,
        message: str,
        session_id: Optional[str] = None,
        backend_session_id: Optional[str] = None,
        system_prompt: Optional[str] = None,
        mode: str = "conversation",
        session_state: Optional[dict] = None,
    ) -> AsyncIterator[SDKEvent]:
        """
        Send a message via the OpenCode server and stream back SDKEvents.

        Flow:
        1. Resolve per-mode port/dir and ensure opencode serve is running.
        2. Create or resume session.
        3. Register session with active_session_manager for interrupt support.
        4. Write session_context.json for MCP bridge servers.
        5. Write AGENTS.md with the resolved system prompt.
        6. Emit tools_init event.
        7-8. Connect SSE stream, wait for first event, then POST message.
             SSE must be connected before posting so no events are missed.
        9. Unregister session on completion.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            yield SDKEvent(
                type=SDKEventType.ERROR,
                content="aiohttp is not installed in this environment. "
                        "OpenCode adapter requires aiohttp.",
                error_type="ImportError",
            )
            return

        try:
            # 1. Resolve per-mode port/dir and ensure server is running
            self._resolve_mode(mode)
            await self._ensure_server_running()

            # 2. Create or resume session
            is_new_session = not session_id
            if is_new_session:
                session_id = await self._create_session()
                self._current_session_id = session_id
                yield SDKEvent(
                    type=SDKEventType.SESSION_CREATED,
                    session_id=session_id,
                    content="",
                )
            else:
                self._current_session_id = session_id
                logger.info("Resuming OpenCode session: %s", session_id)
                yield SDKEvent(
                    type=SDKEventType.SESSION_RESUMED,
                    session_id=session_id,
                    content="",
                )

            # 3. Register with active_session_manager for interrupt support.
            # We pass None as the client since OpenCode interrupt uses HTTP DELETE,
            # not a client method. The manager tracks the session for interrupt flagging.
            await active_session_manager.register_session(session_id, None)

            # 4. Write session context so MCP bridge servers can find backend_session_id
            await self._write_session_context(session_id, backend_session_id)

            # 5. Resolve system prompt and write AGENTS.md
            if system_prompt:
                resolved_prompt = system_prompt
                logger.info("Using explicit system_prompt override")
            else:
                try:
                    generated = self.prompt_generator.generate_prompt(
                        mode, session_state=session_state
                    )
                    # Building mode may return a dict; extract 'append' field
                    if isinstance(generated, dict):
                        resolved_prompt = generated.get("append", "")
                    else:
                        resolved_prompt = generated or ""
                    logger.info(
                        "Generated %s mode prompt (%d chars)",
                        mode, len(resolved_prompt),
                    )
                except ValueError as exc:
                    await active_session_manager.unregister_session(session_id)
                    yield SDKEvent(
                        type=SDKEventType.ERROR,
                        content=str(exc),
                        error_type="ValueError",
                    )
                    return

            await self._write_agents_md(resolved_prompt)

            # 6. Build tools list including plugin MCP servers
            # All tool names are normalized to unified lowercase convention.
            # OpenCode built-ins are already lowercase; MCP bridge tools use
            # the mcp__agent_task__* prefix matching Claude Code naming.
            plugin_mcp = self._build_plugin_mcp_config(mode)
            all_tools = list(OPENCODE_BUILTIN_TOOLS)
            mcp_tool_names = [
                "mcp__knowledge__query_integration_knowledge",
                "mcp__agent_task__add_comment",
                "mcp__agent_task__update_status",
                "mcp__agent_task__create_task",
                "mcp__agent_task__create_subtask",
                "mcp__agent_task__get_details",
                "mcp__agent_task__list_tasks",
            ]
            for key in plugin_mcp:
                mcp_tool_names.append(f"mcp__{key}")
            all_tools.extend(mcp_tool_names)

            yield SDKEvent(
                type=SDKEventType.SYSTEM,
                subtype="tools_init",
                content="",
                data={"tools": all_tools},
            )

            # 7-8. Connect SSE stream FIRST, then send the message once
            #      connected so we don't miss any events.
            # The POST is fired as a background task because it can block
            # until the LLM finishes responding.
            interrupt_initiated = False
            message_posted = False
            post_task: Optional[asyncio.Task] = None
            last_progress_time = asyncio.get_running_loop().time()
            try:
                async with aiohttp.ClientSession() as http_session:
                    async with http_session.get(
                        f"{self._base_url}/global/event",
                        timeout=aiohttp.ClientTimeout(total=None, sock_read=300),
                    ) as sse_resp:
                        if sse_resp.status >= 400:
                            text = await sse_resp.text()
                            yield SDKEvent(
                                type=SDKEventType.ERROR,
                                content=f"GET /global/event failed ({sse_resp.status}): {text}",
                                error_type="OpenCodeError",
                                session_id=session_id,
                            )
                            return

                        # Reset event adapter state for this message exchange
                        self._event_transformer.reset()

                        buffer = ""
                        async for raw_bytes in sse_resp.content:
                            # Check for interrupt request between SSE chunks
                            if not interrupt_initiated and await active_session_manager.check_interrupt_requested(session_id):
                                logger.info(
                                    "Interrupt detected for OpenCode session %s",
                                    session_id,
                                )
                                interrupt_initiated = True
                                await self._delete_session(session_id)
                                yield SDKEvent(
                                    type=SDKEventType.INTERRUPTED,
                                    session_id=session_id,
                                    content="Message interrupted by user",
                                    metadata={"reason": "interrupt_requested"},
                                )
                                return

                            # Check progress timeout — if only heartbeats
                            # (or no events at all) for too long, the session
                            # is likely stuck (e.g. a tool hung on a directory).
                            now = asyncio.get_running_loop().time()
                            if message_posted and (now - last_progress_time) > OPENCODE_PROGRESS_TIMEOUT:
                                logger.error(
                                    "No progress for %ds on OpenCode session %s — aborting",
                                    OPENCODE_PROGRESS_TIMEOUT, session_id,
                                )
                                await self._delete_session(session_id)
                                yield SDKEvent(
                                    type=SDKEventType.ERROR,
                                    session_id=session_id,
                                    content=f"OpenCode session timed out — no progress for {OPENCODE_PROGRESS_TIMEOUT}s. "
                                            "A tool may have hung (e.g. reading a directory instead of a file).",
                                    error_type="ProgressTimeout",
                                )
                                return

                            line = raw_bytes.decode("utf-8", errors="replace")
                            buffer += line

                            # SSE events are separated by double newlines
                            while "\n\n" in buffer:
                                event_block, buffer = buffer.split("\n\n", 1)
                                for sse_line in event_block.split("\n"):
                                    sse_line = sse_line.strip()
                                    if sse_line.startswith("data:"):
                                        raw_data = sse_line[5:].strip()
                                        event_data = self._parse_sse_event(raw_data)
                                        if event_data is None:
                                            continue

                                        event_type = event_data.get("type", "")

                                        # Post message once SSE stream is alive.
                                        # We trigger on the first event (any type)
                                        # because on session resume opencode may
                                        # send project.updated instead of
                                        # server.connected as the first event.
                                        # Fired as background task — POST can block
                                        # until the LLM finishes responding.
                                        if not message_posted:
                                            logger.info(
                                                "SSE alive (first event: %s), posting message to session %s",
                                                event_type, session_id,
                                            )
                                            post_task = asyncio.create_task(
                                                self._post_message(session_id, message)
                                            )
                                            message_posted = True
                                            # Skip server lifecycle events
                                            if event_type in ("server.connected", "server.heartbeat"):
                                                continue

                                        # Skip heartbeats (high frequency, no value)
                                        if event_type == "server.heartbeat":
                                            continue

                                        # Reset progress timer on meaningful events
                                        # (anything except heartbeats, which are
                                        # already filtered above)
                                        last_progress_time = now

                                        # Translate via event adapter
                                        sdk_events = self._event_transformer.translate(
                                            event_data, session_id
                                        )
                                        for sdk_event in sdk_events:
                                            yield sdk_event

                                            if sdk_event.type in (
                                                SDKEventType.DONE,
                                                SDKEventType.ERROR,
                                                SDKEventType.INTERRUPTED,
                                            ):
                                                return
            finally:
                # Ensure the POST task is awaited to catch errors
                if post_task is not None and not post_task.done():
                    post_task.cancel()
                    try:
                        await post_task
                    except (asyncio.CancelledError, Exception):
                        pass
                elif post_task is not None and post_task.done():
                    # Re-raise any exception from the POST
                    exc = post_task.exception() if not post_task.cancelled() else None
                    if exc:
                        logger.error("POST message failed: %s", exc)
                # 9. Always unregister session on exit
                await active_session_manager.unregister_session(session_id)

        except asyncio.CancelledError:
            logger.info(
                "OpenCode stream cancelled for session %s", session_id
            )
            if session_id:
                await active_session_manager.unregister_session(session_id)
            yield SDKEvent(
                type=SDKEventType.INTERRUPTED,
                session_id=session_id,
                content="Message interrupted by user",
                metadata={"reason": "cancelled"},
            )

        except asyncio.TimeoutError:
            logger.error(
                "OpenCode stream timed out for session %s", session_id
            )
            if session_id:
                await active_session_manager.unregister_session(session_id)
            yield SDKEvent(
                type=SDKEventType.ERROR,
                content="OpenCode response timed out",
                error_type="TimeoutError",
                session_id=session_id,
            )

        except Exception as exc:
            logger.error(
                "OpenCode adapter error for session %s: %s",
                session_id, exc, exc_info=True,
            )
            if session_id:
                await active_session_manager.unregister_session(session_id)
            yield SDKEvent(
                type=SDKEventType.ERROR,
                content=f"OpenCode error: {str(exc)}",
                error_type=type(exc).__name__,
                session_id=session_id,
            )

    # ------------------------------------------------------------------
    # Interrupt
    # ------------------------------------------------------------------

    async def _delete_session(self, session_id: str) -> bool:
        """
        Send DELETE /session/:id to cancel an active OpenCode session.

        This is used for interrupt support. OpenCode stops processing when the
        session is deleted. Returns True if the server accepted the request.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            return False

        try:
            async with aiohttp.ClientSession() as session:
                async with session.delete(
                    f"{self._base_url}/session/{session_id}",
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    # 404 is acceptable — session may have already completed
                    success = resp.status in (200, 204, 404)
                    if success:
                        logger.info(
                            "Deleted OpenCode session %s (status=%d)",
                            session_id, resp.status,
                        )
                    else:
                        logger.warning(
                            "DELETE /session/%s returned %d",
                            session_id, resp.status,
                        )
                    return success
        except Exception as exc:
            logger.error(
                "Failed to delete OpenCode session %s: %s", session_id, exc
            )
            return False

    async def interrupt_session(self, session_id: str) -> bool:
        """
        Interrupt an active OpenCode session.

        This integrates with active_session_manager: we set the interrupt flag
        which is checked in the SSE streaming loop. The loop then calls
        _delete_session() to signal OpenCode to stop.

        Fallback: if the session is not registered (e.g., already finishing),
        we call _delete_session() directly.

        Returns True if the interrupt was accepted.
        """
        # Request interrupt via active_session_manager (checked in SSE loop)
        flagged = await active_session_manager.request_interrupt(session_id)
        if flagged:
            logger.info("Interrupt flagged for OpenCode session %s", session_id)
            return True

        # Fallback: direct HTTP delete if session is not registered
        logger.info(
            "Session %s not registered; attempting direct HTTP delete for interrupt",
            session_id,
        )
        return await self._delete_session(session_id)
