"""
OpenCode SDK Adapter

Orchestrates the opencode serve subprocess lifecycle — server management,
session creation, SSE streaming, and interrupt handling.
Event translation is delegated to OpenCodeEventTransformer.

This adapter handles all opencode/* variants by running `opencode serve` as a
background subprocess and communicating with it over HTTP + SSE.

Supported providers (determined at runtime from the linked credential):
- opencode/anthropic: Anthropic Claude via OpenCode
- opencode/openai: OpenAI GPT models via OpenCode
- opencode/openai_compatible: Any OpenAI-compatible endpoint via OpenCode
- opencode/google: Google Gemini via OpenCode
- opencode (default): Falls back to Anthropic

Unlike Claude Code (which embeds the provider in the SDK ID), the OpenCode
adapter determines its provider from the credential type at environment creation
time. The credential's API key and endpoint are baked into the per-mode config
files at /app/core/.opencode/{mode}/.

Architecture:
    Each mode (building / conversation) runs its own `opencode serve` instance
    on a dedicated port with its own config directory:

    building:     port 4096, config /app/core/.opencode/building/opencode.json
    conversation: port 4097, config /app/core/.opencode/conversation/opencode.json

    This allows different models, permissions, and MCP servers per mode without
    any shared state or race conditions between concurrent sessions.

    opencode serve (subprocess, per-mode port)
        <- POST /session              create session
        <- POST /session/:id/message  send message (session resumption)
        <- GET /global/event          SSE event stream
        <- DELETE /session/:id        interrupt session

Config files (generated by backend at environment creation / rebuild):
    /app/core/.opencode/building/opencode.json
    /app/core/.opencode/conversation/opencode.json
    Runtime AGENTS.md written per request from system prompt.

Session context (written before each message for MCP bridge servers):
    /tmp/.opencode_{mode}/session_context.json
"""

import asyncio
import json
import logging
import os
import shutil
from pathlib import Path
from typing import AsyncIterator, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Lazy import guard for aiohttp — avoids import errors when the adapter is
# imported but OpenCode is not in use.
# ---------------------------------------------------------------------------

def _import_aiohttp():
    try:
        import aiohttp
        return aiohttp
    except ImportError:
        return None


from .base import (
    BaseSDKAdapter,
    SDKEvent,
    SDKEventType,
    SDKConfig,
    AdapterRegistry,
)
from .opencode_event_transformer import (
    OpenCodeEventTransformer,
    OPENCODE_QUESTION_REQUEST_ID_KEY,
)
from .tool_name_registry import normalize_tool_name
from ..prompt_generator import PromptGenerator
from ..active_session_manager import active_session_manager
from ..agent_env_service import AgentEnvService


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

OPENCODE_CONFIG_DIR = Path("/app/core/.opencode")

# Per-mode ports — each mode runs its own opencode serve instance
OPENCODE_MODE_PORTS = {
    "building": 4096,
    "conversation": 4097,
}

# How long to wait for opencode serve to become healthy on first start (seconds)
OPENCODE_STARTUP_TIMEOUT = 30

# How long to wait for a terminated opencode serve to exit before killing it
OPENCODE_STOP_TIMEOUT = 10

# How long to wait without meaningful SSE events (text, tool, done) before
# timing out.  Heartbeats keep the socket alive but don't count as progress.
OPENCODE_PROGRESS_TIMEOUT = 120  # seconds

# Per-mode opencode runtime dir (writable, unlike the read-only core config
# volume). Holds the symlinked opencode.json, the per-request AGENTS.md, and
# session_context.json. `{mode}` is formatted in.
#
# COUPLING (host ⇄ container): the host-side config generator in
# ``app/services/environments/environment_lifecycle.py`` bakes the absolute
# AGENTS.md path under this dir into opencode.json's ``instructions`` so the
# system prompt loads regardless of the session's project directory. That module
# runs on the host and cannot import this one (which runs inside the container),
# so it MIRRORS these two constants — keep them in sync.
OPENCODE_RUNTIME_DIR_TEMPLATE = "/tmp/.opencode_{mode}"
OPENCODE_AGENTS_MD_FILENAME = "AGENTS.md"

# OpenCode built-in tools exposed to users
OPENCODE_BUILTIN_TOOLS = [
    "bash", "read", "write", "edit", "glob", "grep",
    "list", "patch", "webfetch", "websearch",
]


# ---------------------------------------------------------------------------
# Adapter
# ---------------------------------------------------------------------------

@AdapterRegistry.register
class OpenCodeAdapter(BaseSDKAdapter):
    """
    OpenCode adapter — wraps an `opencode serve` HTTP server.

    Each mode (building / conversation) gets its own adapter instance with
    its own opencode serve process on a dedicated port, so there is no
    shared state between concurrent building and conversation sessions.

    Supports all opencode/* variants. Provider is determined from the
    config files generated at environment creation time.
    """

    ADAPTER_TYPE = "opencode"
    SUPPORTED_PROVIDERS = [
        "anthropic", "openai", "openai_compatible",
        "google", "default",
    ]

    def __init__(self, config: SDKConfig):
        super().__init__(config)

        # Agent env service for plugin management (mirrors ClaudeCodeAdapter)
        self.agent_env_service = AgentEnvService(self.workspace_dir)

        self.prompt_generator = PromptGenerator(
            self.workspace_dir,
            supports_skills=self.SUPPORTS_SKILLS,
            active_plugins_for_mode=self.agent_env_service.get_active_plugins_for_mode,
        )

        # Server process — started lazily on first send_message_stream call
        self._server_process: Optional[asyncio.subprocess.Process] = None

        # Lock to prevent concurrent server starts
        self._start_lock = asyncio.Lock()

        # Current session ID — tracked across calls
        self._current_session_id: Optional[str] = None

        # Per-mode port and runtime dir are resolved on first use
        # (when mode is known from send_message_stream)
        self._mode: Optional[str] = None
        self._port: Optional[int] = None
        self._base_url: Optional[str] = None
        self._runtime_dir: Optional[Path] = None

        # Plugin capabilities OpenCode can't map (skills/agents/hooks), collected
        # at server start for non-blocking reporting at session start. List of
        # {plugin_name, marketplace_name, capability, message}.
        self._plugin_unsupported: list[dict] = []

        # Event transformer — translates raw OpenCode SSE events to SDKEvents
        self._event_transformer = OpenCodeEventTransformer(self.workspace_dir)

        # Strong references to fire-and-forget background tasks (e.g. the
        # /question/{id}/reject call fired on the interrupt/teardown path).
        # Prevents Python GC from collecting the task reference mid-flight and
        # raising "Task was destroyed but it is pending!" warnings.
        self._background_tasks: set[asyncio.Task] = set()

        # Set once when opencode answered 404 to /instance/dispose, so an older
        # build logs the gap once instead of on every message. Never reset —
        # not even by stop() — because the gap belongs to the installed binary,
        # not to the process: see _dispose_instance.
        self._dispose_unsupported = False

        # Pending interactive `question` tools, keyed by opencode session id.
        # Populated when a `question.asked` requestID is captured during a
        # stream; the NEXT message for that session is treated as the answer
        # and relayed via POST /question/{id}/reply instead of a fresh message
        # post.  This is the in-memory fast path; GET /question is the
        # authoritative, parameter-free source of truth (see
        # _resolve_pending_question).  Each value is
        # ``{"id": request_id, "questions": [...]}``.
        self._pending_questions: dict[str, dict] = {}

    def _resolve_mode(self, mode: str) -> None:
        """
        Resolve per-mode paths and port on first use.

        Called once per adapter instance — subsequent calls with the same
        mode are no-ops.  Different modes get different adapter instances
        via SDKManager caching.
        """
        if self._mode == mode:
            return
        self._mode = mode
        self._port = OPENCODE_MODE_PORTS.get(mode, 4096)
        self._base_url = f"http://127.0.0.1:{self._port}"
        self._runtime_dir = Path(OPENCODE_RUNTIME_DIR_TEMPLATE.format(mode=mode))

    # ------------------------------------------------------------------
    # Process management
    # ------------------------------------------------------------------

    async def _start_opencode_server(self) -> None:
        """
        Launch `opencode serve` as an asyncio subprocess.

        Each mode gets its own server process on a dedicated port with its
        own runtime directory.  Config files are symlinked from the read-only
        per-mode config dir (/app/core/.opencode/{mode}/) into the writable
        runtime dir (/tmp/.opencode_{mode}/).
        """
        logger.info(
            "Starting opencode serve for mode=%s on port %d...",
            self._mode, self._port,
        )

        # Ensure the runtime directory exists (writable, unlike OPENCODE_CONFIG_DIR
        # which is mounted read-only via the /app/core:ro volume).
        self._runtime_dir.mkdir(parents=True, exist_ok=True)

        # Symlink static config files from the read-only per-mode config dir
        # into the writable runtime dir so opencode finds everything in one place.
        # opencode.json is the exception: it is MATERIALIZED (a real merged file,
        # not a symlink) so we can fold in the active plugins' MCP servers, which
        # change dynamically (Phase 1 install) without a rebuild.
        mode_config_dir = OPENCODE_CONFIG_DIR / self._mode
        if mode_config_dir.is_dir():
            for config_file in mode_config_dir.iterdir():
                if not config_file.is_file():
                    continue
                if config_file.name == "opencode.json":
                    continue  # handled by _materialize_opencode_config below
                link = self._runtime_dir / config_file.name
                if not link.exists():
                    link.symlink_to(config_file)

        # Materialize opencode.json with plugin MCP servers merged in + copy
        # plugin command files into the runtime command dir. Plugin capabilities
        # OpenCode can't map are collected here for non-blocking reporting at
        # session start.
        self._plugin_unsupported = self._materialize_opencode_config(mode_config_dir)

        # Sessions are bound to /app/workspace as their project directory (via
        # the `directory` query param) so file tools operate in the workspace.
        # Consequences that this env handles:
        #   * opencode loads project config by walking up from the project dir
        #     (/app/workspace), NOT from cwd — so it would no longer find our
        #     per-mode opencode.json. OPENCODE_CONFIG pins it explicitly.
        #   * opencode spawns local MCP servers (the knowledge / agent_task
        #     bridges) with cwd = the project dir (/app/workspace), so they can
        #     no longer read session_context.json from cwd. We pass its absolute
        #     path so the bridges resolve it regardless of their cwd.
        # The system prompt is delivered via the config's `instructions` entry
        # (absolute AGENTS.md path), so cwd-based AGENTS.md discovery is not
        # needed either.
        env = {
            **os.environ,
            "OPENCODE_SKIP_UPDATE": "1",
            "OPENCODE_CONFIG": str(self._runtime_dir / "opencode.json"),
            "CINNA_SESSION_CONTEXT_PATH": str(self._runtime_dir / "session_context.json"),
        }

        # cwd stays at the runtime dir (where the adapter writes opencode.json,
        # AGENTS.md, and session_context.json); the workspace project binding is
        # applied per request via the `directory` query param.
        self._server_process = await asyncio.create_subprocess_exec(
            "opencode", "serve",
            "--port", str(self._port),
            "--hostname", "127.0.0.1",
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
            env=env,
            cwd=str(self._runtime_dir),
        )

        logger.info(
            "opencode serve started for mode=%s (pid=%d, port=%d)",
            self._mode, self._server_process.pid, self._port,
        )

        # Wait for the server to become healthy
        await self._wait_for_server_health()

    async def _wait_for_server_health(self) -> None:
        """Poll the server until it responds or the timeout is reached."""
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            # Can't check health without aiohttp — give a fixed delay
            await asyncio.sleep(3)
            return

        deadline = asyncio.get_running_loop().time() + OPENCODE_STARTUP_TIMEOUT
        last_error: Optional[Exception] = None

        while asyncio.get_running_loop().time() < deadline:
            # Check if process died already
            if self._server_process and self._server_process.returncode is not None:
                raise RuntimeError(
                    f"opencode serve exited prematurely with code "
                    f"{self._server_process.returncode}"
                )

            try:
                async with aiohttp.ClientSession() as session:
                    # Try /health first; fall back to /doc (always exists)
                    for path in ("/health", "/doc"):
                        try:
                            async with session.get(
                                f"{self._base_url}{path}",
                                timeout=aiohttp.ClientTimeout(total=2),
                            ) as resp:
                                if resp.status < 500:
                                    logger.info(
                                        "opencode serve is healthy (status=%d on %s)",
                                        resp.status, path,
                                    )
                                    return
                        except Exception:
                            pass
            except Exception as exc:
                last_error = exc

            await asyncio.sleep(1)

        raise RuntimeError(
            f"opencode serve did not become healthy within "
            f"{OPENCODE_STARTUP_TIMEOUT}s. Last error: {last_error}"
        )

    async def _ensure_server_running(self) -> bool:
        """
        Ensure the opencode server is running. Starts it if not running.

        Uses a lock to prevent multiple concurrent starts.

        Returns True when this call actually launched the server. Callers use
        that to skip work a fresh process has already done — a just-started
        server has read the current skills projection, so disposing its
        instance to force a rescan would be pure waste.
        """
        async with self._start_lock:
            # Check if process exists and is still alive
            process_alive = (
                self._server_process is not None
                and self._server_process.returncode is None
            )

            if process_alive:
                return False

            if self._server_process is not None:
                logger.warning(
                    "opencode serve process exited (code=%d), restarting...",
                    self._server_process.returncode,
                )
            # Clear stale session ID so the next request creates a fresh session
            self._current_session_id = None
            await self._start_opencode_server()
            return True

    async def stop(self) -> bool:
        """Terminate this mode's opencode server so it relaunches lazily.

        The server materializes its config once at start (plugin MCP servers,
        plugin ``skills`` paths, plugin slash commands), so a plugin change
        only takes effect after a relaunch. ``routes.install_plugins`` calls
        this via ``sdk_manager.stop_opencode_servers()``; the next message pays
        the startup cost once and gets the new plugin set.

        Returns True when a live process was actually stopped.
        """
        async with self._start_lock:
            process = self._server_process
            if process is None or process.returncode is not None:
                self._server_process = None
                return False

            logger.info(
                "Stopping opencode serve for mode=%s (pid=%d) after a plugin change",
                self._mode, process.pid,
            )
            try:
                process.terminate()
            except ProcessLookupError:
                self._server_process = None
                self._current_session_id = None
                return False

            try:
                await asyncio.wait_for(process.wait(), timeout=OPENCODE_STOP_TIMEOUT)
            except asyncio.TimeoutError:
                logger.warning(
                    "opencode serve (mode=%s) did not exit in %ds — killing it",
                    self._mode, OPENCODE_STOP_TIMEOUT,
                )
                try:
                    process.kill()
                    await process.wait()
                except ProcessLookupError:
                    pass

            self._server_process = None
            # The sessions belonged to the dead process; the next message must
            # create a fresh one rather than resume an id the new server never
            # heard of.
            self._current_session_id = None
            return True

    async def _dispose_instance(self) -> None:
        """POST /instance/dispose so OpenCode rebuilds its per-workspace state.

        Used after the skills projection changed: OpenCode memoizes the skill
        list per workspace instance, and disposing is the cheap way to make it
        rescan without the ~30s of a full server relaunch.

        Best-effort by design — a build without the endpoint answers 404, which
        is logged once per adapter instance and otherwise ignored. Once, not
        once per server: ``stop()`` replaces the process but not the adapter,
        and the missing endpoint is a property of the installed opencode
        binary, which a relaunch inside the same container cannot change — so
        re-arming the warning would only repeat what was already reported. The
        skills then become visible at the next server start, and
        ``/rebuild-env`` is the user-facing fix.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            return
        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    f"{self._base_url}/instance/dispose",
                    params={"directory": self.workspace_dir},
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    if resp.status == 404:
                        if not self._dispose_unsupported:
                            self._dispose_unsupported = True
                            logger.warning(
                                "opencode build has no POST /instance/dispose; "
                                "projected skills become visible at the next "
                                "server start (mode=%s)", self._mode,
                            )
                        return
                    if resp.status >= 400:
                        logger.warning(
                            "POST /instance/dispose failed (%d)", resp.status
                        )
                        return
            logger.info(
                "Disposed opencode instance for mode=%s after a skills change",
                self._mode,
            )
        except Exception as e:  # noqa: BLE001 — never break the message path
            logger.warning("Could not dispose opencode instance: %s", e)

    # ------------------------------------------------------------------
    # HTTP helpers
    # ------------------------------------------------------------------

    async def _create_session(self) -> str:
        """
        POST /session — create a new OpenCode session.

        Returns the session ID string.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            raise RuntimeError("aiohttp is required for OpenCodeAdapter but is not installed")

        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"{self._base_url}/session",
                # Bind the session to the agent workspace as its project root.
                # Without this, opencode uses the server's cwd (the runtime
                # config dir under /tmp) as the project, so file tools
                # (write/edit/apply_patch/bash) resolve relative paths to /tmp
                # instead of /app/workspace — making created files invisible to
                # the workspace, the /files browser, and message attachments.
                params={"directory": self.workspace_dir},
                json={},
                timeout=aiohttp.ClientTimeout(total=30),
            ) as resp:
                resp.raise_for_status()
                data = await resp.json()
                session_id = data.get("id") or data.get("sessionId") or data.get("session_id")
                if not session_id:
                    raise RuntimeError(f"POST /session returned no session id: {data}")
                logger.info("Created OpenCode session: %s", session_id)
                self._event_transformer.event_logger.log_send(
                    "create_session", {"session_id": session_id}
                )
                return session_id

    async def _post_message(self, session_id: str, message: str) -> None:
        """
        POST /session/:id/message — send a user message to the session.

        This triggers OpenCode to start processing; actual response comes
        through the SSE stream on GET /global/event.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            raise RuntimeError("aiohttp is required for OpenCodeAdapter but is not installed")

        body = {
            "role": "user",
            "parts": [{"type": "text", "text": message}],
        }

        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"{self._base_url}/session/{session_id}/message",
                # Keep the request scoped to the workspace project so message
                # processing and tool execution run in /app/workspace (matches
                # the directory the session was created with).
                params={"directory": self.workspace_dir},
                json=body,
                timeout=aiohttp.ClientTimeout(total=60),
            ) as resp:
                if resp.status >= 400:
                    text = await resp.text()
                    raise RuntimeError(
                        f"POST /session/{session_id}/message failed "
                        f"({resp.status}): {text}"
                    )
                logger.info("Message sent to OpenCode session %s", session_id)
                self._event_transformer.event_logger.log_send(
                    "post_message",
                    {"session_id": session_id, "message": message},
                )

    # ------------------------------------------------------------------
    # System prompt
    # ------------------------------------------------------------------

    async def _write_agents_md(self, system_prompt: str) -> None:
        """Write the system prompt to AGENTS.md in the runtime directory."""
        agents_md_path = self._runtime_dir / OPENCODE_AGENTS_MD_FILENAME
        self._runtime_dir.mkdir(parents=True, exist_ok=True)
        agents_md_path.write_text(system_prompt, encoding="utf-8")
        logger.info("Wrote AGENTS.md (%d chars)", len(system_prompt))
        self._event_transformer.event_logger.log_send(
            "write_agents_md", {"chars": len(system_prompt)}
        )

    async def _write_session_context(
        self,
        opencode_session_id: str,
        backend_session_id: Optional[str],
    ) -> None:
        """
        Write session context for MCP bridge servers.

        The MCP bridge servers (knowledge_server.py, task_server.py)
        read this file at tool-call time to obtain the
        current backend_session_id without needing to be passed it at startup.
        """
        context = {
            "opencode_session_id": opencode_session_id,
            "backend_session_id": backend_session_id or "",
        }
        context_path = self._runtime_dir / "session_context.json"
        self._runtime_dir.mkdir(parents=True, exist_ok=True)
        context_path.write_text(json.dumps(context, indent=2), encoding="utf-8")
        logger.debug(
            "Wrote session_context.json (opencode=%s, backend=%s)",
            opencode_session_id,
            backend_session_id,
        )

    def _materialize_opencode_config(self, mode_config_dir: Path) -> list[dict]:
        """Write a runtime opencode.json with active plugins' MCP servers merged in.

        The base config is the read-only per-mode ``opencode.json`` (model,
        provider, permissions, the knowledge/agent_task MCP bridges). We fold in
        each active plugin's *declared* MCP servers (from its ``.mcp.json`` /
        ``plugin.json`` — NOT a python3 wrapper of the plugin dir), register each
        plugin's ``skills/`` dir as an OpenCode skills path, and copy the
        plugin's ``commands/*.md`` into the runtime command dir so OpenCode loads
        them as slash commands.

        The agent's OWN skills are NOT listed here: they are projected into
        ``/root/.claude/skills`` before every message (see skills_projection),
        which OpenCode already reads, and listing them a second time would make
        every skill appear twice in the index.

        Returns the list of unsupported-capability reports (skills/agents/hooks)
        for non-blocking surfacing at session start.

        Writes are confined to the per-mode runtime dir (opencode.json + the
        ``command/`` subdir); plugin files are only read.
        """
        base_config_path = mode_config_dir / "opencode.json"
        try:
            if base_config_path.is_file():
                config = json.loads(base_config_path.read_text(encoding="utf-8"))
            else:
                logger.warning("No base opencode.json at %s", base_config_path)
                config = {}
        except (OSError, json.JSONDecodeError) as e:
            logger.error("Failed to read base opencode.json: %s", e)
            config = {}

        unsupported: list[dict] = []
        try:
            artifacts = self.agent_env_service.get_opencode_plugin_artifacts(self._mode)
        except Exception as e:  # noqa: BLE001
            logger.warning("Could not build plugin artifacts: %s", e)
            artifacts = {
                "mcp_servers": {},
                "command_files": [],
                "skill_dirs": [],
                "unsupported": [],
            }

        # 1) Merge plugin MCP servers into the config's mcp section. Plugin keys
        #    are namespaced (plugin_<mkt>_<plugin>_<server>) so they never clobber
        #    the knowledge / agent_task bridges.
        plugin_mcp = artifacts.get("mcp_servers") or {}
        if plugin_mcp:
            mcp_section = config.get("mcp")
            if not isinstance(mcp_section, dict):
                mcp_section = {}
            mcp_section.update(plugin_mcp)
            config["mcp"] = mcp_section

        # 1b) Merge credential-derived MCP-provider servers (RD-5). These are
        #     namespaced cinna_mcp_<credential_id> so they never collide with the
        #     knowledge / agent_task bridges or plugin_* servers.
        try:
            user_mcp = self.agent_env_service.get_user_mcp_servers_for_mode(
                self._mode, engine="opencode"
            )
        except Exception as e:  # noqa: BLE001
            logger.warning("Could not build user MCP servers: %s", e)
            user_mcp = {}
        if user_mcp:
            mcp_section = config.get("mcp")
            if not isinstance(mcp_section, dict):
                mcp_section = {}
            mcp_section.update(user_mcp)
            config["mcp"] = mcp_section
            logger.info(
                "OpenCode %s: merged %d MCP-provider server(s)",
                self._mode, len(user_mcp),
            )

        # 2) Register each active plugin's skills/ dir as an OpenCode skills
        #    path. Absolute, order-preserving and deduped; merged with anything
        #    the base config already declared so a hand-tuned template keeps its
        #    entries.
        plugin_skill_dirs = artifacts.get("skill_dirs") or []
        if plugin_skill_dirs:
            # Shape matters: opencode's config schema declares `skills` as an
            # OBJECT (`{"paths": [...], "urls": [...]}`) with
            # `additionalProperties: false` at both levels, and OPENCODE_CONFIG
            # pins this file — a wrong shape is not quietly ignored, it can stop
            # the server from starting. Merge into any `paths` the base template
            # already declared rather than replacing them.
            existing = config.get("skills")
            skills_section = dict(existing) if isinstance(existing, dict) else {}
            existing_paths = skills_section.get("paths")
            paths = [p for p in existing_paths if isinstance(p, str)] if isinstance(existing_paths, list) else []
            for skills_dir in plugin_skill_dirs:
                path_str = str(skills_dir)
                if path_str not in paths:
                    paths.append(path_str)
            skills_section["paths"] = paths
            config["skills"] = skills_section
            logger.info(
                "OpenCode %s: registered %d plugin skills path(s)",
                self._mode, len(plugin_skill_dirs),
            )

        # 3) Copy plugin command markdown into the runtime command dir.
        self._copy_plugin_commands(artifacts.get("command_files") or [])

        # 4) Collect unsupported capabilities for reporting.
        unsupported = artifacts.get("unsupported") or []

        # Write the merged config into the runtime dir (real file, replaces any
        # stale symlink/file from a prior start).
        runtime_config = self._runtime_dir / "opencode.json"
        try:
            if runtime_config.is_symlink() or runtime_config.exists():
                runtime_config.unlink()
            runtime_config.write_text(json.dumps(config, indent=2), encoding="utf-8")
            try:
                os.chmod(runtime_config, 0o600)
            except OSError:
                pass
        except OSError as e:
            logger.error("Failed to write runtime opencode.json: %s", e)

        if plugin_mcp or unsupported:
            logger.info(
                "OpenCode %s plugins: %d MCP server(s), %d command file(s), "
                "%d unsupported capability report(s)",
                self._mode, len(plugin_mcp),
                len(artifacts.get("command_files") or []), len(unsupported),
            )
        return unsupported

    def _active_plugin_mcp_keys(self) -> list[str]:
        """Return plugin MCP server keys merged into the runtime opencode.json.

        Reads the materialized config so the advertised tool names exactly match
        what OpenCode actually loaded. Plugin servers are keyed ``plugin_*`` to
        distinguish them from the knowledge / agent_task bridges.
        """
        if not self._runtime_dir:
            return []
        runtime_config = self._runtime_dir / "opencode.json"
        try:
            data = json.loads(runtime_config.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return []
        mcp = data.get("mcp")
        if not isinstance(mcp, dict):
            return []
        return [k for k in mcp if isinstance(k, str) and k.startswith("plugin_")]

    def _copy_plugin_commands(self, command_files: list) -> None:
        """Reconcile plugin command ``*.md`` files in the runtime ``command/`` dir.

        OpenCode loads slash commands from ``<config_dir>/command/``. This dir is
        entirely plugin-managed for the runtime, so it is CLEARED first (removing
        commands left over from a prior server generation — e.g. a plugin that was
        uninstalled then the server restarted within the same container) and then
        repopulated from the current active plugins. Writes are confined to the
        runtime command dir; a name collision keeps the first file and skips later
        ones (logged) so two plugins can't silently shadow each other.
        """
        command_dir = self._runtime_dir / "command"

        # Clear any stale plugin commands from a previous generation. Confined to
        # the runtime command dir; only *.md files are removed (defensive).
        if command_dir.exists():
            try:
                for stale in command_dir.glob("*.md"):
                    if stale.is_file():
                        stale.unlink()
            except OSError as e:
                logger.warning("Failed to clear stale command dir: %s", e)

        if not command_files:
            return

        try:
            command_dir.mkdir(parents=True, exist_ok=True)
        except OSError as e:
            logger.error("Failed to create command dir %s: %s", command_dir, e)
            return

        seen: set[str] = set()
        for src in command_files:
            try:
                src_path = Path(src)
                name = src_path.name
                if name in seen:
                    logger.warning(
                        "Skipping duplicate plugin command file: %s", name
                    )
                    continue
                dest = command_dir / name
                # Defence: confirm dest stays within the command dir.
                if dest.resolve().parent != command_dir.resolve():
                    logger.warning("Rejected unsafe command file name: %s", name)
                    continue
                shutil.copy2(src_path, dest)
                seen.add(name)
            except OSError as e:
                logger.warning("Failed to copy plugin command %s: %s", src, e)

    # ------------------------------------------------------------------
    # SSE event parsing
    # ------------------------------------------------------------------

    @staticmethod
    def _parse_sse_event(raw_data: str) -> Optional[dict]:
        """
        Parse a single SSE data payload into a dict.

        OpenCode wraps events in a ``{"payload": {...}}`` envelope.
        This method unwraps it so callers always see the inner event dict
        with ``type`` and ``properties`` at the top level.

        Returns None if parsing fails or the payload is not meaningful.
        """
        stripped = raw_data.strip()
        if not stripped or stripped == ":":
            return None
        try:
            parsed = json.loads(stripped)
            # Unwrap the payload envelope if present
            if "payload" in parsed and isinstance(parsed["payload"], dict):
                parsed = parsed["payload"]
            return parsed
        except json.JSONDecodeError:
            logger.debug("Skipping non-JSON SSE data: %s", stripped[:100])
            return None

    @staticmethod
    def _event_session_id(event_data: dict) -> Optional[str]:
        """
        Extract the opencode session ID an event belongs to, if any.

        ``GET /global/event`` is a serve-wide stream shared by every session on
        the mode's serve process, so each event must be matched against the
        session we are actually streaming for. Different event shapes nest the
        session ID differently:

            properties.sessionID          — most message / session events
            properties.part.sessionID     — message.part.updated / .delta
            properties.info.sessionID     — some session.* snapshots

        Server lifecycle events (server.connected, server.heartbeat,
        project.updated, …) carry NO session ID — those return None and must be
        treated as session-agnostic by the caller (they still drive the
        "first event triggers the POST" handshake in the SSE loop).
        """
        properties = event_data.get("properties")
        if not isinstance(properties, dict):
            return None

        sid = properties.get("sessionID")
        if sid:
            return sid

        part = properties.get("part")
        if isinstance(part, dict):
            sid = part.get("sessionID")
            if sid:
                return sid

        info = properties.get("info")
        if isinstance(info, dict):
            sid = info.get("sessionID")
            if sid:
                return sid

        return None

    # ------------------------------------------------------------------
    # Main send/stream
    # ------------------------------------------------------------------

    async def send_message_stream(
        self,
        message: str,
        session_id: Optional[str] = None,
        backend_session_id: Optional[str] = None,
        system_prompt: Optional[str] = None,
        mode: str = "conversation",
        session_state: Optional[dict] = None,
        skills_changed: bool = False,
    ) -> AsyncIterator[SDKEvent]:
        """
        Send a message via the OpenCode server and stream back SDKEvents.

        Flow:
        1. Resolve per-mode port/dir and ensure opencode serve is running.
        1b. Dispose the workspace instance when the skills projection changed,
            so OpenCode rebuilds its memoized skill list for this message.
        2. Create or resume session.
        3. Register session with active_session_manager for interrupt support.
        4. Write session_context.json for MCP bridge servers.
        5. Write AGENTS.md with the resolved system prompt.
        6. Emit tools_init event.
        7-8. Connect SSE stream, wait for first event, then POST message.
             SSE must be connected before posting so no events are missed.
        9. Unregister session on completion.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            yield SDKEvent(
                type=SDKEventType.ERROR,
                content="aiohttp is not installed in this environment. "
                        "OpenCode adapter requires aiohttp.",
                error_type="ImportError",
            )
            return

        try:
            # 1. Resolve per-mode port/dir and ensure server is running
            self._resolve_mode(mode)
            server_just_started = await self._ensure_server_running()

            # 1b. OpenCode memoizes the skill list per workspace instance, so a
            # skill projected since the last message is invisible until the
            # instance is disposed. Only on an actual change — disposing on
            # every message would throw away warm state for nothing — and never
            # right after a start, which already read the current projection.
            if skills_changed and not server_just_started:
                await self._dispose_instance()

            # 2. Create or resume session
            is_new_session = not session_id
            if is_new_session:
                self._event_transformer.event_logger.rotate()
                session_id = await self._create_session()
                self._current_session_id = session_id
                yield SDKEvent(
                    type=SDKEventType.SESSION_CREATED,
                    session_id=session_id,
                    content="",
                )
            else:
                self._current_session_id = session_id
                logger.info("Resuming OpenCode session: %s", session_id)
                yield SDKEvent(
                    type=SDKEventType.SESSION_RESUMED,
                    session_id=session_id,
                    content="",
                )

            # 3. Register with active_session_manager for interrupt support.
            # We pass None as the client since OpenCode interrupt uses HTTP DELETE,
            # not a client method. The manager tracks the session for interrupt flagging.
            await active_session_manager.register_session(session_id, None)

            # 4. Write session context so MCP bridge servers can find backend_session_id
            await self._write_session_context(session_id, backend_session_id)

            # 5. Resolve system prompt and write AGENTS.md
            if system_prompt:
                resolved_prompt = system_prompt
                logger.info("Using explicit system_prompt override")
            else:
                try:
                    generated = self.prompt_generator.generate_prompt(
                        mode, session_state=session_state
                    )
                    # Building mode may return a dict; extract 'append' field
                    if isinstance(generated, dict):
                        resolved_prompt = generated.get("append", "")
                    else:
                        resolved_prompt = generated or ""
                    logger.info(
                        "Generated %s mode prompt (%d chars)",
                        mode, len(resolved_prompt),
                    )
                except ValueError as exc:
                    await active_session_manager.unregister_session(session_id)
                    yield SDKEvent(
                        type=SDKEventType.ERROR,
                        content=str(exc),
                        error_type="ValueError",
                    )
                    return

            await self._write_agents_md(resolved_prompt)

            # 6. Build tools list including plugin MCP servers.
            # All tool names are normalized to unified lowercase convention.
            # OpenCode built-ins are already lowercase; MCP bridge tools use
            # the mcp__agent_task__* prefix matching Claude Code naming.
            # Plugin MCP servers were merged into the runtime opencode.json by
            # _materialize_opencode_config at server start; advertise each as a
            # wildcard mcp__<server> entry so the UI shows them as available.
            all_tools = list(OPENCODE_BUILTIN_TOOLS)
            mcp_tool_names = [
                "mcp__knowledge__query_integration_knowledge",
                "mcp__agent_task__add_comment",
                "mcp__agent_task__update_status",
                "mcp__agent_task__create_task",
                "mcp__agent_task__create_subtask",
                "mcp__agent_task__get_details",
                "mcp__agent_task__list_tasks",
            ]
            for key in self._active_plugin_mcp_keys():
                mcp_tool_names.append(f"mcp__{key}")
            all_tools.extend(mcp_tool_names)

            yield SDKEvent(
                type=SDKEventType.SYSTEM,
                subtype="tools_init",
                content="",
                data={"tools": all_tools},
            )

            # 6b. Report (non-blocking) any plugin capabilities OpenCode can't
            # map — skills/agents/hooks — as a SYSTEM event so the owner is told
            # rather than the capability being silently dropped (mirrors the
            # Phase 2 "report, don't drop" warning channel).
            if self._plugin_unsupported:
                summary = "; ".join(
                    u.get("message", "") for u in self._plugin_unsupported
                )
                yield SDKEvent(
                    type=SDKEventType.SYSTEM,
                    subtype="plugin_capability_warning",
                    content=(
                        "Some installed plugin capabilities are not supported "
                        f"under OpenCode and were skipped: {summary}"
                    ),
                    data={"unsupported": self._plugin_unsupported},
                )

            # 6c. Answer relay: if this session has an outstanding `question`
            #     tool, the incoming message IS the answer — relay it via
            #     POST /question/{id}/reply (resuming the suspended turn)
            #     instead of posting a fresh message (which would wedge,
            #     because opencode serializes turns per session and the
            #     prior turn never reached session.idle).  Detection is
            #     parameter-free (GET /question + in-memory fast path).
            #     A brand-new session can't have a pending question.
            reply_request_id: Optional[str] = None
            reply_answers: Optional[list] = None
            if not is_new_session:
                pending_q = await self._resolve_pending_question(session_id)
                if pending_q and pending_q.get("id"):
                    reply_request_id = pending_q["id"]
                    n_questions = len(pending_q.get("questions") or []) or 1
                    reply_answers = self._build_question_answers(
                        message, n_questions, session_state
                    )
                    logger.info(
                        "Session %s has pending question %s — relaying message "
                        "as answer (%d question(s))",
                        session_id, reply_request_id, n_questions,
                    )

            # 7-8. Connect SSE stream FIRST, then send the message once
            #      connected so we don't miss any events.
            # The POST is fired as a background task because it can block
            # until the LLM finishes responding.
            interrupt_initiated = False
            message_posted = False
            post_task: Optional[asyncio.Task] = None
            last_progress_time = asyncio.get_running_loop().time()
            # Questions captured from `question.asked` during THIS stream are
            # remembered in self._pending_questions so the next message relays
            # as a /reply.  We do NOT reject on stream close — the suspended
            # turn must stay alive for that reply (it survives the POST
            # disconnect; reject is reserved for interrupt/teardown).
            captured_question_payload: Optional[list] = None
            try:
                async with aiohttp.ClientSession() as http_session:
                    async with http_session.get(
                        f"{self._base_url}/global/event",
                        timeout=aiohttp.ClientTimeout(total=None, sock_read=300),
                    ) as sse_resp:
                        if sse_resp.status >= 400:
                            text = await sse_resp.text()
                            yield SDKEvent(
                                type=SDKEventType.ERROR,
                                content=f"GET /global/event failed ({sse_resp.status}): {text}",
                                error_type="OpenCodeError",
                                session_id=session_id,
                            )
                            return

                        # Reset event adapter state for this message exchange
                        self._event_transformer.reset()

                        buffer = ""
                        async for raw_bytes in sse_resp.content:
                            # Check for interrupt request between SSE chunks
                            if not interrupt_initiated and await active_session_manager.check_interrupt_requested(session_id):
                                logger.info(
                                    "Interrupt detected for OpenCode session %s",
                                    session_id,
                                )
                                interrupt_initiated = True
                                # Explicit teardown: release any abandoned
                                # question so it doesn't leak a parked turn.
                                self._cleanup_pending_question(session_id)
                                await self._delete_session(session_id)
                                yield SDKEvent(
                                    type=SDKEventType.INTERRUPTED,
                                    session_id=session_id,
                                    content="Message interrupted by user",
                                    metadata={"reason": "interrupt_requested"},
                                )
                                return

                            # Check progress timeout — if only heartbeats
                            # (or no events at all) for too long, the session
                            # is likely stuck (e.g. a tool hung on a directory).
                            now = asyncio.get_running_loop().time()
                            if message_posted and (now - last_progress_time) > OPENCODE_PROGRESS_TIMEOUT:
                                logger.error(
                                    "No progress for %ds on OpenCode session %s — aborting",
                                    OPENCODE_PROGRESS_TIMEOUT, session_id,
                                )
                                await self._delete_session(session_id)
                                yield SDKEvent(
                                    type=SDKEventType.ERROR,
                                    session_id=session_id,
                                    content=f"OpenCode session timed out — no progress for {OPENCODE_PROGRESS_TIMEOUT}s. "
                                            "A tool may have hung (e.g. reading a directory instead of a file).",
                                    error_type="ProgressTimeout",
                                )
                                return

                            line = raw_bytes.decode("utf-8", errors="replace")
                            buffer += line

                            # SSE events are separated by double newlines
                            while "\n\n" in buffer:
                                event_block, buffer = buffer.split("\n\n", 1)
                                for sse_line in event_block.split("\n"):
                                    sse_line = sse_line.strip()
                                    if sse_line.startswith("data:"):
                                        raw_data = sse_line[5:].strip()
                                        event_data = self._parse_sse_event(raw_data)
                                        if event_data is None:
                                            continue

                                        event_type = event_data.get("type", "")

                                        # Post message once SSE stream is alive.
                                        # We trigger on the first event (any type)
                                        # because on session resume opencode may
                                        # send project.updated instead of
                                        # server.connected as the first event.
                                        # Any event proves the socket is live, so
                                        # even a foreign-session event (the
                                        # /global/event stream is serve-wide) is a
                                        # valid "SSE alive" trigger here.
                                        # Fired as background task — POST can block
                                        # until the LLM finishes responding.
                                        if not message_posted:
                                            if reply_request_id is not None:
                                                logger.info(
                                                    "SSE alive (first event: %s), replying to "
                                                    "question %s on session %s",
                                                    event_type, reply_request_id, session_id,
                                                )
                                                post_task = asyncio.create_task(
                                                    self._reply_question(
                                                        reply_request_id, reply_answers
                                                    )
                                                )
                                                # Consumed — this question is being answered.
                                                self._pending_questions.pop(session_id, None)
                                            else:
                                                logger.info(
                                                    "SSE alive (first event: %s), posting message to session %s",
                                                    event_type, session_id,
                                                )
                                                post_task = asyncio.create_task(
                                                    self._post_message(session_id, message)
                                                )
                                            message_posted = True
                                            # Skip server lifecycle events
                                            if event_type in ("server.connected", "server.heartbeat"):
                                                continue

                                        # Skip heartbeats (high frequency, no value)
                                        if event_type == "server.heartbeat":
                                            continue

                                        # Demultiplex the serve-wide stream: GET
                                        # /global/event carries events for EVERY
                                        # session on this mode's serve process
                                        # (one serve per mode, shared by all
                                        # backend sessions). Drop any event that
                                        # belongs to a different opencode session —
                                        # e.g. an orphaned generation from a
                                        # since-deleted backend session — so it
                                        # neither bleeds its text into this stream
                                        # nor terminates it early via that
                                        # session's session.idle. Events with no
                                        # session ID (server/project lifecycle)
                                        # fall through unchanged. Crucially this
                                        # runs BEFORE the progress-timer reset and
                                        # translate() so foreign events do not
                                        # count as progress for this session.
                                        event_sid = self._event_session_id(event_data)
                                        if event_sid and event_sid != session_id:
                                            logger.debug(
                                                "Dropping foreign-session event %s "
                                                "(event session=%s, stream session=%s)",
                                                event_type, event_sid, session_id,
                                            )
                                            continue

                                        # Reset progress timer on meaningful events
                                        # (anything except heartbeats, which are
                                        # already filtered above, and foreign-session
                                        # events dropped just above)
                                        last_progress_time = now

                                        # Translate via event adapter
                                        sdk_events = self._event_transformer.translate(
                                            event_data, session_id
                                        )
                                        for sdk_event in sdk_events:
                                            yield sdk_event

                                            # Capture the question's structure
                                            # from the TOOL_USE event (carries
                                            # the questions array) so the
                                            # in-memory fast path knows how many
                                            # answer slots to pad on the next
                                            # turn.  Metadata key contract is
                                            # owned by the transformer.
                                            if (
                                                sdk_event.type == SDKEventType.TOOL_USE
                                                and (sdk_event.metadata or {}).get(
                                                    OPENCODE_QUESTION_REQUEST_ID_KEY
                                                )
                                            ):
                                                captured_question_payload = (
                                                    (sdk_event.metadata or {})
                                                    .get("tool_input", {})
                                                    .get("questions", [])
                                                )

                                            # Capture the question requestID from
                                            # the transformer's DONE metadata and
                                            # remember it as PENDING for this
                                            # session.  We do NOT reject: the
                                            # suspended turn stays alive so the
                                            # next message can answer it via
                                            # POST /question/{id}/reply.
                                            if sdk_event.type == SDKEventType.DONE:
                                                req_id = (sdk_event.metadata or {}).get(
                                                    OPENCODE_QUESTION_REQUEST_ID_KEY
                                                )
                                                if req_id:
                                                    self._pending_questions[session_id] = {
                                                        "id": req_id,
                                                        "questions": captured_question_payload or [],
                                                    }
                                                    logger.info(
                                                        "question.asked signalled for session %s "
                                                        "(requestID=%s) — turn kept alive; next "
                                                        "message will be relayed as the answer",
                                                        session_id, req_id,
                                                    )

                                            if sdk_event.type in (
                                                SDKEventType.DONE,
                                                SDKEventType.ERROR,
                                                SDKEventType.INTERRUPTED,
                                            ):
                                                return
            finally:
                # NOTE: do NOT reject a pending `question` here.  On a normal
                # question.asked close the suspended turn must stay alive so the
                # next message can answer it via /reply (the turn survives this
                # POST teardown — verified against opencode 1.14.x).  Reject is
                # reserved for the explicit interrupt path above, which calls
                # _cleanup_pending_question; the CancelledError handler below
                # tears the question down via _delete_session (DELETE settles
                # the suspended Deferred and pops the fast-path entry).

                # Ensure the POST task is awaited to catch errors
                if post_task is not None and not post_task.done():
                    post_task.cancel()
                    try:
                        await post_task
                    except (asyncio.CancelledError, Exception):
                        pass
                elif post_task is not None and post_task.done():
                    # Re-raise any exception from the POST
                    exc = post_task.exception() if not post_task.cancelled() else None
                    if exc:
                        logger.error("POST message failed: %s", exc)
                # 9. Always unregister session on exit
                await active_session_manager.unregister_session(session_id)

        except asyncio.CancelledError:
            logger.info(
                "OpenCode stream cancelled for session %s", session_id
            )
            if session_id:
                await active_session_manager.unregister_session(session_id)
                # Stop the in-flight opencode generation so it doesn't keep
                # running as an orphan after the backend stream is gone (e.g.
                # the user deleted the session while a slow model was still
                # answering). An orphan would otherwise bleed its events into
                # the next session via the serve-wide /global/event stream.
                # We can't await DELETE here: this is a cancelled context, so an
                # await would be re-cancelled immediately. Fire it on a
                # background task instead. The loop may be tearing down, so guard
                # against "no running loop" and let it be best-effort.
                try:
                    self._spawn_background(self._delete_session(session_id))
                except RuntimeError:
                    logger.debug(
                        "Could not schedule orphan delete for session %s "
                        "(event loop unavailable)", session_id,
                    )
            yield SDKEvent(
                type=SDKEventType.INTERRUPTED,
                session_id=session_id,
                content="Message interrupted by user",
                metadata={"reason": "cancelled"},
            )

        except asyncio.TimeoutError:
            logger.error(
                "OpenCode stream timed out for session %s", session_id
            )
            if session_id:
                await active_session_manager.unregister_session(session_id)
            yield SDKEvent(
                type=SDKEventType.ERROR,
                content="OpenCode response timed out",
                error_type="TimeoutError",
                session_id=session_id,
            )

        except Exception as exc:
            logger.error(
                "OpenCode adapter error for session %s: %s",
                session_id, exc, exc_info=True,
            )
            if session_id:
                await active_session_manager.unregister_session(session_id)
            yield SDKEvent(
                type=SDKEventType.ERROR,
                content=f"OpenCode error: {str(exc)}",
                error_type=type(exc).__name__,
                session_id=session_id,
            )

    # ------------------------------------------------------------------
    # Interrupt
    # ------------------------------------------------------------------

    async def _delete_session(self, session_id: str) -> bool:
        """
        Send DELETE /session/:id to cancel an active OpenCode session.

        This is used for interrupt support. OpenCode stops processing when the
        session is deleted. Returns True if the server accepted the request.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            return False

        # Deleting the opencode session settles any suspended `question`
        # Deferred (the fiber is interrupted), so forget our fast-path entry
        # for it — every delete path (interrupt, progress timeout, cancel)
        # funnels through here.
        self._pending_questions.pop(session_id, None)

        try:
            async with aiohttp.ClientSession() as session:
                async with session.delete(
                    f"{self._base_url}/session/{session_id}",
                    # Session is scoped to the workspace project; pass the
                    # directory so opencode resolves the right instance.
                    params={"directory": self.workspace_dir},
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    # 404 is acceptable — session may have already completed
                    success = resp.status in (200, 204, 404)
                    if success:
                        logger.info(
                            "Deleted OpenCode session %s (status=%d)",
                            session_id, resp.status,
                        )
                    else:
                        logger.warning(
                            "DELETE /session/%s returned %d",
                            session_id, resp.status,
                        )
                    return success
        except Exception as exc:
            logger.error(
                "Failed to delete OpenCode session %s: %s", session_id, exc
            )
            return False

    def _spawn_background(self, coro) -> asyncio.Task:
        """
        Launch a fire-and-forget coroutine while keeping a strong reference
        to the Task until it completes.

        `asyncio.create_task` returns a weakly-referenced Task; if the caller
        drops it, the event loop can garbage-collect the Task mid-flight
        and cancel the underlying coroutine.  Adding the task to a set (and
        removing it when done) guarantees the coroutine runs to completion.
        """
        task = asyncio.create_task(coro)
        self._background_tasks.add(task)
        task.add_done_callback(self._background_tasks.discard)
        return task

    # ------------------------------------------------------------------
    # Interactive `question` tool — detection, reply, cleanup
    # ------------------------------------------------------------------

    async def _list_pending_question(self, session_id: str) -> Optional[dict]:
        """
        GET /question — return the pending question for ``session_id``, if any.

        ``GET /question`` lists pending interactive questions across every
        session on this mode's serve process; there is no server-side
        per-session filter, so we filter client-side by ``sessionID``.

        IMPORTANT: opencode scopes pending questions to the project directory,
        so the ``directory`` query param is REQUIRED — without it the endpoint
        returns an empty list even when questions are pending (verified against
        opencode 1.14.x).

        Returns the matching ``{"id", "sessionID", "questions", ...}`` dict, or
        ``None`` when no question is pending for the session.  Raises on
        transport/parse errors so the caller can fall back to the in-memory
        fast path.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            return None

        async with aiohttp.ClientSession() as session:
            async with session.get(
                f"{self._base_url}/question",
                params={"directory": self.workspace_dir},
                timeout=aiohttp.ClientTimeout(total=10),
            ) as resp:
                resp.raise_for_status()
                pending = await resp.json()

        if not isinstance(pending, list):
            return None
        for entry in pending:
            if isinstance(entry, dict) and entry.get("sessionID") == session_id:
                return entry
        return None

    async def _resolve_pending_question(self, session_id: str) -> Optional[dict]:
        """
        Decide whether ``session_id`` has an outstanding question to answer.

        Detection is parameter-free and does not rely on any "reply-to"
        marker — the rule is simply *if the session has a pending question,
        the next message is the answer*.  Two sources combine:

        - ``GET /question`` (authoritative).  When it succeeds, its result is
          definitive: a hit means answer-this-question; an empty result means
          there is no pending question, so any stale in-memory entry is dropped
          and the message is posted normally (handles opencode restarts / gone
          sessions without wedging).
        - ``self._pending_questions`` (in-memory fast path).  Used only when the
          authoritative GET fails (transport error), so a transient blip can't
          turn an answer into a brand-new message post.

        Returns the resolved question dict (``{"id", "questions", ...}``) or
        ``None`` when the message should be posted as a normal turn.
        """
        try:
            server_pending = await self._list_pending_question(session_id)
        except Exception as exc:  # noqa: BLE001 — fall back to the fast path
            logger.warning(
                "GET /question failed for session %s (%s); using in-memory "
                "pending-question fast path", session_id, exc,
            )
            return self._pending_questions.get(session_id)

        if server_pending is None:
            # Authoritative: nothing pending — drop any stale fast-path entry.
            self._pending_questions.pop(session_id, None)
            return None
        return server_pending

    @staticmethod
    def _build_question_answers(
        message: str,
        n_questions: int,
        session_state: Optional[dict],
    ) -> list:
        """
        Map an incoming answer to opencode's ``reply`` payload shape.

        ``POST /question/{id}/reply`` expects ``{"answers": Answer[]}`` where
        ``Answer = string[]`` — one entry per question in order, with custom
        free-text labels allowed.

        Structured selections take precedence when the caller threads them
        through ``session_state`` (key ``question_answers``: a list of
        per-question string lists).  Otherwise we fall back to treating the
        message text as a single custom answer to the first question and pad
        the remaining slots with empty lists::

            answers = [[text]] + [[]] * (n_questions - 1)

        NOTE: no caller wires ``session_state["question_answers"]`` today — the
        frontend submits all selections as one ``\\n\\n``-joined text blob, so
        every reply currently goes through the free-text fallback.  The
        structured branch is intentional forward-looking scaffolding for when
        the frontend threads per-question selections through.  Empty padding
        slots are accepted by opencode's ``/reply`` (verified live against
        opencode 1.14.x: a 2-question reply ``[["Red"], []]`` resolves the turn
        to a clean ``session.idle``), so multi-question asks do not wedge.
        """
        n = max(n_questions, 1)

        structured = None
        if isinstance(session_state, dict):
            candidate = session_state.get("question_answers")
            if isinstance(candidate, list) and candidate and all(
                isinstance(a, list) for a in candidate
            ):
                structured = [
                    [str(item) for item in answer] for answer in candidate
                ]

        if structured is not None:
            # Normalise length to the number of questions (pad / truncate).
            if len(structured) < n:
                structured = structured + [[] for _ in range(n - len(structured))]
            return structured[:n]

        return [[message]] + [[] for _ in range(n - 1)]

    async def _reply_question(self, request_id: str, answers: list) -> bool:
        """
        POST /question/{requestID}/reply — answer a suspended `question` tool.

        Resolves opencode's pending Deferred WITH the answers, so the same
        suspended assistant turn resumes and runs to a clean ``session.idle``
        (unlike ``/reject``, which aborts the turn).  The resumed turn's events
        stream back over the serve-wide ``GET /global/event`` connection that
        the caller is already reading.

        ``directory`` is passed to match the project scope used everywhere else.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None or not request_id:
            return False

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    f"{self._base_url}/question/{request_id}/reply",
                    params={"directory": self.workspace_dir},
                    json={"answers": answers},
                    timeout=aiohttp.ClientTimeout(total=30),
                ) as resp:
                    success = resp.status in (200, 204)
                    if success:
                        logger.info(
                            "Replied to OpenCode question %s (status=%d)",
                            request_id, resp.status,
                        )
                    else:
                        text = await resp.text()
                        logger.warning(
                            "POST /question/%s/reply returned %d: %s",
                            request_id, resp.status, text[:200],
                        )
                    return success
        except Exception as exc:
            logger.error(
                "Failed to reply to OpenCode question %s: %s", request_id, exc
            )
            return False

    def _cleanup_pending_question(self, session_id: str) -> None:
        """
        Reject and forget any pending question for a session being torn down.

        Used ONLY on the explicit interrupt / cancel / session-delete paths so
        an abandoned question (user switched context, interrupted, etc.) does
        not leak a parked Deferred + suspended turn inside opencode.  Never
        called on the normal ``question.asked`` close — there the turn must
        stay alive for the next message's ``/reply``.
        """
        pending = self._pending_questions.pop(session_id, None)
        if not pending:
            return
        request_id = pending.get("id")
        if request_id:
            self._spawn_background(self._reject_question(request_id))

    async def _reject_question(self, request_id: str) -> bool:
        """
        POST /question/{requestID}/reject — abort a session suspended by the
        `question` tool.

        Reserved for the explicit interrupt / cancel / teardown path: it fails
        opencode's `Question.Service.ask()` Deferred with QuestionRejectedError,
        aborting the suspended turn.  This is NOT used on the normal answer
        flow — answers go through ``_reply_question`` so the turn completes
        cleanly.  Rejecting here just releases an abandoned question so it does
        not leak a parked turn.

        This endpoint is undocumented in the public OpenAPI spec but present
        since at least OpenCode 1.4.0; 1.4.4 officially exposes the schema.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None or not request_id:
            return False

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    f"{self._base_url}/question/{request_id}/reject",
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    # 404 is acceptable — the question may already have been
                    # answered/rejected via another client or the session
                    # may have been torn down.
                    success = resp.status in (200, 204, 404)
                    if success:
                        logger.info(
                            "Rejected OpenCode question %s (status=%d)",
                            request_id, resp.status,
                        )
                    else:
                        text = await resp.text()
                        logger.warning(
                            "POST /question/%s/reject returned %d: %s",
                            request_id, resp.status, text[:200],
                        )
                    return success
        except Exception as exc:
            logger.error(
                "Failed to reject OpenCode question %s: %s", request_id, exc
            )
            return False

    async def interrupt_session(self, session_id: str) -> bool:
        """
        Interrupt an active OpenCode session.

        This integrates with active_session_manager: we set the interrupt flag
        which is checked in the SSE streaming loop. The loop then calls
        _delete_session() to signal OpenCode to stop.

        Fallback: if the session is not registered (e.g., already finishing),
        we call _delete_session() directly.

        Returns True if the interrupt was accepted.
        """
        # Release any abandoned question so the interrupt doesn't leave a
        # parked Deferred + suspended turn behind in opencode.
        self._cleanup_pending_question(session_id)

        # Request interrupt via active_session_manager (checked in SSE loop)
        flagged = await active_session_manager.request_interrupt(session_id)
        if flagged:
            logger.info("Interrupt flagged for OpenCode session %s", session_id)
            return True

        # Fallback: direct HTTP delete if session is not registered
        logger.info(
            "Session %s not registered; attempting direct HTTP delete for interrupt",
            session_id,
        )
        return await self._delete_session(session_id)
