"""
OpenCode SDK Adapter

This adapter handles all opencode/* variants by running `opencode serve` as a
background subprocess and communicating with it over HTTP + SSE.

Supported providers (determined at runtime from the linked credential):
- opencode/anthropic: Anthropic Claude via OpenCode
- opencode/openai: OpenAI GPT models via OpenCode
- opencode/openai_compatible: Any OpenAI-compatible endpoint via OpenCode
- opencode/google: Google Gemini via OpenCode
- opencode (default): Falls back to Anthropic

Unlike Claude Code (which embeds the provider in the SDK ID), the OpenCode
adapter determines its provider from the credential type at environment creation
time. The credential's API key and endpoint are baked into the per-mode config
files at /app/core/.opencode/{mode}_config.json.

Architecture:
    opencode serve (subprocess, port 4096)
        <- POST /session              create session
        <- POST /session/:id/message  send message (session resumption)
        <- GET /global/event          SSE event stream
        <- PATCH /config              update model per mode
        <- DELETE /session/:id        interrupt session

Config files (generated by backend at environment creation / rebuild):
    /app/core/.opencode/building_config.json
    /app/core/.opencode/conversation_config.json
    /app/core/.opencode/AGENTS.md  (written per request from system prompt)

Session context (written before each message for MCP bridge servers):
    /app/core/.opencode/session_context.json
"""

import asyncio
import json
import logging
import os
from pathlib import Path
from typing import AsyncIterator, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Lazy import guard for aiohttp — avoids import errors when the adapter is
# imported but OpenCode is not in use.
# ---------------------------------------------------------------------------

def _import_aiohttp():
    try:
        import aiohttp
        return aiohttp
    except ImportError:
        return None


from .base import (
    BaseSDKAdapter,
    SDKEvent,
    SDKEventType,
    SDKConfig,
    AdapterRegistry,
)
from ..prompt_generator import PromptGenerator
from ..active_session_manager import active_session_manager
from ..agent_env_service import AgentEnvService


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

OPENCODE_CONFIG_DIR = Path("/app/core/.opencode")
OPENCODE_PORT = 4096
OPENCODE_BASE_URL = f"http://127.0.0.1:{OPENCODE_PORT}"

# How long to wait for opencode serve to become healthy on first start (seconds)
OPENCODE_STARTUP_TIMEOUT = 30

# Default model per provider per mode
_DEFAULT_MODELS = {
    "anthropic": {
        "building": "anthropic/claude-sonnet-4-5",
        "conversation": "anthropic/claude-haiku-4-5-20251001",
    },
    "openai": {
        "building": "openai/gpt-4o",
        "conversation": "openai/gpt-4o-mini",
    },
    "openai_compatible": {
        "building": "openai/gpt-4",
        "conversation": "openai/gpt-4",
    },
    "google": {
        "building": "google/gemini-2.5-pro",
        "conversation": "google/gemini-2.5-flash",
    },
    "default": {
        "building": "anthropic/claude-sonnet-4-5",
        "conversation": "anthropic/claude-haiku-4-5-20251001",
    },
}

# OpenCode built-in tools exposed to users
OPENCODE_BUILTIN_TOOLS = [
    "bash", "read", "write", "edit", "glob", "grep",
    "list", "patch", "webfetch", "websearch",
]


# ---------------------------------------------------------------------------
# Adapter
# ---------------------------------------------------------------------------

@AdapterRegistry.register
class OpenCodeAdapter(BaseSDKAdapter):
    """
    OpenCode adapter — wraps the `opencode serve` HTTP server.

    Supports all opencode/* variants. Provider is determined from the
    config files generated at environment creation time.
    """

    ADAPTER_TYPE = "opencode"
    SUPPORTED_PROVIDERS = [
        "anthropic", "openai", "openai_compatible",
        "google", "default",
    ]

    def __init__(self, config: SDKConfig):
        super().__init__(config)

        self.prompt_generator = PromptGenerator(self.workspace_dir)

        # Agent env service for plugin management (mirrors ClaudeCodeAdapter)
        self.agent_env_service = AgentEnvService(self.workspace_dir)

        # Server process — started lazily on first send_message_stream call
        self._server_process: Optional[asyncio.subprocess.Process] = None

        # Lock to prevent concurrent server starts
        self._start_lock = asyncio.Lock()

        # Current session ID — tracked across calls
        self._current_session_id: Optional[str] = None

    # ------------------------------------------------------------------
    # Process management
    # ------------------------------------------------------------------

    async def _start_opencode_server(self) -> None:
        """
        Launch `opencode serve` as an asyncio subprocess.

        The process is kept running for the lifetime of this adapter instance.
        Environment variables:
        - OPENCODE_SKIP_UPDATE=1 — suppress update nag
        - HOME set so opencode can find its config dir
        """
        logger.info("Starting opencode serve on port %d...", OPENCODE_PORT)

        env = {**os.environ, "OPENCODE_SKIP_UPDATE": "1"}

        # Ensure the config directory exists before starting
        OPENCODE_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

        # opencode reads config from the current directory or XDG dirs.
        # We point it at our config dir by using OPENCODE_CONFIG_DIR as cwd
        # so it finds opencode.json / AGENTS.md there.
        self._server_process = await asyncio.create_subprocess_exec(
            "opencode", "serve",
            "--port", str(OPENCODE_PORT),
            "--hostname", "127.0.0.1",
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
            env=env,
            cwd=str(OPENCODE_CONFIG_DIR),
        )

        logger.info("opencode serve started (pid=%d)", self._server_process.pid)

        # Wait for the server to become healthy
        await self._wait_for_server_health()

    async def _wait_for_server_health(self) -> None:
        """Poll the server until it responds or the timeout is reached."""
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            # Can't check health without aiohttp — give a fixed delay
            await asyncio.sleep(3)
            return

        deadline = asyncio.get_running_loop().time() + OPENCODE_STARTUP_TIMEOUT
        last_error: Optional[Exception] = None

        while asyncio.get_running_loop().time() < deadline:
            # Check if process died already
            if self._server_process and self._server_process.returncode is not None:
                raise RuntimeError(
                    f"opencode serve exited prematurely with code "
                    f"{self._server_process.returncode}"
                )

            try:
                async with aiohttp.ClientSession() as session:
                    # Try /health first; fall back to /doc (always exists)
                    for path in ("/health", "/doc"):
                        try:
                            async with session.get(
                                f"{OPENCODE_BASE_URL}{path}",
                                timeout=aiohttp.ClientTimeout(total=2),
                            ) as resp:
                                if resp.status < 500:
                                    logger.info(
                                        "opencode serve is healthy (status=%d on %s)",
                                        resp.status, path,
                                    )
                                    return
                        except Exception:
                            pass
            except Exception as exc:
                last_error = exc

            await asyncio.sleep(1)

        raise RuntimeError(
            f"opencode serve did not become healthy within "
            f"{OPENCODE_STARTUP_TIMEOUT}s. Last error: {last_error}"
        )

    async def _ensure_server_running(self) -> None:
        """
        Ensure the opencode server is running. Starts it if not running.

        Uses a lock to prevent multiple concurrent starts.
        """
        async with self._start_lock:
            # Check if process exists and is still alive
            process_alive = (
                self._server_process is not None
                and self._server_process.returncode is None
            )

            if not process_alive:
                if self._server_process is not None:
                    logger.warning(
                        "opencode serve process exited (code=%d), restarting...",
                        self._server_process.returncode,
                    )
                # Clear stale session ID so the next request creates a fresh session
                self._current_session_id = None
                await self._start_opencode_server()

    # ------------------------------------------------------------------
    # HTTP helpers
    # ------------------------------------------------------------------

    async def _create_session(self) -> str:
        """
        POST /session — create a new OpenCode session.

        Returns the session ID string.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            raise RuntimeError("aiohttp is required for OpenCodeAdapter but is not installed")

        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"{OPENCODE_BASE_URL}/session",
                json={},
                timeout=aiohttp.ClientTimeout(total=30),
            ) as resp:
                resp.raise_for_status()
                data = await resp.json()
                session_id = data.get("id") or data.get("sessionId") or data.get("session_id")
                if not session_id:
                    raise RuntimeError(f"POST /session returned no session id: {data}")
                logger.info("Created OpenCode session: %s", session_id)
                return session_id

    async def _patch_config(self, model: str) -> None:
        """
        PATCH /config — update the model for the current mode.

        Called before each send_message so the correct model is used.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            return

        try:
            async with aiohttp.ClientSession() as session:
                async with session.patch(
                    f"{OPENCODE_BASE_URL}/config",
                    json={"model": model},
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    if resp.status < 400:
                        logger.info("Patched OpenCode config: model=%s", model)
                    else:
                        logger.warning(
                            "PATCH /config returned %d for model=%s",
                            resp.status, model,
                        )
        except Exception as exc:
            logger.warning("Failed to PATCH /config (model=%s): %s", model, exc)

    async def _post_message(self, session_id: str, message: str) -> None:
        """
        POST /session/:id/message — send a user message to the session.

        This triggers OpenCode to start processing; actual response comes
        through the SSE stream on GET /global/event.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            raise RuntimeError("aiohttp is required for OpenCodeAdapter but is not installed")

        body = {
            "role": "user",
            "parts": [{"type": "text", "text": message}],
        }

        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"{OPENCODE_BASE_URL}/session/{session_id}/message",
                json=body,
                timeout=aiohttp.ClientTimeout(total=60),
            ) as resp:
                if resp.status >= 400:
                    text = await resp.text()
                    raise RuntimeError(
                        f"POST /session/{session_id}/message failed "
                        f"({resp.status}): {text}"
                    )
                logger.info("Message sent to OpenCode session %s", session_id)

    # ------------------------------------------------------------------
    # System prompt
    # ------------------------------------------------------------------

    async def _write_agents_md(self, system_prompt: str) -> None:
        """Write the system prompt to AGENTS.md in the config directory."""
        agents_md_path = OPENCODE_CONFIG_DIR / "AGENTS.md"
        OPENCODE_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        agents_md_path.write_text(system_prompt, encoding="utf-8")
        logger.info("Wrote AGENTS.md (%d chars)", len(system_prompt))

    async def _write_session_context(
        self,
        opencode_session_id: str,
        backend_session_id: Optional[str],
    ) -> None:
        """
        Write session context for MCP bridge servers.

        The MCP bridge servers (knowledge_server.py, task_server.py,
        collaboration_server.py) read this file at tool-call time to obtain the
        current backend_session_id without needing to be passed it at startup.
        """
        context = {
            "opencode_session_id": opencode_session_id,
            "backend_session_id": backend_session_id or "",
        }
        context_path = OPENCODE_CONFIG_DIR / "session_context.json"
        OPENCODE_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        context_path.write_text(json.dumps(context, indent=2), encoding="utf-8")
        logger.debug(
            "Wrote session_context.json (opencode=%s, backend=%s)",
            opencode_session_id,
            backend_session_id,
        )

    def _build_plugin_mcp_config(self, mode: str) -> dict:
        """
        Build MCP config entries for active agent plugins.

        Mirrors the plugin loading in ClaudeCodeAdapter but produces the dict
        format used by OpenCode's mcp config section.

        Returns:
            Dict mapping plugin MCP server names to their config entries.
        """
        plugin_mcp: dict = {}
        try:
            active_plugins = self.agent_env_service.get_active_plugins_for_mode(mode)
            for plugin in active_plugins:
                path = plugin.get("path", "")
                if not path:
                    continue
                plugin_name = plugin.get("name", Path(path).parent.name)
                # Use a namespaced key to avoid collisions with bridge servers
                key = f"plugin_{plugin_name}"
                plugin_mcp[key] = {
                    "type": "local",
                    "command": ["python3", path],
                    "enabled": True,
                }
            if plugin_mcp:
                logger.info(
                    "Built plugin MCP config for %s mode: %d plugin(s)",
                    mode,
                    len(plugin_mcp),
                )
        except Exception as exc:  # noqa: BLE001
            logger.warning("Could not build plugin MCP config: %s", exc)
        return plugin_mcp

    # ------------------------------------------------------------------
    # Config loading
    # ------------------------------------------------------------------

    def _load_config_for_mode(self, mode: str) -> Optional[dict]:
        """
        Load the per-mode config from /app/core/.opencode/{mode}_config.json.

        Returns the parsed dict or None if the file does not exist.
        """
        config_path = OPENCODE_CONFIG_DIR / f"{mode}_config.json"
        if config_path.exists():
            try:
                return json.loads(config_path.read_text(encoding="utf-8"))
            except Exception as exc:
                logger.error("Failed to load OpenCode config %s: %s", config_path, exc)
        return None

    def _get_model_for_mode(self, mode: str) -> Optional[str]:
        """
        Get the model string to use for this mode.

        Priority:
        1. model field in {mode}_config.json
        2. Default for provider + mode
        """
        config = self._load_config_for_mode(mode)
        if config:
            model = config.get("model")
            if model:
                return model

        provider = self.config.provider or "default"
        return _DEFAULT_MODELS.get(provider, _DEFAULT_MODELS["default"]).get(mode)

    # ------------------------------------------------------------------
    # SSE event parsing
    # ------------------------------------------------------------------

    def _parse_sse_event(self, raw_data: str) -> Optional[dict]:
        """
        Parse a single SSE data payload into a dict.

        Returns None if parsing fails or the payload is not meaningful.
        """
        stripped = raw_data.strip()
        if not stripped or stripped == ":":
            return None
        try:
            return json.loads(stripped)
        except json.JSONDecodeError:
            logger.debug("Skipping non-JSON SSE data: %s", stripped[:100])
            return None

    def _convert_event_to_sdk(
        self,
        event_data: dict,
        session_id: str,
    ) -> Optional[SDKEvent]:
        """
        Convert an OpenCode SSE event dict to our unified SDKEvent.

        OpenCode SSE events have varied schemas across versions. We use
        defensive attribute access throughout.

        Known event shapes:
        - {"type": "session.updated", "properties": {"session": {...}}}
          where session.messages[-1].parts contains text/tool parts
        - {"type": "...", "properties": {...}} for various events
        """
        event_type = event_data.get("type", "")
        properties = event_data.get("properties", {})

        # ----------------------------------------------------------------
        # Session completion
        # ----------------------------------------------------------------
        if (
            "completed" in event_type
            or event_type in ("session.finished", "message.completed")
            or properties.get("finishReason") in ("stop", "end_turn", "end")
        ):
            return SDKEvent(
                type=SDKEventType.DONE,
                session_id=session_id,
                content="",
                metadata={"opencode_event_type": event_type},
            )

        # ----------------------------------------------------------------
        # Error events
        # ----------------------------------------------------------------
        if "error" in event_type.lower() or properties.get("error"):
            error_msg = (
                properties.get("error")
                or properties.get("message")
                or event_type
            )
            if isinstance(error_msg, dict):
                error_msg = error_msg.get("message", str(error_msg))
            return SDKEvent(
                type=SDKEventType.ERROR,
                session_id=session_id,
                content=str(error_msg),
                error_type="OpenCodeError",
                metadata={"opencode_event_type": event_type},
            )

        # ----------------------------------------------------------------
        # Session update — contains message parts
        # ----------------------------------------------------------------
        if "session" in event_type or "message" in event_type:
            session_data = properties.get("session") or properties.get("message") or {}

            # Try to extract message parts from the last message
            messages = session_data.get("messages", [])
            if messages:
                last_message = messages[-1]
                parts = last_message.get("parts", [])
                role = last_message.get("role", "assistant")

                if role == "assistant":
                    text_parts: list[str] = []
                    for part in parts:
                        part_type = part.get("type", "")

                        # Text content — accumulate all text parts before returning
                        if part_type == "text":
                            text = part.get("text", "")
                            if text:
                                text_parts.append(text)

                        # Tool invocation
                        elif part_type == "tool-invocation":
                            tool_invocation = part.get("toolInvocation") or part
                            state = tool_invocation.get("state", "")
                            tool_name = tool_invocation.get("toolName", "")
                            tool_call_id = tool_invocation.get("toolCallId", "")

                            if state == "call":
                                args = tool_invocation.get("args", {})
                                try:
                                    args_str = json.dumps(args, indent=2)
                                    if len(args_str) > 200:
                                        args_str = args_str[:200] + "..."
                                except Exception:
                                    args_str = str(args)[:200]

                                return SDKEvent(
                                    type=SDKEventType.TOOL_USE,
                                    session_id=session_id,
                                    tool_name=tool_name,
                                    content=f"Using tool: {tool_name}\nInput: {args_str}",
                                    metadata={
                                        "tool_call_id": tool_call_id,
                                        "tool_input": args,
                                        "opencode_event_type": event_type,
                                    },
                                )

                            elif state == "result":
                                result = tool_invocation.get("result", "")
                                result_str = str(result)[:500] if result else ""
                                return SDKEvent(
                                    type=SDKEventType.TOOL_RESULT,
                                    session_id=session_id,
                                    content=result_str,
                                    metadata={
                                        "tool_call_id": tool_call_id,
                                        "tool_name": tool_name,
                                        "opencode_event_type": event_type,
                                    },
                                )

                    # Return a single event with all accumulated text parts joined
                    if text_parts:
                        return SDKEvent(
                            type=SDKEventType.ASSISTANT,
                            session_id=session_id,
                            content="".join(text_parts),
                            metadata={"opencode_event_type": event_type},
                        )

            # Also check for top-level text in properties
            text = properties.get("text") or properties.get("content")
            if text and isinstance(text, str):
                return SDKEvent(
                    type=SDKEventType.ASSISTANT,
                    session_id=session_id,
                    content=text,
                    metadata={"opencode_event_type": event_type},
                )

        # ----------------------------------------------------------------
        # Unrecognised events — log and skip
        # ----------------------------------------------------------------
        logger.debug("Unhandled OpenCode SSE event type: %s", event_type)
        return None

    # ------------------------------------------------------------------
    # Main send/stream
    # ------------------------------------------------------------------

    async def send_message_stream(
        self,
        message: str,
        session_id: Optional[str] = None,
        backend_session_id: Optional[str] = None,
        system_prompt: Optional[str] = None,
        mode: str = "conversation",
        session_state: Optional[dict] = None,
    ) -> AsyncIterator[SDKEvent]:
        """
        Send a message via the OpenCode server and stream back SDKEvents.

        Flow:
        1. Ensure opencode serve is running.
        2. Load per-mode config and PATCH /config with the target model.
        3. Create or resume session.
        4. Register session with active_session_manager for interrupt support.
        5. Write session_context.json for MCP bridge servers.
        6. Write AGENTS.md with the resolved system prompt.
        7. Emit tools_init event.
        8. POST the user message.
        9. Stream GET /global/event SSE, checking for interrupt on each event.
        10. Unregister session on completion.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            yield SDKEvent(
                type=SDKEventType.ERROR,
                content="aiohttp is not installed in this environment. "
                        "OpenCode adapter requires aiohttp.",
                error_type="ImportError",
            )
            return

        try:
            # 1. Ensure server is running
            await self._ensure_server_running()

            # 2. Dynamic model switching — PATCH /config before each message
            model = self._get_model_for_mode(mode)
            if model:
                await self._patch_config(model)

            # 3. Create or resume session
            is_new_session = not session_id
            if is_new_session:
                session_id = await self._create_session()
                self._current_session_id = session_id
                yield SDKEvent(
                    type=SDKEventType.SESSION_CREATED,
                    session_id=session_id,
                    content="",
                )
            else:
                self._current_session_id = session_id
                logger.info("Resuming OpenCode session: %s", session_id)
                yield SDKEvent(
                    type=SDKEventType.SESSION_RESUMED,
                    session_id=session_id,
                    content="",
                )

            # 4. Register with active_session_manager for interrupt support.
            # We pass None as the client since OpenCode interrupt uses HTTP DELETE,
            # not a client method. The manager tracks the session for interrupt flagging.
            await active_session_manager.register_session(session_id, None)

            # 5. Write session context so MCP bridge servers can find backend_session_id
            await self._write_session_context(session_id, backend_session_id)

            # 6. Resolve system prompt and write AGENTS.md
            if system_prompt:
                resolved_prompt = system_prompt
                logger.info("Using explicit system_prompt override")
            else:
                try:
                    generated = self.prompt_generator.generate_prompt(
                        mode, session_state=session_state
                    )
                    # Building mode may return a dict; extract 'append' field
                    if isinstance(generated, dict):
                        resolved_prompt = generated.get("append", "")
                    else:
                        resolved_prompt = generated or ""
                    logger.info(
                        "Generated %s mode prompt (%d chars)",
                        mode, len(resolved_prompt),
                    )
                except ValueError as exc:
                    await active_session_manager.unregister_session(session_id)
                    yield SDKEvent(
                        type=SDKEventType.ERROR,
                        content=str(exc),
                        error_type="ValueError",
                    )
                    return

            await self._write_agents_md(resolved_prompt)

            # 7. Build tools list including plugin MCP servers
            plugin_mcp = self._build_plugin_mcp_config(mode)
            all_tools = list(OPENCODE_BUILTIN_TOOLS)
            # Append MCP bridge tool names so the frontend can display them
            mcp_tool_names = [
                "mcp__knowledge__query_integration_knowledge",
                "mcp__task__create_agent_task",
                "mcp__task__update_session_state",
                "mcp__task__respond_to_task",
                "mcp__collaboration__create_collaboration",
                "mcp__collaboration__post_finding",
                "mcp__collaboration__get_collaboration_status",
            ]
            for key in plugin_mcp:
                mcp_tool_names.append(f"mcp__{key}")
            all_tools.extend(mcp_tool_names)

            yield SDKEvent(
                type=SDKEventType.SYSTEM,
                subtype="tools_init",
                content="",
                data={"tools": all_tools},
            )

            # 8. Send the user message
            await self._post_message(session_id, message)

            # 9. Stream SSE events, checking for interrupt on each event
            interrupt_initiated = False
            try:
                async with aiohttp.ClientSession() as http_session:
                    async with http_session.get(
                        f"{OPENCODE_BASE_URL}/global/event",
                        timeout=aiohttp.ClientTimeout(total=None, sock_read=300),
                    ) as sse_resp:
                        if sse_resp.status >= 400:
                            text = await sse_resp.text()
                            yield SDKEvent(
                                type=SDKEventType.ERROR,
                                content=f"GET /global/event failed ({sse_resp.status}): {text}",
                                error_type="OpenCodeError",
                                session_id=session_id,
                            )
                            return

                        buffer = ""
                        async for raw_bytes in sse_resp.content:
                            # Check for interrupt request between SSE chunks
                            if not interrupt_initiated and await active_session_manager.check_interrupt_requested(session_id):
                                logger.info(
                                    "Interrupt detected for OpenCode session %s",
                                    session_id,
                                )
                                interrupt_initiated = True
                                # Interrupt via HTTP DELETE on the session
                                await self._delete_session(session_id)
                                yield SDKEvent(
                                    type=SDKEventType.INTERRUPTED,
                                    session_id=session_id,
                                    content="Message interrupted by user",
                                    metadata={"reason": "interrupt_requested"},
                                )
                                return

                            line = raw_bytes.decode("utf-8", errors="replace")
                            buffer += line

                            # SSE events are separated by double newlines
                            while "\n\n" in buffer:
                                event_block, buffer = buffer.split("\n\n", 1)
                                for sse_line in event_block.split("\n"):
                                    sse_line = sse_line.strip()
                                    if sse_line.startswith("data:"):
                                        raw_data = sse_line[5:].strip()
                                        event_data = self._parse_sse_event(raw_data)
                                        if event_data is None:
                                            continue

                                        sdk_event = self._convert_event_to_sdk(
                                            event_data, session_id
                                        )
                                        if sdk_event is not None:
                                            yield sdk_event

                                            # Stop streaming after terminal events
                                            if sdk_event.type in (
                                                SDKEventType.DONE,
                                                SDKEventType.ERROR,
                                                SDKEventType.INTERRUPTED,
                                            ):
                                                return
            finally:
                # 10. Always unregister session on exit
                await active_session_manager.unregister_session(session_id)

        except asyncio.CancelledError:
            logger.info(
                "OpenCode stream cancelled for session %s", session_id
            )
            if session_id:
                await active_session_manager.unregister_session(session_id)
            yield SDKEvent(
                type=SDKEventType.INTERRUPTED,
                session_id=session_id,
                content="Message interrupted by user",
                metadata={"reason": "cancelled"},
            )

        except asyncio.TimeoutError:
            logger.error(
                "OpenCode stream timed out for session %s", session_id
            )
            if session_id:
                await active_session_manager.unregister_session(session_id)
            yield SDKEvent(
                type=SDKEventType.ERROR,
                content="OpenCode response timed out",
                error_type="TimeoutError",
                session_id=session_id,
            )

        except Exception as exc:
            logger.error(
                "OpenCode adapter error for session %s: %s",
                session_id, exc, exc_info=True,
            )
            if session_id:
                await active_session_manager.unregister_session(session_id)
            yield SDKEvent(
                type=SDKEventType.ERROR,
                content=f"OpenCode error: {str(exc)}",
                error_type=type(exc).__name__,
                session_id=session_id,
            )

    # ------------------------------------------------------------------
    # Interrupt
    # ------------------------------------------------------------------

    async def _delete_session(self, session_id: str) -> bool:
        """
        Send DELETE /session/:id to cancel an active OpenCode session.

        This is used for interrupt support. OpenCode stops processing when the
        session is deleted. Returns True if the server accepted the request.
        """
        aiohttp = _import_aiohttp()
        if aiohttp is None:
            return False

        try:
            async with aiohttp.ClientSession() as session:
                async with session.delete(
                    f"{OPENCODE_BASE_URL}/session/{session_id}",
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as resp:
                    # 404 is acceptable — session may have already completed
                    success = resp.status in (200, 204, 404)
                    if success:
                        logger.info(
                            "Deleted OpenCode session %s (status=%d)",
                            session_id, resp.status,
                        )
                    else:
                        logger.warning(
                            "DELETE /session/%s returned %d",
                            session_id, resp.status,
                        )
                    return success
        except Exception as exc:
            logger.error(
                "Failed to delete OpenCode session %s: %s", session_id, exc
            )
            return False

    async def interrupt_session(self, session_id: str) -> bool:
        """
        Interrupt an active OpenCode session.

        This integrates with active_session_manager: we set the interrupt flag
        which is checked in the SSE streaming loop. The loop then calls
        _delete_session() to signal OpenCode to stop.

        Fallback: if the session is not registered (e.g., already finishing),
        we call _delete_session() directly.

        Returns True if the interrupt was accepted.
        """
        # Request interrupt via active_session_manager (checked in SSE loop)
        flagged = await active_session_manager.request_interrupt(session_id)
        if flagged:
            logger.info("Interrupt flagged for OpenCode session %s", session_id)
            return True

        # Fallback: direct HTTP delete if session is not registered
        logger.info(
            "Session %s not registered; attempting direct HTTP delete for interrupt",
            session_id,
        )
        return await self._delete_session(session_id)
