# Re-export all models for backward compatibility
from sqlmodel import SQLModel
from .link_models import AgentCredentialLink
from .user import (
    User,
    UserCreate,
    UserRegister,
    UserUpdate,
    UserUpdateMe,
    UserPublic,
    UsersPublic,
    UpdatePassword,
    Message,
    NewPassword,
    Token,
    TokenPayload,
    SetPassword,
    OAuthConfig,
)
from .agent import (
    Agent,
    AgentCreate,
    AgentUpdate,
    AgentPublic,
    AgentsPublic,
    AgentWithCredentials,
    AgentCredentialLinkRequest,
    AgentCreateFlowRequest,
    AgentCreateFlowResponse,
    AgentSdkConfig,
    AllowedToolsUpdate,
    PendingToolsResponse,
    CloneMode,
    UpdateMode,
)
from .credential import (
    Credential,
    CredentialCreate,
    CredentialUpdate,
    CredentialPublic,
    CredentialsPublic,
    CredentialType,
    EmailImapData,
    OdooData,
    GmailOAuthData,
    ApiTokenData,
    CredentialWithData,
)
from .ai_credential import (
    AICredential,
    AICredentialCreate,
    AICredentialUpdate,
    AICredentialPublic,
    AICredentialsPublic,
    AICredentialType,
    AICredentialData,
)
from .ai_credential_share import (
    AICredentialShare,
    AICredentialShareBase,
    AICredentialSharePublic,
    AICredentialShareCreate,
    AICredentialSharesPublic,
    SharedAICredentialPublic,
    SharedAICredentialsPublic,
)
from .credential_share import (
    CredentialShare,
    CredentialShareBase,
    CredentialSharePublic,
    CredentialShareCreate,
    CredentialSharesPublic,
    SharedCredentialPublic,
    SharedCredentialsPublic,
)
from .agent_share import (
    AgentShare,
    AgentShareBase,
    AgentSharePublic,
    AgentShareCreate,
    AgentShareUpdate,
    AgentSharesPublic,
    PendingSharePublic,
    PendingSharesPublic,
    CredentialRequirement,
    AICredentialRequirement,
    ShareStatus,
    ShareMode,
    ShareSource,
)
from .clone_update_request import (
    CloneUpdateRequest,
    CloneUpdateRequestBase,
    CloneUpdateRequestPublic,
    CloneUpdateRequestsPublic,
    PushUpdateActionsRequest,
    UpdateRequestStatus,
)
from .item import (
    Item,
    ItemCreate,
    ItemUpdate,
    ItemPublic,
    ItemsPublic,
)
from .environment import (
    AgentEnvironment,
    AgentEnvironmentCreate,
    AgentEnvironmentUpdate,
    AgentEnvironmentPublic,
    AgentEnvironmentsPublic,
)
from .session import (
    Session,
    SessionCreate,
    SessionUpdate,
    SessionPublic,
    SessionPublicExtended,
    SessionsPublic,
    SessionsPublicExtended,
    SessionMessage,
    MessageCreate,
    MessagePublic,
    MessagesPublic,
)
from .activity import (
    Activity,
    ActivityCreate,
    ActivityUpdate,
    ActivityPublic,
    ActivityPublicExtended,
    ActivitiesPublic,
    ActivitiesPublicExtended,
    ActivityStats,
)
from .event import (
    EventType,
    EventBase,
    EventPublic,
    EventBroadcast,
    ConnectionInfo,
)
from .agent_schedule import (
    AgentSchedule,
    ScheduleRequest,
    ScheduleResponse,
    CreateScheduleRequest,
    UpdateScheduleRequest,
    AgentSchedulePublic,
    AgentSchedulesPublic,
)
from .agent_handover import (
    AgentHandoverConfig,
    HandoverConfigCreate,
    HandoverConfigUpdate,
    HandoverConfigPublic,
    HandoverConfigsPublic,
    GenerateHandoverPromptRequest,
    GenerateHandoverPromptResponse,
    CreateAgentTaskRequest,
    CreateAgentTaskResponse,
    ExecuteHandoverRequest,  # Deprecated, use CreateAgentTaskRequest
    ExecuteHandoverResponse,  # Deprecated, use CreateAgentTaskResponse
    UpdateSessionStateRequest,
    UpdateSessionStateResponse,
    RespondToTaskRequest,
)
from .user_workspace import (
    UserWorkspace,
    UserWorkspaceCreate,
    UserWorkspaceUpdate,
    UserWorkspacePublic,
    UserWorkspacesPublic,
)
from .ssh_key import (
    UserSSHKey,
    SSHKeyGenerate,
    SSHKeyImport,
    SSHKeyPublic,
    SSHKeysPublic,
    SSHKeyUpdate,
)
from .knowledge import (
    AIKnowledgeGitRepo,
    AIKnowledgeGitRepoCreate,
    AIKnowledgeGitRepoUpdate,
    AIKnowledgeGitRepoPublic,
    AIKnowledgeGitRepoWorkspace,
    UserEnabledDiscoverableSource,
    DiscoverableSourcePublic,
    KnowledgeArticle,
    KnowledgeArticlePublic,
    KnowledgeArticleDetail,
    KnowledgeArticleChunk,
    KnowledgeArticleChunkPublic,
    SourceStatus,
    WorkspaceAccessType,
    CheckAccessResponse,
    RefreshKnowledgeResponse,
    ArticleListItem,
    ArticleContent,
)
from .llm_plugin import (
    LLMPluginMarketplace,
    LLMPluginMarketplaceCreate,
    LLMPluginMarketplaceUpdate,
    LLMPluginMarketplacePublic,
    LLMPluginMarketplacesPublic,
    LLMPluginMarketplacePlugin,
    LLMPluginMarketplacePluginPublic,
    LLMPluginMarketplacePluginsPublic,
    AgentPluginLink,
    AgentPluginLinkCreate,
    AgentPluginLinkUpdate,
    AgentPluginLinkPublic,
    AgentPluginLinkWithPlugin,
    AgentPluginLinkWithUpdateInfo,
    AgentPluginLinksPublic,
    MarketplaceStatus,
    PluginSourceType,
)
from .agent_access_token import (
    AgentAccessToken,
    AgentAccessTokenCreate,
    AgentAccessTokenUpdate,
    AgentAccessTokenPublic,
    AgentAccessTokenCreated,
    AgentAccessTokensPublic,
    AccessTokenMode,
    AccessTokenScope,
    A2ATokenPayload,
)
from .agent_guest_share import (
    AgentGuestShare,
    AgentGuestShareBase,
    AgentGuestShareCreate,
    AgentGuestShareUpdate,
    AgentGuestSharePublic,
    AgentGuestShareCreated,
    AgentGuestSharesPublic,
    GuestShareGrant,
    GuestShareTokenPayload,
)
from .input_task import (
    InputTask,
    InputTaskCreate,
    InputTaskUpdate,
    InputTaskPublic,
    InputTaskPublicExtended,
    InputTasksPublic,
    InputTasksPublicExtended,
    InputTaskStatus,
    RefinementHistoryItem,
    RefineTaskRequest,
    RefineTaskResponse,
    ExecuteTaskRequest,
    ExecuteTaskResponse,
    SendAnswerRequest,
    SendAnswerResponse,
)
from .task_trigger import (
    TaskTrigger,
    TriggerType,
    TaskTriggerCreateSchedule,
    TaskTriggerCreateExactDate,
    TaskTriggerCreateWebhook,
    TaskTriggerUpdate,
    TaskTriggerPublic,
    TaskTriggerPublicWithToken,
    TaskTriggersPublic,
)
from .agent_email_integration import (
    AgentEmailIntegration,
    AgentEmailIntegrationCreate,
    AgentEmailIntegrationUpdate,
    AgentEmailIntegrationPublic,
    EmailAccessMode,
    EmailCloneShareMode,
    EmailProcessAs,
    ProcessEmailsResult,
)
from .mail_server_config import (
    MailServerConfig,
    MailServerConfigCreate,
    MailServerConfigUpdate,
    MailServerConfigPublic,
    MailServerConfigsPublic,
    MailServerType,
    EncryptionType,
)
from .email_message import (
    EmailMessage,
    EmailMessagePublic,
)
from .outgoing_email_queue import (
    OutgoingEmailQueue,
    OutgoingEmailQueuePublic,
    OutgoingEmailStatus,
)
from .mcp_connector import (
    MCPConnector,
    MCPConnectorCreate,
    MCPConnectorUpdate,
    MCPConnectorPublic,
    MCPConnectorsPublic,
)
from .mcp_oauth_client import (
    MCPOAuthClient,
    MCPOAuthClientPublic,
)
from .mcp_auth_code import (
    MCPAuthCode,
    MCPAuthRequest,
)
from .mcp_token import (
    MCPToken,
)
from .mcp_session_meta import (
    MCPSessionMeta,
    MCPSessionMetaPublic,
)
from .mcp_transport_session import (
    MCPTransportSession,
)
from .agent_webapp_share import (
    AgentWebappShare,
    AgentWebappShareBase,
    AgentWebappShareCreate,
    AgentWebappShareUpdate,
    AgentWebappSharePublic,
    AgentWebappShareCreated,
    AgentWebappSharesPublic,
    WebappShareTokenPayload,
)
from .agent_webapp_interface_config import (
    AgentWebappInterfaceConfig,
    AgentWebappInterfaceConfigBase,
    AgentWebappInterfaceConfigCreate,
    AgentWebappInterfaceConfigUpdate,
    AgentWebappInterfaceConfigPublic,
)
from .security_event import (
    SecurityEvent,
    SecurityEventCreate,
    SecurityEventPublic,
    SecurityEventsPublic,
    CREDENTIAL_READ_ATTEMPT,
    CREDENTIAL_BASH_ACCESS,
    OUTPUT_REDACTED,
    CREDENTIAL_WRITE_ATTEMPT,
)
from .user_dashboard import (
    UserDashboard,
    UserDashboardCreate,
    UserDashboardUpdate,
    UserDashboardPublic,
    UserDashboardBlock,
    UserDashboardBlockCreate,
    UserDashboardBlockUpdate,
    UserDashboardBlockPublic,
    BlockLayoutUpdate,
    UserDashboardBlockPromptAction,
    UserDashboardBlockPromptActionCreate,
    UserDashboardBlockPromptActionUpdate,
    UserDashboardBlockPromptActionPublic,
)
from .agent_collaboration import (
    AgentCollaboration,
    CollaborationSubtask,
    CollaborationSubtaskCreate,
    CollaborationSubtaskPublic,
    AgentCollaborationCreate,
    AgentCollaborationPublic,
    PostFindingRequest,
    PostFindingResponse,
    CreateCollaborationRequest,
    CreateCollaborationResponse,
)
from .agentic_team import (
    AgenticTeam,
    AgenticTeamCreate,
    AgenticTeamUpdate,
    AgenticTeamPublic,
    AgenticTeamsPublic,
    AgenticTeamNode,
    AgenticTeamNodeCreate,
    AgenticTeamNodeUpdate,
    AgenticTeamNodePublic,
    AgenticTeamNodesPublic,
    AgenticTeamNodePositionUpdate,
    AgenticTeamConnection,
    AgenticTeamConnectionCreate,
    AgenticTeamConnectionUpdate,
    AgenticTeamConnectionPublic,
    AgenticTeamConnectionsPublic,
    AgenticTeamChartPublic,
)

__all__ = [
    # Core
    "SQLModel",
    # Link models
    "AgentCredentialLink",
    # Users
    "User",
    "UserCreate",
    "UserRegister",
    "UserUpdate",
    "UserUpdateMe",
    "UserPublic",
    "UsersPublic",
    "UpdatePassword",
    "Message",
    "NewPassword",
    "Token",
    "TokenPayload",
    "SetPassword",
    "OAuthConfig",
    # Agents
    "Agent",
    "AgentCreate",
    "AgentUpdate",
    "AgentPublic",
    "AgentsPublic",
    "AgentCredentialLink",
    "AgentWithCredentials",
    "AgentCredentialLinkRequest",
    "AgentCreateFlowRequest",
    "AgentCreateFlowResponse",
    "AgentSdkConfig",
    "AllowedToolsUpdate",
    "PendingToolsResponse",
    "CloneMode",
    "UpdateMode",
    # Credentials
    "Credential",
    "CredentialCreate",
    "CredentialUpdate",
    "CredentialPublic",
    "CredentialsPublic",
    "CredentialType",
    "EmailImapData",
    "OdooData",
    "GmailOAuthData",
    "ApiTokenData",
    "CredentialWithData",
    # AI Credentials
    "AICredential",
    "AICredentialCreate",
    "AICredentialUpdate",
    "AICredentialPublic",
    "AICredentialsPublic",
    "AICredentialType",
    "AICredentialData",
    # AI Credential Shares
    "AICredentialShare",
    "AICredentialShareBase",
    "AICredentialSharePublic",
    "AICredentialShareCreate",
    "AICredentialSharesPublic",
    "SharedAICredentialPublic",
    "SharedAICredentialsPublic",
    # Credential Shares
    "CredentialShare",
    "CredentialShareBase",
    "CredentialSharePublic",
    "CredentialShareCreate",
    "CredentialSharesPublic",
    "SharedCredentialPublic",
    "SharedCredentialsPublic",
    # Agent Shares
    "AgentShare",
    "AgentShareBase",
    "AgentSharePublic",
    "AgentShareCreate",
    "AgentShareUpdate",
    "AgentSharesPublic",
    "PendingSharePublic",
    "PendingSharesPublic",
    "CredentialRequirement",
    "AICredentialRequirement",
    "ShareStatus",
    "ShareMode",
    "ShareSource",
    # Clone Update Requests
    "CloneUpdateRequest",
    "CloneUpdateRequestBase",
    "CloneUpdateRequestPublic",
    "CloneUpdateRequestsPublic",
    "PushUpdateActionsRequest",
    "UpdateRequestStatus",
    # Items
    "Item",
    "ItemCreate",
    "ItemUpdate",
    "ItemPublic",
    "ItemsPublic",
    # Environments
    "AgentEnvironment",
    "AgentEnvironmentCreate",
    "AgentEnvironmentUpdate",
    "AgentEnvironmentPublic",
    "AgentEnvironmentsPublic",
    # Sessions
    "Session",
    "SessionCreate",
    "SessionUpdate",
    "SessionPublic",
    "SessionPublicExtended",
    "SessionsPublic",
    "SessionsPublicExtended",
    # Messages
    "SessionMessage",
    "MessageCreate",
    "MessagePublic",
    "MessagesPublic",
    # Activities
    "Activity",
    "ActivityCreate",
    "ActivityUpdate",
    "ActivityPublic",
    "ActivityPublicExtended",
    "ActivitiesPublic",
    "ActivitiesPublicExtended",
    "ActivityStats",
    # Events
    "EventType",
    "EventBase",
    "EventPublic",
    "EventBroadcast",
    "ConnectionInfo",
    # Agent Schedules
    "AgentSchedule",
    "ScheduleRequest",
    "ScheduleResponse",
    "CreateScheduleRequest",
    "UpdateScheduleRequest",
    "AgentSchedulePublic",
    "AgentSchedulesPublic",
    # Agent Handovers / Task Creation
    "AgentHandoverConfig",
    "HandoverConfigCreate",
    "HandoverConfigUpdate",
    "HandoverConfigPublic",
    "HandoverConfigsPublic",
    "GenerateHandoverPromptRequest",
    "GenerateHandoverPromptResponse",
    "CreateAgentTaskRequest",
    "CreateAgentTaskResponse",
    "ExecuteHandoverRequest",  # Deprecated
    "ExecuteHandoverResponse",  # Deprecated
    "UpdateSessionStateRequest",
    "UpdateSessionStateResponse",
    "RespondToTaskRequest",
    # User Workspaces
    "UserWorkspace",
    "UserWorkspaceCreate",
    "UserWorkspaceUpdate",
    "UserWorkspacePublic",
    "UserWorkspacesPublic",
    # SSH Keys
    "UserSSHKey",
    "SSHKeyGenerate",
    "SSHKeyImport",
    "SSHKeyPublic",
    "SSHKeysPublic",
    "SSHKeyUpdate",
    # Knowledge Management
    "AIKnowledgeGitRepo",
    "AIKnowledgeGitRepoCreate",
    "AIKnowledgeGitRepoUpdate",
    "AIKnowledgeGitRepoPublic",
    "AIKnowledgeGitRepoWorkspace",
    "UserEnabledDiscoverableSource",
    "DiscoverableSourcePublic",
    "KnowledgeArticle",
    "KnowledgeArticlePublic",
    "KnowledgeArticleDetail",
    "KnowledgeArticleChunk",
    "KnowledgeArticleChunkPublic",
    "SourceStatus",
    "WorkspaceAccessType",
    "CheckAccessResponse",
    "RefreshKnowledgeResponse",
    "ArticleListItem",
    "ArticleContent",
    # LLM Plugin Management
    "LLMPluginMarketplace",
    "LLMPluginMarketplaceCreate",
    "LLMPluginMarketplaceUpdate",
    "LLMPluginMarketplacePublic",
    "LLMPluginMarketplacesPublic",
    "LLMPluginMarketplacePlugin",
    "LLMPluginMarketplacePluginPublic",
    "LLMPluginMarketplacePluginsPublic",
    "AgentPluginLink",
    "AgentPluginLinkCreate",
    "AgentPluginLinkUpdate",
    "AgentPluginLinkPublic",
    "AgentPluginLinkWithPlugin",
    "AgentPluginLinkWithUpdateInfo",
    "AgentPluginLinksPublic",
    "MarketplaceStatus",
    "PluginSourceType",
    # Agent Access Tokens
    "AgentAccessToken",
    "AgentAccessTokenCreate",
    "AgentAccessTokenUpdate",
    "AgentAccessTokenPublic",
    "AgentAccessTokenCreated",
    "AgentAccessTokensPublic",
    "AccessTokenMode",
    "AccessTokenScope",
    "A2ATokenPayload",
    # Agent Guest Shares
    "AgentGuestShare",
    "AgentGuestShareBase",
    "AgentGuestShareCreate",
    "AgentGuestShareUpdate",
    "AgentGuestSharePublic",
    "AgentGuestShareCreated",
    "AgentGuestSharesPublic",
    "GuestShareGrant",
    "GuestShareTokenPayload",
    # Input Tasks
    "InputTask",
    "InputTaskCreate",
    "InputTaskUpdate",
    "InputTaskPublic",
    "InputTaskPublicExtended",
    "InputTasksPublic",
    "InputTasksPublicExtended",
    "InputTaskStatus",
    "RefinementHistoryItem",
    "RefineTaskRequest",
    "RefineTaskResponse",
    "ExecuteTaskRequest",
    "ExecuteTaskResponse",
    "SendAnswerRequest",
    "SendAnswerResponse",
    # Task Triggers
    "TaskTrigger",
    "TriggerType",
    "TaskTriggerCreateSchedule",
    "TaskTriggerCreateExactDate",
    "TaskTriggerCreateWebhook",
    "TaskTriggerUpdate",
    "TaskTriggerPublic",
    "TaskTriggerPublicWithToken",
    "TaskTriggersPublic",
    # Agent Email Integration
    "AgentEmailIntegration",
    "AgentEmailIntegrationCreate",
    "AgentEmailIntegrationUpdate",
    "AgentEmailIntegrationPublic",
    "EmailAccessMode",
    "EmailCloneShareMode",
    "EmailProcessAs",
    "ProcessEmailsResult",
    # Mail Server Config
    "MailServerConfig",
    "MailServerConfigCreate",
    "MailServerConfigUpdate",
    "MailServerConfigPublic",
    "MailServerConfigsPublic",
    "MailServerType",
    "EncryptionType",
    # Email Messages
    "EmailMessage",
    "EmailMessagePublic",
    # Outgoing Email Queue
    "OutgoingEmailQueue",
    "OutgoingEmailQueuePublic",
    "OutgoingEmailStatus",
    # MCP Connectors
    "MCPConnector",
    "MCPConnectorCreate",
    "MCPConnectorUpdate",
    "MCPConnectorPublic",
    "MCPConnectorsPublic",
    # MCP OAuth
    "MCPOAuthClient",
    "MCPOAuthClientPublic",
    "MCPAuthCode",
    "MCPAuthRequest",
    "MCPToken",
    # MCP Session Meta
    "MCPSessionMeta",
    "MCPSessionMetaPublic",
    # MCP Transport Sessions
    "MCPTransportSession",
    # Agent Webapp Shares
    "AgentWebappShare",
    "AgentWebappShareBase",
    "AgentWebappShareCreate",
    "AgentWebappShareUpdate",
    "AgentWebappSharePublic",
    "AgentWebappShareCreated",
    "AgentWebappSharesPublic",
    "WebappShareTokenPayload",
    # Agent Webapp Interface Config
    "AgentWebappInterfaceConfig",
    "AgentWebappInterfaceConfigBase",
    "AgentWebappInterfaceConfigCreate",
    "AgentWebappInterfaceConfigUpdate",
    "AgentWebappInterfaceConfigPublic",
    # Security Events
    "SecurityEvent",
    "SecurityEventCreate",
    "SecurityEventPublic",
    "SecurityEventsPublic",
    "CREDENTIAL_READ_ATTEMPT",
    "CREDENTIAL_BASH_ACCESS",
    "OUTPUT_REDACTED",
    "CREDENTIAL_WRITE_ATTEMPT",
    # User Dashboards
    "UserDashboard",
    "UserDashboardCreate",
    "UserDashboardUpdate",
    "UserDashboardPublic",
    "UserDashboardBlock",
    "UserDashboardBlockCreate",
    "UserDashboardBlockUpdate",
    "UserDashboardBlockPublic",
    "BlockLayoutUpdate",
    "UserDashboardBlockPromptAction",
    "UserDashboardBlockPromptActionCreate",
    "UserDashboardBlockPromptActionUpdate",
    "UserDashboardBlockPromptActionPublic",
    # Agent Collaboration
    "AgentCollaboration",
    "CollaborationSubtask",
    "CollaborationSubtaskCreate",
    "CollaborationSubtaskPublic",
    "AgentCollaborationCreate",
    "AgentCollaborationPublic",
    "PostFindingRequest",
    "PostFindingResponse",
    "CreateCollaborationRequest",
    "CreateCollaborationResponse",
    # AgenticTeams
    "AgenticTeam",
    "AgenticTeamCreate",
    "AgenticTeamUpdate",
    "AgenticTeamPublic",
    "AgenticTeamsPublic",
    "AgenticTeamNode",
    "AgenticTeamNodeCreate",
    "AgenticTeamNodeUpdate",
    "AgenticTeamNodePublic",
    "AgenticTeamNodesPublic",
    "AgenticTeamNodePositionUpdate",
    "AgenticTeamConnection",
    "AgenticTeamConnectionCreate",
    "AgenticTeamConnectionUpdate",
    "AgenticTeamConnectionPublic",
    "AgenticTeamConnectionsPublic",
    "AgenticTeamChartPublic",
]
