"""add user dashboard tables

Revision ID: 0045add3641e
Revises: 5432134b1366
Create Date: 2026-03-13 07:40:01.559852

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0045add3641e'
down_revision = '5432134b1366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dashboard',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_dashboard_owner_id', 'user_dashboard', ['owner_id'], unique=False)
    op.create_index('ix_user_dashboard_owner_sort', 'user_dashboard', ['owner_id', 'sort_order'], unique=False)
    op.create_table('user_dashboard_block',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('view_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('show_border', sa.Boolean(), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('grid_w', sa.Integer(), nullable=False),
    sa.Column('grid_h', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['user_dashboard.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_dashboard_block_agent_id', 'user_dashboard_block', ['agent_id'], unique=False)
    op.create_index('ix_user_dashboard_block_dashboard_id', 'user_dashboard_block', ['dashboard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_dashboard_block_dashboard_id', table_name='user_dashboard_block')
    op.drop_index('ix_user_dashboard_block_agent_id', table_name='user_dashboard_block')
    op.drop_table('user_dashboard_block')
    op.drop_index('ix_user_dashboard_owner_sort', table_name='user_dashboard')
    op.drop_index('ix_user_dashboard_owner_id', table_name='user_dashboard')
    op.drop_table('user_dashboard')
    # ### end Alembic commands ###
