"""add knowledge management tables

Revision ID: 240176144d01
Revises: dcbfc8267939
Create Date: 2026-01-04 12:13:54.157090

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '240176144d01'
down_revision = 'dcbfc8267939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_knowledge_git_repo',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('git_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ssh_key_id', sa.Uuid(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'connected', 'error', 'disconnected', name='sourcestatus'), nullable=False),
    sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_commit_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workspace_access_type', sa.Enum('all', 'specific', name='workspaceaccesstype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ssh_key_id'], ['user_ssh_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_knowledge_git_repo_is_enabled'), 'ai_knowledge_git_repo', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_git_repo_name'), 'ai_knowledge_git_repo', ['name'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_git_repo_user_id'), 'ai_knowledge_git_repo', ['user_id'], unique=False)
    op.create_table('ai_knowledge_git_repo_workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('git_repo_id', sa.Uuid(), nullable=False),
    sa.Column('user_workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['git_repo_id'], ['ai_knowledge_git_repo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_workspace_id'], ['user_workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_git_repo_workspace_unique', 'ai_knowledge_git_repo_workspaces', ['git_repo_id', 'user_workspace_id'], unique=True)
    op.create_index(op.f('ix_ai_knowledge_git_repo_workspaces_git_repo_id'), 'ai_knowledge_git_repo_workspaces', ['git_repo_id'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_git_repo_workspaces_user_workspace_id'), 'ai_knowledge_git_repo_workspaces', ['user_workspace_id'], unique=False)
    op.create_table('knowledge_articles',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('commit_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('git_repo_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['git_repo_id'], ['ai_knowledge_git_repo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_article_repo_path_unique', 'knowledge_articles', ['git_repo_id', 'file_path'], unique=True)
    op.create_index('idx_articles_model', 'knowledge_articles', ['embedding_model'], unique=False)
    op.create_index('idx_articles_repo', 'knowledge_articles', ['git_repo_id'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_git_repo_id'), 'knowledge_articles', ['git_repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_articles_git_repo_id'), table_name='knowledge_articles')
    op.drop_index('idx_articles_repo', table_name='knowledge_articles')
    op.drop_index('idx_articles_model', table_name='knowledge_articles')
    op.drop_index('idx_article_repo_path_unique', table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index(op.f('ix_ai_knowledge_git_repo_workspaces_user_workspace_id'), table_name='ai_knowledge_git_repo_workspaces')
    op.drop_index(op.f('ix_ai_knowledge_git_repo_workspaces_git_repo_id'), table_name='ai_knowledge_git_repo_workspaces')
    op.drop_index('idx_git_repo_workspace_unique', table_name='ai_knowledge_git_repo_workspaces')
    op.drop_table('ai_knowledge_git_repo_workspaces')
    op.drop_index(op.f('ix_ai_knowledge_git_repo_user_id'), table_name='ai_knowledge_git_repo')
    op.drop_index(op.f('ix_ai_knowledge_git_repo_name'), table_name='ai_knowledge_git_repo')
    op.drop_index(op.f('ix_ai_knowledge_git_repo_is_enabled'), table_name='ai_knowledge_git_repo')
    op.drop_table('ai_knowledge_git_repo')
    # ### end Alembic commands ###
