"""Add expiry_notification_date to ai_credential

Revision ID: 67bd39e7e42c
Revises: u1p2q3r4s5t6
Create Date: 2026-01-25 14:20:02.829188

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '67bd39e7e42c'
down_revision = 'u1p2q3r4s5t6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_credential', sa.Column('expiry_notification_date', sa.DateTime(), nullable=True))
    op.alter_column('session', 'result_summary',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'result_summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('ai_credential', 'expiry_notification_date')
    # ### end Alembic commands ###
