"""remove unique constraint from input_task short_code

Revision ID: 86d07eb9fbf5
Revises: c802804db41c
Create Date: 2026-04-04 18:36:05.241283

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '86d07eb9fbf5'
down_revision = 'c802804db41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The unique index was never created (removed from earlier migration),
    # so just create the non-unique index directly.
    op.create_index(op.f('ix_input_task_short_code'), 'input_task', ['short_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_input_task_short_code'), table_name='input_task')
    # ### end Alembic commands ###
