"""add icon field to user workspace

Revision ID: 88ff71b370a1
Revises: 3a154fd039f5
Create Date: 2026-01-03 13:27:17.809517

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '88ff71b370a1'
down_revision = '3a154fd039f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_workspace', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_workspace', 'icon')
    # ### end Alembic commands ###
