"""add agent_sdk_config field

Revision ID: a1b8a2315572
Revises: 874dc8aa7c01
Create Date: 2026-01-12 11:55:17.857436

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a1b8a2315572'
down_revision = '874dc8aa7c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('agent_sdk_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'agent_sdk_config')
    # ### end Alembic commands ###
