"""add conversation_mode_ui field to agent

Revision ID: bb6811059aba
Revises: 3b9c8d4e5f6a
Create Date: 2026-01-08 17:03:49.372465

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bb6811059aba'
down_revision = '3b9c8d4e5f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('conversation_mode_ui', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='detailed'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'conversation_mode_ui')
    # ### end Alembic commands ###
