"""add app mcp server models

Revision ID: bccf5d92996f
Revises: 51014db83e57
Create Date: 2026-04-13 10:23:56.915144

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bccf5d92996f'
down_revision = '51014db83e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_mcp_oauth_client',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_secret_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=True),
    sa.Column('grant_types', sa.JSON(), nullable=True),
    sa.Column('response_types', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_mcp_oauth_client_client_id'), 'app_mcp_oauth_client', ['client_id'], unique=True)
    op.create_table('app_agent_route',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('session_mode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('trigger_prompt', sa.Text(), nullable=False),
    sa.Column('message_patterns', sa.Text(), nullable=True),
    sa.Column('channel_app_mcp', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_agent_route_agent_id'), 'app_agent_route', ['agent_id'], unique=False)
    op.create_index(op.f('ix_app_agent_route_created_by'), 'app_agent_route', ['created_by'], unique=False)
    op.create_table('app_mcp_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_mcp_token_client_id'), 'app_mcp_token', ['client_id'], unique=False)
    op.create_index(op.f('ix_app_mcp_token_token_hash'), 'app_mcp_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_app_mcp_token_user_id'), 'app_mcp_token', ['user_id'], unique=False)
    op.create_table('user_app_agent_route',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('session_mode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('trigger_prompt', sa.Text(), nullable=False),
    sa.Column('message_patterns', sa.Text(), nullable=True),
    sa.Column('channel_app_mcp', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agent_id', name='uq_user_app_agent_route')
    )
    op.create_index(op.f('ix_user_app_agent_route_user_id'), 'user_app_agent_route', ['user_id'], unique=False)
    op.create_table('app_agent_route_assignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['app_agent_route.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'user_id', name='uq_app_agent_route_assignment')
    )
    op.create_index(op.f('ix_app_agent_route_assignment_user_id'), 'app_agent_route_assignment', ['user_id'], unique=False)
    op.alter_column('cli_setup_token', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('cli_setup_token', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_cli_setup_token_owner_agent'), table_name='cli_setup_token')
    op.alter_column('cli_token', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('cli_token', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('cli_token', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_cli_token_owner_agent'), table_name='cli_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cli_token_owner_agent'), 'cli_token', ['owner_id', 'agent_id'], unique=False)
    op.alter_column('cli_token', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('cli_token', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('cli_token', 'last_used_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_cli_setup_token_owner_agent'), 'cli_setup_token', ['owner_id', 'agent_id'], unique=False)
    op.alter_column('cli_setup_token', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('cli_setup_token', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_app_agent_route_assignment_user_id'), table_name='app_agent_route_assignment')
    op.drop_table('app_agent_route_assignment')
    op.drop_index(op.f('ix_user_app_agent_route_user_id'), table_name='user_app_agent_route')
    op.drop_table('user_app_agent_route')
    op.drop_index(op.f('ix_app_mcp_token_user_id'), table_name='app_mcp_token')
    op.drop_index(op.f('ix_app_mcp_token_token_hash'), table_name='app_mcp_token')
    op.drop_index(op.f('ix_app_mcp_token_client_id'), table_name='app_mcp_token')
    op.drop_table('app_mcp_token')
    op.drop_index(op.f('ix_app_agent_route_created_by'), table_name='app_agent_route')
    op.drop_index(op.f('ix_app_agent_route_agent_id'), table_name='app_agent_route')
    op.drop_table('app_agent_route')
    op.drop_index(op.f('ix_app_mcp_oauth_client_client_id'), table_name='app_mcp_oauth_client')
    op.drop_table('app_mcp_oauth_client')
    # ### end Alembic commands ###
