"""Add tool_questions_status and answers_to_message_id to messages

Revision ID: bfbae71690bb
Revises: 57b4e9d8707e
Create Date: 2025-12-27 14:20:51.775518

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bfbae71690bb'
down_revision = '57b4e9d8707e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('tool_questions_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('message', sa.Column('answers_to_message_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'message', 'message', ['answers_to_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'answers_to_message_id')
    op.drop_column('message', 'tool_questions_status')
    # ### end Alembic commands ###
