"""agent-sdk-to-sessions

Revision ID: cc18aee3c7c4
Revises: f53a3e7bd2c1
Create Date: 2025-12-26 09:13:48.903566

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cc18aee3c7c4'
down_revision = 'f53a3e7bd2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('agent_sdk', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'agent_sdk')
    # ### end Alembic commands ###
