"""add mcp integration tables

Revision ID: dc259404533e
Revises: w3r4s5t6u7v8
Create Date: 2026-02-25 21:11:42.713510

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dc259404533e'
down_revision = 'w3r4s5t6u7v8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_connector',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allowed_emails', sa.JSON(), nullable=True),
    sa.Column('max_clients', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_auth_code',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=False),
    sa.Column('redirect_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_challenge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['mcp_connector.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_mcp_auth_code_client_id'), 'mcp_auth_code', ['client_id'], unique=False)
    op.create_table('mcp_auth_request',
    sa.Column('nonce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('redirect_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_challenge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_challenge_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['mcp_connector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_table('mcp_oauth_client',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_secret_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=True),
    sa.Column('grant_types', sa.JSON(), nullable=True),
    sa.Column('response_types', sa.JSON(), nullable=True),
    sa.Column('connector_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['mcp_connector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_oauth_client_client_id'), 'mcp_oauth_client', ['client_id'], unique=True)
    op.create_table('mcp_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['mcp_connector.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_token_client_id'), 'mcp_token', ['client_id'], unique=False)
    op.create_index(op.f('ix_mcp_token_connector_id'), 'mcp_token', ['connector_id'], unique=False)
    op.create_index(op.f('ix_mcp_token_token'), 'mcp_token', ['token'], unique=True)
    op.add_column('session', sa.Column('mcp_connector_id', sa.Uuid(), nullable=True))
    op.add_column('session', sa.Column('mcp_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'session', ['mcp_session_id'])
    op.create_foreign_key(None, 'session', 'mcp_connector', ['mcp_connector_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_constraint(None, 'session', type_='unique')
    op.drop_column('session', 'mcp_session_id')
    op.drop_column('session', 'mcp_connector_id')
    op.drop_index(op.f('ix_mcp_token_token'), table_name='mcp_token')
    op.drop_index(op.f('ix_mcp_token_connector_id'), table_name='mcp_token')
    op.drop_index(op.f('ix_mcp_token_client_id'), table_name='mcp_token')
    op.drop_table('mcp_token')
    op.drop_index(op.f('ix_mcp_oauth_client_client_id'), table_name='mcp_oauth_client')
    op.drop_table('mcp_oauth_client')
    op.drop_table('mcp_auth_request')
    op.drop_index(op.f('ix_mcp_auth_code_client_id'), table_name='mcp_auth_code')
    op.drop_table('mcp_auth_code')
    op.drop_table('mcp_connector')
    # ### end Alembic commands ###
