"""add status_message field to agent_environment

Revision ID: f53a3e7bd2c1
Revises: 998040e1ade4
Create Date: 2025-12-24 17:52:07.459389

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f53a3e7bd2c1'
down_revision = '998040e1ade4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_environment', sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_environment', 'status_message')
    # ### end Alembic commands ###
