/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as WebappWebappTokenRouteImport } from './routes/webapp/$webappToken'
import { Route as OauthMcpConsentRouteImport } from './routes/oauth/mcp-consent'
import { Route as GuestFileViewerRouteImport } from './routes/guest/file-viewer'
import { Route as GuestGuestShareTokenRouteImport } from './routes/guest/$guestShareToken'
import { Route as DashboardFullscreenDashboardIdRouteImport } from './routes/dashboard-fullscreen/$dashboardId'
import { Route as LayoutTasksRouteImport } from './routes/_layout/tasks'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSessionsRouteImport } from './routes/_layout/sessions'
import { Route as LayoutKnowledgeSourcesRouteImport } from './routes/_layout/knowledge-sources'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutCredentialsRouteImport } from './routes/_layout/credentials'
import { Route as LayoutAgentsRouteImport } from './routes/_layout/agents'
import { Route as LayoutActivitiesRouteImport } from './routes/_layout/activities'
import { Route as LayoutSessionsIndexRouteImport } from './routes/_layout/sessions.index'
import { Route as LayoutDashboardsIndexRouteImport } from './routes/_layout/dashboards.index'
import { Route as CredentialsOauthCallbackRouteImport } from './routes/credentials/oauth/callback'
import { Route as LayoutTaskTaskIdRouteImport } from './routes/_layout/task/$taskId'
import { Route as LayoutSessionSessionIdRouteImport } from './routes/_layout/session/$sessionId'
import { Route as LayoutKnowledgeSourceSourceIdRouteImport } from './routes/_layout/knowledge-source/$sourceId'
import { Route as LayoutDashboardsDashboardIdRouteImport } from './routes/_layout/dashboards.$dashboardId'
import { Route as LayoutCredentialCredentialIdRouteImport } from './routes/_layout/credential/$credentialId'
import { Route as LayoutAgentCreatingRouteImport } from './routes/_layout/agent/creating'
import { Route as LayoutAgentAgentIdRouteImport } from './routes/_layout/agent/$agentId'
import { Route as LayoutAdminUsersRouteImport } from './routes/_layout/admin/users'
import { Route as LayoutAdminMarketplacesRouteImport } from './routes/_layout/admin/marketplaces'
import { Route as LayoutSessionsAgentAgentIdRouteImport } from './routes/_layout/sessions.agent.$agentId'
import { Route as LayoutEnvironmentEnvIdFileRouteImport } from './routes/_layout/environment/$envId/file'
import { Route as LayoutEnvironmentEnvIdDatabaseRouteImport } from './routes/_layout/environment/$envId/database'
import { Route as LayoutAgentAgentIdConversationsRouteImport } from './routes/_layout/agent/$agentId/conversations'
import { Route as LayoutAdminMarketplaceMarketplaceIdRouteImport } from './routes/_layout/admin/marketplace/$marketplaceId'
import { Route as LayoutAdminMarketplacePluginPluginIdRouteImport } from './routes/_layout/admin/marketplace/plugin/$pluginId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const WebappWebappTokenRoute = WebappWebappTokenRouteImport.update({
  id: '/webapp/$webappToken',
  path: '/webapp/$webappToken',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthMcpConsentRoute = OauthMcpConsentRouteImport.update({
  id: '/oauth/mcp-consent',
  path: '/oauth/mcp-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestFileViewerRoute = GuestFileViewerRouteImport.update({
  id: '/guest/file-viewer',
  path: '/guest/file-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestGuestShareTokenRoute = GuestGuestShareTokenRouteImport.update({
  id: '/guest/$guestShareToken',
  path: '/guest/$guestShareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFullscreenDashboardIdRoute =
  DashboardFullscreenDashboardIdRouteImport.update({
    id: '/dashboard-fullscreen/$dashboardId',
    path: '/dashboard-fullscreen/$dashboardId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutTasksRoute = LayoutTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionsRoute = LayoutSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeSourcesRoute = LayoutKnowledgeSourcesRouteImport.update({
  id: '/knowledge-sources',
  path: '/knowledge-sources',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCredentialsRoute = LayoutCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsRoute = LayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutActivitiesRoute = LayoutActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionsIndexRoute = LayoutSessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutSessionsRoute,
} as any)
const LayoutDashboardsIndexRoute = LayoutDashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => LayoutRoute,
} as any)
const CredentialsOauthCallbackRoute =
  CredentialsOauthCallbackRouteImport.update({
    id: '/credentials/oauth/callback',
    path: '/credentials/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutTaskTaskIdRoute = LayoutTaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionSessionIdRoute = LayoutSessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutKnowledgeSourceSourceIdRoute =
  LayoutKnowledgeSourceSourceIdRouteImport.update({
    id: '/knowledge-source/$sourceId',
    path: '/knowledge-source/$sourceId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDashboardsDashboardIdRoute =
  LayoutDashboardsDashboardIdRouteImport.update({
    id: '/dashboards/$dashboardId',
    path: '/dashboards/$dashboardId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCredentialCredentialIdRoute =
  LayoutCredentialCredentialIdRouteImport.update({
    id: '/credential/$credentialId',
    path: '/credential/$credentialId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAgentCreatingRoute = LayoutAgentCreatingRouteImport.update({
  id: '/agent/creating',
  path: '/agent/creating',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentAgentIdRoute = LayoutAgentAgentIdRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminUsersRoute = LayoutAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminMarketplacesRoute = LayoutAdminMarketplacesRouteImport.update({
  id: '/admin/marketplaces',
  path: '/admin/marketplaces',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionsAgentAgentIdRoute =
  LayoutSessionsAgentAgentIdRouteImport.update({
    id: '/agent/$agentId',
    path: '/agent/$agentId',
    getParentRoute: () => LayoutSessionsRoute,
  } as any)
const LayoutEnvironmentEnvIdFileRoute =
  LayoutEnvironmentEnvIdFileRouteImport.update({
    id: '/environment/$envId/file',
    path: '/environment/$envId/file',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEnvironmentEnvIdDatabaseRoute =
  LayoutEnvironmentEnvIdDatabaseRouteImport.update({
    id: '/environment/$envId/database',
    path: '/environment/$envId/database',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAgentAgentIdConversationsRoute =
  LayoutAgentAgentIdConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => LayoutAgentAgentIdRoute,
  } as any)
const LayoutAdminMarketplaceMarketplaceIdRoute =
  LayoutAdminMarketplaceMarketplaceIdRouteImport.update({
    id: '/admin/marketplace/$marketplaceId',
    path: '/admin/marketplace/$marketplaceId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminMarketplacePluginPluginIdRoute =
  LayoutAdminMarketplacePluginPluginIdRouteImport.update({
    id: '/admin/marketplace/plugin/$pluginId',
    path: '/admin/marketplace/plugin/$pluginId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/activities': typeof LayoutActivitiesRoute
  '/agents': typeof LayoutAgentsRoute
  '/credentials': typeof LayoutCredentialsRoute
  '/items': typeof LayoutItemsRoute
  '/knowledge-sources': typeof LayoutKnowledgeSourcesRoute
  '/sessions': typeof LayoutSessionsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/tasks': typeof LayoutTasksRoute
  '/dashboard-fullscreen/$dashboardId': typeof DashboardFullscreenDashboardIdRoute
  '/guest/$guestShareToken': typeof GuestGuestShareTokenRoute
  '/guest/file-viewer': typeof GuestFileViewerRoute
  '/oauth/mcp-consent': typeof OauthMcpConsentRoute
  '/webapp/$webappToken': typeof WebappWebappTokenRoute
  '/': typeof LayoutIndexRoute
  '/admin/marketplaces': typeof LayoutAdminMarketplacesRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/agent/$agentId': typeof LayoutAgentAgentIdRouteWithChildren
  '/agent/creating': typeof LayoutAgentCreatingRoute
  '/credential/$credentialId': typeof LayoutCredentialCredentialIdRoute
  '/dashboards/$dashboardId': typeof LayoutDashboardsDashboardIdRoute
  '/knowledge-source/$sourceId': typeof LayoutKnowledgeSourceSourceIdRoute
  '/session/$sessionId': typeof LayoutSessionSessionIdRoute
  '/task/$taskId': typeof LayoutTaskTaskIdRoute
  '/credentials/oauth/callback': typeof CredentialsOauthCallbackRoute
  '/dashboards': typeof LayoutDashboardsIndexRoute
  '/sessions/': typeof LayoutSessionsIndexRoute
  '/admin/marketplace/$marketplaceId': typeof LayoutAdminMarketplaceMarketplaceIdRoute
  '/agent/$agentId/conversations': typeof LayoutAgentAgentIdConversationsRoute
  '/environment/$envId/database': typeof LayoutEnvironmentEnvIdDatabaseRoute
  '/environment/$envId/file': typeof LayoutEnvironmentEnvIdFileRoute
  '/sessions/agent/$agentId': typeof LayoutSessionsAgentAgentIdRoute
  '/admin/marketplace/plugin/$pluginId': typeof LayoutAdminMarketplacePluginPluginIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/activities': typeof LayoutActivitiesRoute
  '/agents': typeof LayoutAgentsRoute
  '/credentials': typeof LayoutCredentialsRoute
  '/items': typeof LayoutItemsRoute
  '/knowledge-sources': typeof LayoutKnowledgeSourcesRoute
  '/settings': typeof LayoutSettingsRoute
  '/tasks': typeof LayoutTasksRoute
  '/dashboard-fullscreen/$dashboardId': typeof DashboardFullscreenDashboardIdRoute
  '/guest/$guestShareToken': typeof GuestGuestShareTokenRoute
  '/guest/file-viewer': typeof GuestFileViewerRoute
  '/oauth/mcp-consent': typeof OauthMcpConsentRoute
  '/webapp/$webappToken': typeof WebappWebappTokenRoute
  '/': typeof LayoutIndexRoute
  '/admin/marketplaces': typeof LayoutAdminMarketplacesRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/agent/$agentId': typeof LayoutAgentAgentIdRouteWithChildren
  '/agent/creating': typeof LayoutAgentCreatingRoute
  '/credential/$credentialId': typeof LayoutCredentialCredentialIdRoute
  '/dashboards/$dashboardId': typeof LayoutDashboardsDashboardIdRoute
  '/knowledge-source/$sourceId': typeof LayoutKnowledgeSourceSourceIdRoute
  '/session/$sessionId': typeof LayoutSessionSessionIdRoute
  '/task/$taskId': typeof LayoutTaskTaskIdRoute
  '/credentials/oauth/callback': typeof CredentialsOauthCallbackRoute
  '/dashboards': typeof LayoutDashboardsIndexRoute
  '/sessions': typeof LayoutSessionsIndexRoute
  '/admin/marketplace/$marketplaceId': typeof LayoutAdminMarketplaceMarketplaceIdRoute
  '/agent/$agentId/conversations': typeof LayoutAgentAgentIdConversationsRoute
  '/environment/$envId/database': typeof LayoutEnvironmentEnvIdDatabaseRoute
  '/environment/$envId/file': typeof LayoutEnvironmentEnvIdFileRoute
  '/sessions/agent/$agentId': typeof LayoutSessionsAgentAgentIdRoute
  '/admin/marketplace/plugin/$pluginId': typeof LayoutAdminMarketplacePluginPluginIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/activities': typeof LayoutActivitiesRoute
  '/_layout/agents': typeof LayoutAgentsRoute
  '/_layout/credentials': typeof LayoutCredentialsRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/knowledge-sources': typeof LayoutKnowledgeSourcesRoute
  '/_layout/sessions': typeof LayoutSessionsRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tasks': typeof LayoutTasksRoute
  '/dashboard-fullscreen/$dashboardId': typeof DashboardFullscreenDashboardIdRoute
  '/guest/$guestShareToken': typeof GuestGuestShareTokenRoute
  '/guest/file-viewer': typeof GuestFileViewerRoute
  '/oauth/mcp-consent': typeof OauthMcpConsentRoute
  '/webapp/$webappToken': typeof WebappWebappTokenRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/marketplaces': typeof LayoutAdminMarketplacesRoute
  '/_layout/admin/users': typeof LayoutAdminUsersRoute
  '/_layout/agent/$agentId': typeof LayoutAgentAgentIdRouteWithChildren
  '/_layout/agent/creating': typeof LayoutAgentCreatingRoute
  '/_layout/credential/$credentialId': typeof LayoutCredentialCredentialIdRoute
  '/_layout/dashboards/$dashboardId': typeof LayoutDashboardsDashboardIdRoute
  '/_layout/knowledge-source/$sourceId': typeof LayoutKnowledgeSourceSourceIdRoute
  '/_layout/session/$sessionId': typeof LayoutSessionSessionIdRoute
  '/_layout/task/$taskId': typeof LayoutTaskTaskIdRoute
  '/credentials/oauth/callback': typeof CredentialsOauthCallbackRoute
  '/_layout/dashboards/': typeof LayoutDashboardsIndexRoute
  '/_layout/sessions/': typeof LayoutSessionsIndexRoute
  '/_layout/admin/marketplace/$marketplaceId': typeof LayoutAdminMarketplaceMarketplaceIdRoute
  '/_layout/agent/$agentId/conversations': typeof LayoutAgentAgentIdConversationsRoute
  '/_layout/environment/$envId/database': typeof LayoutEnvironmentEnvIdDatabaseRoute
  '/_layout/environment/$envId/file': typeof LayoutEnvironmentEnvIdFileRoute
  '/_layout/sessions/agent/$agentId': typeof LayoutSessionsAgentAgentIdRoute
  '/_layout/admin/marketplace/plugin/$pluginId': typeof LayoutAdminMarketplacePluginPluginIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/activities'
    | '/agents'
    | '/credentials'
    | '/items'
    | '/knowledge-sources'
    | '/sessions'
    | '/settings'
    | '/tasks'
    | '/dashboard-fullscreen/$dashboardId'
    | '/guest/$guestShareToken'
    | '/guest/file-viewer'
    | '/oauth/mcp-consent'
    | '/webapp/$webappToken'
    | '/'
    | '/admin/marketplaces'
    | '/admin/users'
    | '/agent/$agentId'
    | '/agent/creating'
    | '/credential/$credentialId'
    | '/dashboards/$dashboardId'
    | '/knowledge-source/$sourceId'
    | '/session/$sessionId'
    | '/task/$taskId'
    | '/credentials/oauth/callback'
    | '/dashboards'
    | '/sessions/'
    | '/admin/marketplace/$marketplaceId'
    | '/agent/$agentId/conversations'
    | '/environment/$envId/database'
    | '/environment/$envId/file'
    | '/sessions/agent/$agentId'
    | '/admin/marketplace/plugin/$pluginId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/activities'
    | '/agents'
    | '/credentials'
    | '/items'
    | '/knowledge-sources'
    | '/settings'
    | '/tasks'
    | '/dashboard-fullscreen/$dashboardId'
    | '/guest/$guestShareToken'
    | '/guest/file-viewer'
    | '/oauth/mcp-consent'
    | '/webapp/$webappToken'
    | '/'
    | '/admin/marketplaces'
    | '/admin/users'
    | '/agent/$agentId'
    | '/agent/creating'
    | '/credential/$credentialId'
    | '/dashboards/$dashboardId'
    | '/knowledge-source/$sourceId'
    | '/session/$sessionId'
    | '/task/$taskId'
    | '/credentials/oauth/callback'
    | '/dashboards'
    | '/sessions'
    | '/admin/marketplace/$marketplaceId'
    | '/agent/$agentId/conversations'
    | '/environment/$envId/database'
    | '/environment/$envId/file'
    | '/sessions/agent/$agentId'
    | '/admin/marketplace/plugin/$pluginId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/activities'
    | '/_layout/agents'
    | '/_layout/credentials'
    | '/_layout/items'
    | '/_layout/knowledge-sources'
    | '/_layout/sessions'
    | '/_layout/settings'
    | '/_layout/tasks'
    | '/dashboard-fullscreen/$dashboardId'
    | '/guest/$guestShareToken'
    | '/guest/file-viewer'
    | '/oauth/mcp-consent'
    | '/webapp/$webappToken'
    | '/_layout/'
    | '/_layout/admin/marketplaces'
    | '/_layout/admin/users'
    | '/_layout/agent/$agentId'
    | '/_layout/agent/creating'
    | '/_layout/credential/$credentialId'
    | '/_layout/dashboards/$dashboardId'
    | '/_layout/knowledge-source/$sourceId'
    | '/_layout/session/$sessionId'
    | '/_layout/task/$taskId'
    | '/credentials/oauth/callback'
    | '/_layout/dashboards/'
    | '/_layout/sessions/'
    | '/_layout/admin/marketplace/$marketplaceId'
    | '/_layout/agent/$agentId/conversations'
    | '/_layout/environment/$envId/database'
    | '/_layout/environment/$envId/file'
    | '/_layout/sessions/agent/$agentId'
    | '/_layout/admin/marketplace/plugin/$pluginId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  DashboardFullscreenDashboardIdRoute: typeof DashboardFullscreenDashboardIdRoute
  GuestGuestShareTokenRoute: typeof GuestGuestShareTokenRoute
  GuestFileViewerRoute: typeof GuestFileViewerRoute
  OauthMcpConsentRoute: typeof OauthMcpConsentRoute
  WebappWebappTokenRoute: typeof WebappWebappTokenRoute
  CredentialsOauthCallbackRoute: typeof CredentialsOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/webapp/$webappToken': {
      id: '/webapp/$webappToken'
      path: '/webapp/$webappToken'
      fullPath: '/webapp/$webappToken'
      preLoaderRoute: typeof WebappWebappTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/mcp-consent': {
      id: '/oauth/mcp-consent'
      path: '/oauth/mcp-consent'
      fullPath: '/oauth/mcp-consent'
      preLoaderRoute: typeof OauthMcpConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest/file-viewer': {
      id: '/guest/file-viewer'
      path: '/guest/file-viewer'
      fullPath: '/guest/file-viewer'
      preLoaderRoute: typeof GuestFileViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest/$guestShareToken': {
      id: '/guest/$guestShareToken'
      path: '/guest/$guestShareToken'
      fullPath: '/guest/$guestShareToken'
      preLoaderRoute: typeof GuestGuestShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-fullscreen/$dashboardId': {
      id: '/dashboard-fullscreen/$dashboardId'
      path: '/dashboard-fullscreen/$dashboardId'
      fullPath: '/dashboard-fullscreen/$dashboardId'
      preLoaderRoute: typeof DashboardFullscreenDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/tasks': {
      id: '/_layout/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof LayoutTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sessions': {
      id: '/_layout/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof LayoutSessionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge-sources': {
      id: '/_layout/knowledge-sources'
      path: '/knowledge-sources'
      fullPath: '/knowledge-sources'
      preLoaderRoute: typeof LayoutKnowledgeSourcesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/credentials': {
      id: '/_layout/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof LayoutCredentialsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents': {
      id: '/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof LayoutAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/activities': {
      id: '/_layout/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof LayoutActivitiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sessions/': {
      id: '/_layout/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof LayoutSessionsIndexRouteImport
      parentRoute: typeof LayoutSessionsRoute
    }
    '/_layout/dashboards/': {
      id: '/_layout/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof LayoutDashboardsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/credentials/oauth/callback': {
      id: '/credentials/oauth/callback'
      path: '/credentials/oauth/callback'
      fullPath: '/credentials/oauth/callback'
      preLoaderRoute: typeof CredentialsOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/task/$taskId': {
      id: '/_layout/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof LayoutTaskTaskIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/session/$sessionId': {
      id: '/_layout/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof LayoutSessionSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/knowledge-source/$sourceId': {
      id: '/_layout/knowledge-source/$sourceId'
      path: '/knowledge-source/$sourceId'
      fullPath: '/knowledge-source/$sourceId'
      preLoaderRoute: typeof LayoutKnowledgeSourceSourceIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboards/$dashboardId': {
      id: '/_layout/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof LayoutDashboardsDashboardIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/credential/$credentialId': {
      id: '/_layout/credential/$credentialId'
      path: '/credential/$credentialId'
      fullPath: '/credential/$credentialId'
      preLoaderRoute: typeof LayoutCredentialCredentialIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agent/creating': {
      id: '/_layout/agent/creating'
      path: '/agent/creating'
      fullPath: '/agent/creating'
      preLoaderRoute: typeof LayoutAgentCreatingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agent/$agentId': {
      id: '/_layout/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/agent/$agentId'
      preLoaderRoute: typeof LayoutAgentAgentIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/users': {
      id: '/_layout/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof LayoutAdminUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/marketplaces': {
      id: '/_layout/admin/marketplaces'
      path: '/admin/marketplaces'
      fullPath: '/admin/marketplaces'
      preLoaderRoute: typeof LayoutAdminMarketplacesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sessions/agent/$agentId': {
      id: '/_layout/sessions/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/sessions/agent/$agentId'
      preLoaderRoute: typeof LayoutSessionsAgentAgentIdRouteImport
      parentRoute: typeof LayoutSessionsRoute
    }
    '/_layout/environment/$envId/file': {
      id: '/_layout/environment/$envId/file'
      path: '/environment/$envId/file'
      fullPath: '/environment/$envId/file'
      preLoaderRoute: typeof LayoutEnvironmentEnvIdFileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/environment/$envId/database': {
      id: '/_layout/environment/$envId/database'
      path: '/environment/$envId/database'
      fullPath: '/environment/$envId/database'
      preLoaderRoute: typeof LayoutEnvironmentEnvIdDatabaseRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agent/$agentId/conversations': {
      id: '/_layout/agent/$agentId/conversations'
      path: '/conversations'
      fullPath: '/agent/$agentId/conversations'
      preLoaderRoute: typeof LayoutAgentAgentIdConversationsRouteImport
      parentRoute: typeof LayoutAgentAgentIdRoute
    }
    '/_layout/admin/marketplace/$marketplaceId': {
      id: '/_layout/admin/marketplace/$marketplaceId'
      path: '/admin/marketplace/$marketplaceId'
      fullPath: '/admin/marketplace/$marketplaceId'
      preLoaderRoute: typeof LayoutAdminMarketplaceMarketplaceIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/marketplace/plugin/$pluginId': {
      id: '/_layout/admin/marketplace/plugin/$pluginId'
      path: '/admin/marketplace/plugin/$pluginId'
      fullPath: '/admin/marketplace/plugin/$pluginId'
      preLoaderRoute: typeof LayoutAdminMarketplacePluginPluginIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutSessionsRouteChildren {
  LayoutSessionsIndexRoute: typeof LayoutSessionsIndexRoute
  LayoutSessionsAgentAgentIdRoute: typeof LayoutSessionsAgentAgentIdRoute
}

const LayoutSessionsRouteChildren: LayoutSessionsRouteChildren = {
  LayoutSessionsIndexRoute: LayoutSessionsIndexRoute,
  LayoutSessionsAgentAgentIdRoute: LayoutSessionsAgentAgentIdRoute,
}

const LayoutSessionsRouteWithChildren = LayoutSessionsRoute._addFileChildren(
  LayoutSessionsRouteChildren,
)

interface LayoutAgentAgentIdRouteChildren {
  LayoutAgentAgentIdConversationsRoute: typeof LayoutAgentAgentIdConversationsRoute
}

const LayoutAgentAgentIdRouteChildren: LayoutAgentAgentIdRouteChildren = {
  LayoutAgentAgentIdConversationsRoute: LayoutAgentAgentIdConversationsRoute,
}

const LayoutAgentAgentIdRouteWithChildren =
  LayoutAgentAgentIdRoute._addFileChildren(LayoutAgentAgentIdRouteChildren)

interface LayoutRouteChildren {
  LayoutActivitiesRoute: typeof LayoutActivitiesRoute
  LayoutAgentsRoute: typeof LayoutAgentsRoute
  LayoutCredentialsRoute: typeof LayoutCredentialsRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutKnowledgeSourcesRoute: typeof LayoutKnowledgeSourcesRoute
  LayoutSessionsRoute: typeof LayoutSessionsRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTasksRoute: typeof LayoutTasksRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAdminMarketplacesRoute: typeof LayoutAdminMarketplacesRoute
  LayoutAdminUsersRoute: typeof LayoutAdminUsersRoute
  LayoutAgentAgentIdRoute: typeof LayoutAgentAgentIdRouteWithChildren
  LayoutAgentCreatingRoute: typeof LayoutAgentCreatingRoute
  LayoutCredentialCredentialIdRoute: typeof LayoutCredentialCredentialIdRoute
  LayoutDashboardsDashboardIdRoute: typeof LayoutDashboardsDashboardIdRoute
  LayoutKnowledgeSourceSourceIdRoute: typeof LayoutKnowledgeSourceSourceIdRoute
  LayoutSessionSessionIdRoute: typeof LayoutSessionSessionIdRoute
  LayoutTaskTaskIdRoute: typeof LayoutTaskTaskIdRoute
  LayoutDashboardsIndexRoute: typeof LayoutDashboardsIndexRoute
  LayoutAdminMarketplaceMarketplaceIdRoute: typeof LayoutAdminMarketplaceMarketplaceIdRoute
  LayoutEnvironmentEnvIdDatabaseRoute: typeof LayoutEnvironmentEnvIdDatabaseRoute
  LayoutEnvironmentEnvIdFileRoute: typeof LayoutEnvironmentEnvIdFileRoute
  LayoutAdminMarketplacePluginPluginIdRoute: typeof LayoutAdminMarketplacePluginPluginIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutActivitiesRoute: LayoutActivitiesRoute,
  LayoutAgentsRoute: LayoutAgentsRoute,
  LayoutCredentialsRoute: LayoutCredentialsRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutKnowledgeSourcesRoute: LayoutKnowledgeSourcesRoute,
  LayoutSessionsRoute: LayoutSessionsRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTasksRoute: LayoutTasksRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAdminMarketplacesRoute: LayoutAdminMarketplacesRoute,
  LayoutAdminUsersRoute: LayoutAdminUsersRoute,
  LayoutAgentAgentIdRoute: LayoutAgentAgentIdRouteWithChildren,
  LayoutAgentCreatingRoute: LayoutAgentCreatingRoute,
  LayoutCredentialCredentialIdRoute: LayoutCredentialCredentialIdRoute,
  LayoutDashboardsDashboardIdRoute: LayoutDashboardsDashboardIdRoute,
  LayoutKnowledgeSourceSourceIdRoute: LayoutKnowledgeSourceSourceIdRoute,
  LayoutSessionSessionIdRoute: LayoutSessionSessionIdRoute,
  LayoutTaskTaskIdRoute: LayoutTaskTaskIdRoute,
  LayoutDashboardsIndexRoute: LayoutDashboardsIndexRoute,
  LayoutAdminMarketplaceMarketplaceIdRoute:
    LayoutAdminMarketplaceMarketplaceIdRoute,
  LayoutEnvironmentEnvIdDatabaseRoute: LayoutEnvironmentEnvIdDatabaseRoute,
  LayoutEnvironmentEnvIdFileRoute: LayoutEnvironmentEnvIdFileRoute,
  LayoutAdminMarketplacePluginPluginIdRoute:
    LayoutAdminMarketplacePluginPluginIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  DashboardFullscreenDashboardIdRoute: DashboardFullscreenDashboardIdRoute,
  GuestGuestShareTokenRoute: GuestGuestShareTokenRoute,
  GuestFileViewerRoute: GuestFileViewerRoute,
  OauthMcpConsentRoute: OauthMcpConsentRoute,
  WebappWebappTokenRoute: WebappWebappTokenRoute,
  CredentialsOauthCallbackRoute: CredentialsOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
