"""
Google ADK Wrapper Prompts

This module provides tool and system prompts for the Google ADK workflow runner adapter.
These prompts are injected before the main prompt generated by prompt_generator.
"""

import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Directory containing prompt files
PROMPTS_DIR = Path(__file__).parent


def load_prompt(filename: str) -> Optional[str]:
    """
    Load a prompt file from this directory.

    Args:
        filename: Name of the prompt file (e.g., 'general_system_prompt.md')

    Returns:
        Content of the prompt file, or None if not found
    """
    prompt_path = PROMPTS_DIR / filename
    if prompt_path.exists():
        try:
            with open(prompt_path, 'r', encoding='utf-8') as f:
                content = f.read().strip()
                logger.debug(f"Loaded prompt from {filename} ({len(content)} chars)")
                return content
        except Exception as e:
            logger.error(f"Failed to load prompt {filename}: {e}")
            return None
    else:
        logger.warning(f"Prompt file not found: {prompt_path}")
        return None


def get_general_system_prompt() -> Optional[str]:
    """Load the general system prompt with tool usage guidelines."""
    return load_prompt('general_system_prompt.md')


def get_read_tool_prompt() -> Optional[str]:
    """Load the Read tool instructions."""
    return load_prompt('read_tool_prompt.md')


def get_bash_tool_prompt() -> Optional[str]:
    """Load the Bash tool instructions."""
    return load_prompt('bash_tool_prompt.md')


def get_combined_tool_prompts() -> str:
    """
    Get all tool prompts combined into a single string.

    Returns:
        Combined prompt string with all tool instructions
    """
    parts = []

    # Load general system prompt
    general_prompt = get_general_system_prompt()
    if general_prompt:
        parts.append(general_prompt)

    # Load tool-specific prompts
    read_prompt = get_read_tool_prompt()
    if read_prompt:
        parts.append(f"\n\n---\n\n{read_prompt}")

    bash_prompt = get_bash_tool_prompt()
    if bash_prompt:
        parts.append(f"\n\n---\n\n{bash_prompt}")

    combined = "\n".join(parts)
    logger.info(f"Combined tool prompts: {len(combined)} chars total")
    return combined
